#!/usr/bin/env python3
"""Translate files 11-12+13: Claude in action + Other ways to work + What's next."""
import os

FOLDER = os.path.dirname(os.path.abspath(__file__))

COMMON = {
    'Header Navigation': '헤더 내비게이션',
    'Anthropic Academy': 'Anthropic 아카데미',
    '>Courses<': '>강좌<',
    'Sign Out': '로그아웃',
    '>Previous<': '>이전<',
    '>Next<': '>다음<',
    '>Downloads<': '>다운로드<',
    'Learning objectives': '학습 목표',
    "What you'll learn": '학습 내용',
    'Lesson reflection': '레슨 되돌아보기',
    'Acknowledgments and license': '감사의 말 및 라이선스',
    'Share your feedback': '피드백을 공유해 주세요',
    "As you progress through the course, we'd love to hear from you about how you are using concepts from the course in your work and any feedback you may have. Share your feedback": "강좌를 진행하면서, 강좌의 개념을 업무에 어떻게 활용하고 계신지, 그리고 피드백이 있으시면 알려주세요. 피드백을 공유해 주세요",
    '>What is Claude?<': '>Claude란 무엇인가?<',
    '>Your first conversation with Claude<': '>Claude와의 첫 대화<',
    '>Getting better results<': '>더 나은 결과 얻기<',
    '>Claude desktop app: Chat, Cowork, Code<': '>Claude 데스크톱 앱: Chat, Cowork, Code<',
    '>Introduction to projects<': '>프로젝트 소개<',
    '>Creating with artifacts<': '>아티팩트로 만들기<',
    '>Working with skills<': '>스킬 활용하기<',
    '>Connecting your tools<': '>도구 연결하기<',
    '>Enterprise search<': '>Enterprise 검색<',
    '>Research mode for deep dives<': '>심층 분석을 위한 Research 모드<',
    '>Claude in action: use-cases by role<': '>Claude 활용 사례: 역할별 사용 사례<',
    '>Other ways to work with Claude<': '>Claude와 함께 일하는 다른 방법<',
    ">What's next?<": '>다음 단계는?<',
    '>Certificate of completion<': '>수료 인증서<',
    'title="What is Claude?"': 'title="Claude란 무엇인가?"',
    'title="Your first conversation with Claude"': 'title="Claude와의 첫 대화"',
    'title="Getting better results"': 'title="더 나은 결과 얻기"',
    'title="Claude desktop app: Chat, Cowork, Code"': 'title="Claude 데스크톱 앱: Chat, Cowork, Code"',
    'title="Introduction to projects"': 'title="프로젝트 소개"',
    'title="Creating with artifacts"': 'title="아티팩트로 만들기"',
    'title="Working with skills"': 'title="스킬 활용하기"',
    'title="Connecting your tools"': 'title="도구 연결하기"',
    'title="Enterprise search"': 'title="Enterprise 검색"',
    'title="Research mode for deep dives"': 'title="심층 분석을 위한 Research 모드"',
    'title="Claude in action: use-cases by role"': 'title="Claude 활용 사례: 역할별 사용 사례"',
    'title="Other ways to work with Claude"': 'title="Claude와 함께 일하는 다른 방법"',
    '''title="What's next?"''': 'title="다음 단계는?"',
    'title="Certificate of completion"': 'title="수료 인증서"',
    '- What is Claude?': '- Claude란 무엇인가?',
    '- Your first conversation with Claude': '- Claude와의 첫 대화',
    '- Getting better results': '- 더 나은 결과 얻기',
    '- Claude desktop app: Chat, Cowork, Code': '- Claude 데스크톱 앱: Chat, Cowork, Code',
    '- Introduction to projects': '- 프로젝트 소개',
    '- Creating with artifacts': '- 아티팩트로 만들기',
    '- Working with skills': '- 스킬 활용하기',
    '- Connecting your tools': '- 도구 연결하기',
    '- Enterprise search': '- Enterprise 검색',
    '- Research mode for deep dives': '- 심층 분석을 위한 Research 모드',
    '- Claude in action: use-cases by role': '- Claude 활용 사례: 역할별 사용 사례',
    '- Other ways to work with Claude': '- Claude와 함께 일하는 다른 방법',
    "- What's next?": '- 다음 단계는?',
    '- Certificate of completion': '- 수료 인증서',
    'By the end of this lesson, you will be able to:': '이 레슨을 마치면 다음을 할 수 있습니다:',
    'Anthropic Help Center': 'Anthropic 도움말 센터',
}

FILES = {
    'Claude in action': {
        'Claude in action: use-cases by role': 'Claude 활용 사례: 역할별 사용 사례',
        'Describe 2-3 use-cases for claude.ai that you can try right away': '바로 시도할 수 있는 claude.ai의 2~3가지 사용 사례를 설명할 수 있습니다',
        'Know where to go to find additional use-case inspiration': '추가 사용 사례 영감을 찾을 수 있는 곳을 알 수 있습니다',
        'No matter what you do, Claude can help streamline your work. This lesson highlights practical use cases organized by role, so you can see how Claude applies to your specific work context.': '어떤 업무를 하든 Claude는 작업을 간소화하는 데 도움을 줄 수 있습니다. 이 레슨에서는 역할별로 구성된 실용적인 사용 사례를 소개하므로, Claude가 특정 업무 맥락에 어떻게 적용되는지 볼 수 있습니다.',
        'Each use case below links to a detailed guide in our Use Case Gallery with step-by-step instructions you can follow.': '아래 각 사용 사례는 단계별 지침이 포함된 사용 사례 갤러리의 상세 가이드로 연결됩니다.',
        'General professional use': '일반 전문 업무 활용',
        'These use cases apply across many roles and industries.': '이 사용 사례는 다양한 역할과 산업에 걸쳐 적용됩니다.',
        'Generate project status reports': '프로젝트 현황 보고서 생성',
        '– Keep stakeholders informed with clear, consistent updates': '– 명확하고 일관된 업데이트로 이해관계자에게 정보 제공',
        'Analyze patterns in user feedback': '사용자 피드백의 패턴 분석',
        '– Extract insights from customer comments and survey responses': '– 고객 의견 및 설문 응답에서 인사이트 추출',
        'Package your brand guidelines in a skill': '브랜드 가이드라인을 스킬로 패키징',
        '– Create a reusable Claude skill that applies your brand standards': '– 브랜드 표준을 적용하는 재사용 가능한 Claude 스킬 생성',
        'Sales professionals can use Claude to accelerate deal preparation, create compelling materials, and stay on top of competitive intelligence.': '영업 전문가는 Claude를 사용하여 딜 준비를 가속하고, 설득력 있는 자료를 만들며, 경쟁 정보를 파악할 수 있습니다.',
        'Build a battle card library': '배틀 카드 라이브러리 구축',
        '– Create competitive intelligence resources that help your team win deals': '– 팀이 거래를 성사시키는 데 도움이 되는 경쟁 정보 자료 생성',
        'Prepare for sales deals': '영업 거래 준비',
        '– Research prospects and organize your talking points before important meetings': '– 중요한 회의 전에 잠재 고객을 조사하고 핵심 논점 정리',
        'Create sales reports': '영업 보고서 작성',
        '– Turn your pipeline data into clear, actionable reports': '– 파이프라인 데이터를 명확하고 실행 가능한 보고서로 전환',
        'Marketers can leverage Claude to analyze performance data and efficiently repurpose content across channels.': '마케터는 Claude를 활용하여 성과 데이터를 분석하고 채널 간 콘텐츠를 효율적으로 재활용할 수 있습니다.',
        'Analyze campaign performance': '캠페인 성과 분석',
        '– Extract insights from campaign metrics to inform your strategy': '– 캠페인 지표에서 인사이트를 추출하여 전략에 반영',
        'Adapt content across platforms': '플랫폼 간 콘텐츠 적응',
        '– Efficiently repurpose content for different channels and audiences': '– 다양한 채널과 대상에 맞게 콘텐츠를 효율적으로 재활용',
        'Finance professionals can use Claude to build models, draft documents, and make sense of complex spreadsheets.': '재무 전문가는 Claude를 사용하여 모델을 구축하고, 문서 초안을 작성하며, 복잡한 스프레드시트를 이해할 수 있습니다.',
        'Build financial models': '재무 모델 구축',
        "– Create and refine financial projections with Claude's help": '– Claude의 도움으로 재무 예측 생성 및 개선',
        'Draft investment memos': '투자 메모 초안 작성',
        '– Structure and write investment analyses more efficiently': '– 투자 분석을 더 효율적으로 구조화하고 작성',
        'Understand and extend an inherited spreadsheet': '인계받은 스프레드시트 이해 및 확장',
        '– Decode complex spreadsheets and add new functionality': '– 복잡한 스프레드시트를 해독하고 새 기능 추가',
        'HR teams can use Claude to create better onboarding experiences and documentation.': 'HR 팀은 Claude를 사용하여 더 나은 온보딩 경험과 문서를 만들 수 있습니다.',
        'Create new hire onboarding guides': '신입 사원 온보딩 가이드 작성',
        '– Develop comprehensive onboarding materials tailored to different roles': '– 다양한 역할에 맞춘 포괄적인 온보딩 자료 개발',
        'Legal professionals can use Claude to track complex timelines and manage discovery processes.': '법률 전문가는 Claude를 사용하여 복잡한 일정을 추적하고 디스커버리 프로세스를 관리할 수 있습니다.',
        'Track discovery timelines and analyze patterns': '디스커버리 일정 추적 및 패턴 분석',
        '– Organize case timelines and identify key patterns in legal documents': '– 사건 일정을 정리하고 법률 문서에서 핵심 패턴 파악',
        'Researchers can use Claude to plan literature reviews and verify data analysis.': '연구자는 Claude를 사용하여 문헌 검토를 계획하고 데이터 분석을 검증할 수 있습니다.',
        'Plan your literature review': '문헌 검토 계획',
        '– Organize your approach to reviewing academic sources': '– 학술 자료 검토에 대한 접근 방식 정리',
        'Verify statistics from raw data': '원시 데이터에서 통계 검증',
        '– Double-check calculations and statistical analyses': '– 계산 및 통계 분석 재확인',
        'These examples are just the beginning. Visit the': '이 예시는 시작에 불과합니다. 방문하세요',
        'Use Case Gallery': '사용 사례 갤러리',
        'to browse the full collection and find inspiration for how Claude can help with your specific work.': '에서 전체 컬렉션을 탐색하고 Claude가 특정 업무에 어떻게 도움을 줄 수 있는지 영감을 얻으세요.',
        "In our final module, you'll meet a few more versions of Claude including Claude Code, Claude in Chrome, Claude in Excel, and Claude in Slack — each tailored to different types of working.": '마지막 모듈에서는 Claude Code, Claude in Chrome, Claude in Excel, Claude in Slack 등 다양한 유형의 작업에 맞춤화된 Claude의 다른 버전들을 만나게 됩니다.',
    },
    'Other ways to work with Claude': {
        'Other ways to work with Claude': 'Claude와 함께 일하는 다른 방법',
        'Understand when to use additional Claude products including Claude Code, Claude for Slack, Claude for Excel, and Claude for Chrome': 'Claude Code, Claude for Slack, Claude for Excel, Claude for Chrome을 포함한 추가 Claude 제품을 언제 사용해야 하는지 이해할 수 있습니다',
        'As we mentioned at the start of this course, Claude is an intelligence.': '이 강좌 시작 부분에서 언급했듯이, Claude는 지능입니다.',
        'is just one way of working with it.': '은 Claude와 작업하는 하나의 방법일 뿐입니다.',
        'Claude is also available in several specialized tools designed to meet you where you already work. This lesson introduces four additional ways to work with Claude, each tailored to specific workflows ': 'Claude는 이미 작업하고 있는 곳에서 만나도록 설계된 여러 전문 도구에서도 사용할 수 있습니다. 이 레슨에서는 특정 워크플로에 맞춤화된 Claude와 작업하는 네 가지 추가 방법을 소개합니다 ',
        'Claude Code is an agentic coding tool that works where you work — in your terminal, IDE, browser, or even in Slack. It understands your codebase, executes commands, and handles entire development work': 'Claude Code는 터미널, IDE, 브라우저, 심지어 Slack에서 작업하는 곳 어디서나 작동하는 에이전트형 코딩 도구입니다. 코드베이스를 이해하고, 명령을 실행하며, 전체 개발 작업을 처리합니다',
        'When to use Claude Code:': 'Claude Code 사용 시기:',
        'You want to build features by describing what you need in plain English, and have Claude write the code, run tests, and create commits': '필요한 것을 평이한 언어로 설명하여 기능을 구축하고, Claude가 코드를 작성하고, 테스트를 실행하며, 커밋을 생성하길 원할 때',
        'You need to debug issues by pasting error messages and having Claude analyze your codebase to identify and fix problems': '오류 메시지를 붙여넣고 Claude가 코드베이스를 분석하여 문제를 파악하고 수정하도록 할 때',
        "You're navigating an unfamiliar codebase and want to ask questions about how different parts work together": '익숙하지 않은 코드베이스를 탐색하면서 다양한 부분이 어떻게 함께 작동하는지 질문하고 싶을 때',
        'You want to automate tedious tasks like fixing lint errors, resolving merge conflicts, or writing release notes': 'lint 오류 수정, 병합 충돌 해결, 릴리스 노트 작성과 같은 지루한 작업을 자동화하고 싶을 때',
        'You prefer working in your terminal alongside your existing IDE and development tools rather than switching to a separate interface': '별도의 인터페이스로 전환하지 않고 기존 IDE 및 개발 도구와 함께 터미널에서 작업하는 것을 선호할 때',
        'Claude integrates directly with Slack, allowing you to get help in channels and threads or bring Slack context into your Claude conversations.': 'Claude는 Slack에 직접 통합되어 채널과 스레드에서 도움을 받거나 Slack 컨텍스트를 Claude 대화에 가져올 수 있습니다.',
        'When to use Claude in Slack:': 'Slack에서 Claude 사용 시기:',
        'You want to draft responses to messages, summarize lengthy threads, or break down complex discussions without leaving Slack': 'Slack을 떠나지 않고 메시지에 대한 답장 초안 작성, 긴 스레드 요약, 복잡한 논의 분석을 원할 때',
        'You need to prepare for meetings by having Claude pull together relevant conversations and shared documents from your workspace': 'Claude가 워크스페이스에서 관련 대화와 공유 문서를 모아 회의를 준비해야 할 때',
        "You're onboarding to a new team and want help understanding ongoing projects by reviewing channel history": '새 팀에 합류하여 채널 이력을 검토하며 진행 중인 프로젝트를 이해하는 데 도움이 필요할 때',
        'You want to hand off coding tasks directly from a bug report or feature discussion—just tag @Claude and it can spin up a Claude Code session using the surrounding context': '버그 리포트나 기능 논의에서 직접 코딩 작업을 넘기고 싶을 때—@Claude를 태그하면 주변 맥락을 사용하여 Claude Code 세션을 시작할 수 있습니다',
        'You need to quickly get answers about industry trends, technical concepts, or company information during a conversation': '대화 중 산업 트렌드, 기술 개념 또는 회사 정보에 대한 답변을 빠르게 얻어야 할 때',
        'Claude for Excel': 'Claude for Excel',
        'Claude for Excel brings Claude directly into Microsoft Excel through a sidebar, allowing you to analyze, understand, and modify spreadsheets through conversation.': 'Claude for Excel은 사이드바를 통해 Claude를 Microsoft Excel에 직접 가져와 대화를 통해 스프레드시트를 분석, 이해, 수정할 수 있게 합니다.',
        'When to use Claude for Excel:': 'Claude for Excel 사용 시기:',
        "You're working with a complex multi-tab workbook and want to understand how specific formulas or calculation flows work across sheets": '복잡한 다중 탭 통합 문서로 작업하면서 특정 수식이나 계산 흐름이 시트 간에 어떻게 작동하는지 이해하고 싶을 때',
        'You need to update assumptions or inputs across your model while preserving formula dependencies and relationships': '수식 의존성과 관계를 유지하면서 모델 전체의 가정이나 입력을 업데이트해야 할 때',
        "You're debugging spreadsheet errors like #REF!, #VALUE!, or circular references and want Claude to trace them to their source and suggest fixes": '#REF!, #VALUE! 또는 순환 참조와 같은 스프레드시트 오류를 디버깅하고 Claude가 원인을 추적하고 수정을 제안하길 원할 때',
        'You want to create new spreadsheets or populate existing templates with data while maintaining proper formula structure': '적절한 수식 구조를 유지하면서 새 스프레드시트를 만들거나 기존 템플릿에 데이터를 채우고 싶을 때',
        'You need to quickly build pivot tables or charts to visualize your data': '데이터를 시각화하기 위해 피벗 테이블이나 차트를 빠르게 만들어야 할 때',
        'Claude for Chrome': 'Claude for Chrome',
        "Claude for Chrome is a browser extension that adds Claude as a sidebar in Google Chrome. It can observe what you're working on and take actions directly within your browser.": 'Claude for Chrome은 Google Chrome에 사이드바로 Claude를 추가하는 브라우저 확장입니다. 작업 중인 내용을 관찰하고 브라우저 내에서 직접 작업을 수행할 수 있습니다.',
        'When to use Claude for Chrome:': 'Claude for Chrome 사용 시기:',
        'You want to summarize articles, research papers, or web pages while browsing': '브라우징하면서 기사, 연구 논문, 웹 페이지를 요약하고 싶을 때',
        'You need help drafting email responses or managing your inbox': '이메일 답장 초안 작성이나 받은편지함 관리에 도움이 필요할 때',
        "You're filling out repetitive forms and want to automate the process": '반복적인 양식을 작성하면서 프로세스를 자동화하고 싶을 때',
        'You want to test website features or navigate multi-step workflows without manually clicking through each step': '각 단계를 수동으로 클릭하지 않고 웹사이트 기능을 테스트하거나 다단계 워크플로를 탐색하고 싶을 때',
        'You need a browsing assistant that maintains context as you move between tabs and tasks': '탭과 작업 간 이동 시 맥락을 유지하는 브라우징 어시스턴트가 필요할 때',
        'Claude for Chrome is currently in research preview. Anthropic recommends using it for low-risk tasks on trusted websites. The extension asks for permission before taking high-risk actions like purchas': 'Claude for Chrome은 현재 연구 프리뷰 단계입니다. Anthropic은 신뢰할 수 있는 웹사이트에서 저위험 작업에 사용하는 것을 권장합니다. 확장은 구매와 같은 고위험 작업 전에 권한을 요청합니다',
        'Claude for Chrome is available for Claude Max subscribers. Join the waitlist at claude.ai/chrome.': 'Claude for Chrome은 Claude Max 구독자에게 제공됩니다. claude.ai/chrome에서 대기 목록에 가입하세요.',
        "Each of these tools extends Claude's capabilities into the specific environments where you work:": '이러한 각 도구는 Claude의 기능을 작업 환경으로 확장합니다:',
        'General tasks, research, writing, analysis, file creation': '일반 작업, 연구, 글쓰기, 분석, 파일 생성',
        'Web, desktop, and mobile apps': '웹, 데스크톱, 모바일 앱',
        'Software development, codebase navigation, git workflows': '소프트웨어 개발, 코드베이스 탐색, git 워크플로',
        'Terminal/command line, IDE, or your browser': '터미널/명령줄, IDE 또는 브라우저',
        'Claude/Claude Code in Slack': 'Claude/Claude Code in Slack',
        'Team collaboration, meeting prep, quick answers in context': '팀 협업, 회의 준비, 맥락 내 빠른 답변',
        'Spreadsheet analysis, financial modeling, formula debugging': '스프레드시트 분석, 재무 모델링, 수식 디버깅',
        'Microsoft Excel sidebar': 'Microsoft Excel 사이드바',
        'Web research, email management, browser automation': '웹 연구, 이메일 관리, 브라우저 자동화',
        'Chrome browser sidebar': 'Chrome 브라우저 사이드바',
        'Wrap up with a short recap of this course and a quiz to earn your certificate of completion that you can share on LinkedIn, and with your team.': '이 강좌의 간단한 요약과 퀴즈로 마무리하여 LinkedIn과 팀에 공유할 수 있는 수료 인증서를 받으세요.',
    },
    "What's next\uff1f": {
        'Estimated time: 5 minutes': '예상 소요 시간: 5분',
        "Congratulations on completing Claude 101! You've built a solid foundation for working with Claude effectively. Let's recap what you've learned and point you toward resources for continued growth.": "Claude 101을 완료하신 것을 축하합니다! Claude와 효과적으로 작업하기 위한 탄탄한 기반을 구축하셨습니다. 배운 내용을 요약하고 지속적인 성장을 위한 리소스를 안내합니다.",
        "What you've learned": '배운 내용',
        'Getting started with Claude': 'Claude 시작하기',
        "Claude is an AI assistant built to be helpful, harmless, and honest—more than a chatbot, it's a thinking partner for complex work": 'Claude는 유용하고, 무해하며, 정직하도록 구축된 AI 어시스턴트입니다—단순한 챗봇이 아닌 복잡한 작업을 위한 사고 파트너',
        'You can access Claude through web, desktop, and mobile apps, with your conversations syncing across devices': '웹, 데스크톱, 모바일 앱을 통해 Claude에 접근할 수 있으며, 대화가 기기 간 동기화됩니다',
        'Effective prompts set the stage (context), define the task (action), and specify rules (format and style)': '효과적인 프롬프트는 무대를 설정하고(맥락), 과제를 정의하며(작업), 규칙을 지정합니다(형식과 스타일)',
        'Getting better results': '더 나은 결과 얻기',
        'Iteration is key—treat first responses as starting points and refine through conversation': '반복이 핵심입니다—첫 응답을 출발점으로 삼고 대화를 통해 개선하세요',
        'Common challenges like generic responses or wrong tone can be fixed with more specific context': '일반적인 응답이나 잘못된 톤과 같은 흔한 문제는 더 구체적인 맥락으로 해결할 수 있습니다',
        'AI Fluency encompasses four competencies: Delegation, Description, Discernment, and Diligence': 'AI 활용 능력은 네 가지 역량을 포괄합니다: 위임(Delegation), 기술(Description), 판단(Discernment), 성실(Diligence)',
        'Organizing your work': '작업 정리하기',
        'Projects create dedicated workspaces with persistent knowledge, custom instructions, and team collaboration': '프로젝트는 지속적인 지식, 맞춤 지침, 팀 협업을 갖춘 전용 워크스페이스를 만듭니다',
        'Artifacts are standalone outputs like documents, code, diagrams, and interactive tools that Claude creates alongside your conversation': '아티팩트는 Claude가 대화와 함께 만드는 문서, 코드, 다이어그램, 대화형 도구와 같은 독립적인 결과물입니다',
        'Skills are instruction packages that teach Claude specialized workflows—including built-in document creation and custom skills you can create': '스킬은 Claude에게 전문 워크플로를 가르치는 지침 패키지입니다—내장 문서 생성 및 직접 만들 수 있는 맞춤 스킬 포함',
        "Expanding Claude's reach": 'Claude의 범위 확장하기',
        'Connectors link Claude to your tools (Google Workspace, Slack, Notion, and many more) so it can work with your actual data': '커넥터는 Claude를 도구(Google Workspace, Slack, Notion 등)에 연결하여 실제 데이터로 작업할 수 있게 합니다',
        "Enterprise Search provides a dedicated project for searching across your organization's knowledge sources": 'Enterprise 검색은 조직의 지식 소스를 검색하기 위한 전용 프로젝트를 제공합니다',
        'Research mode conducts systematic, multi-source investigations that would take hours to do manually': 'Research 모드는 수동으로 수시간이 걸리는 체계적이고 다중 소스 조사를 수행합니다',
        'Putting it all together': '모든 것을 종합하기',
        'Claude applies across roles—sales, marketing, finance, HR, legal, research, and beyond': 'Claude는 영업, 마케팅, 재무, HR, 법무, 연구 등 다양한 역할에 걸쳐 적용됩니다',
        'Beyond claude.ai, you can work with Claude through Claude Code, Slack, Excel, and Chrome': 'claude.ai 외에도 Claude Code, Slack, Excel, Chrome을 통해 Claude와 작업할 수 있습니다',
        'Additional resources': '추가 리소스',
        'Learn more about AI and Claude': 'AI와 Claude에 대해 더 알아보기',
        'AI Fluency courses': 'AI 활용 능력 강좌',
        '– Free courses on effective AI collaboration': '– 효과적인 AI 협업에 대한 무료 강좌',
        'Use Case Gallery': '사용 사례 갤러리',
        '– Step-by-step guides and prompts for powerful workflows': '– 강력한 워크플로를 위한 단계별 가이드 및 프롬프트',
        '– Detailed documentation and troubleshooting': '– 상세 문서 및 문제 해결',
        'Prompting documentation': '프롬프팅 문서',
        '– Comprehensive guide to getting the best results': '– 최고의 결과를 얻기 위한 종합 가이드',
        'Product-specific resources': '제품별 리소스',
        'Claude Code in Action': 'Claude Code 실전 활용',
        '– Course on using Claude for development workflows': '– 개발 워크플로에 Claude를 사용하는 강좌',
        'Connector Directory': '커넥터 디렉토리',
        '– Browse and connect your tools': '– 도구를 탐색하고 연결하세요',
        'A word of encouragement': '격려의 말',
        "The most important thing you can do now is just get started! The skills you've learned here will sharpen with practice, and you'll develop intuition for when and how Claude can help.": '지금 할 수 있는 가장 중요한 것은 그냥 시작하는 것입니다! 여기서 배운 기술은 연습을 통해 날카로워지고, Claude가 언제 어떻게 도울 수 있는지에 대한 직관이 생길 것입니다.',
        "Start simple. Pick one recurring task from your work this week and try it with Claude. Maybe it's drafting an email, summarizing meeting notes, or analyzing a spreadsheet. See what happens. Iterate. Learn what works for your specific needs.": '간단하게 시작하세요. 이번 주 업무에서 반복되는 작업 하나를 골라 Claude로 시도해 보세요. 이메일 초안 작성, 회의록 요약, 스프레드시트 분석일 수 있습니다. 어떤 일이 일어나는지 보세요. 반복하세요. 특정 요구에 맞는 것을 배우세요.',
        'Remember: Claude is designed to be a collaborator, not a replacement. The best results come when you bring your expertise, context, and judgment to the conversation.': '기억하세요: Claude는 대체가 아닌 협업자로 설계되었습니다. 전문성, 맥락, 판단력을 대화에 가져올 때 최고의 결과를 얻을 수 있습니다.',
        "We'd love to hear how this course has helped you and what we could improve. Share your feedback": '이 강좌가 어떻게 도움이 되었는지, 무엇을 개선할 수 있는지 듣고 싶습니다. 피드백을 공유해 주세요',
        'Certificate of completion': '수료 인증서',
    },
}

def translate_file(filepath, translations):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    all_trans = {**COMMON, **translations}
    sorted_items = sorted(all_trans.items(), key=lambda x: len(x[0]), reverse=True)
    for eng, kor in sorted_items:
        if eng in content:
            content = content.replace(eng, kor)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    return content != original

for lesson_name, translations in FILES.items():
    matches = [f for f in os.listdir(FOLDER)
               if f.startswith(lesson_name) and f.endswith('.html') and f != 'index.html']
    if not matches:
        print(f'  [SKIP] No file found for: {lesson_name}')
        continue
    fpath = os.path.join(FOLDER, matches[0])
    changed = translate_file(fpath, translations)
    status = 'TRANSLATED' if changed else 'NO CHANGE'
    print(f'  [{status}] {matches[0]}')

print('\nPart 6 translation complete!')
