#!/usr/bin/env python3
"""Translate files 5-6: Introduction to projects + Creating with artifacts."""
import os

FOLDER = os.path.dirname(os.path.abspath(__file__))

COMMON = {
    'Header Navigation': '헤더 내비게이션',
    'Anthropic Academy': 'Anthropic 아카데미',
    '>Courses<': '>강좌<',
    'Sign Out': '로그아웃',
    '>Previous<': '>이전<',
    '>Next<': '>다음<',
    '>Downloads<': '>다운로드<',
    'Learning objectives': '학습 목표',
    "What you'll learn": '학습 내용',
    'Lesson reflection': '레슨 되돌아보기',
    'Acknowledgments and license': '감사의 말 및 라이선스',
    'Share your feedback': '피드백을 공유해 주세요',
    "As you progress through the course, we'd love to hear from you about how you are using concepts from the course in your work and any feedback you may have. Share your feedback": "강좌를 진행하면서, 강좌의 개념을 업무에 어떻게 활용하고 계신지, 그리고 피드백이 있으시면 알려주세요. 피드백을 공유해 주세요",
    '>What is Claude?<': '>Claude란 무엇인가?<',
    '>Your first conversation with Claude<': '>Claude와의 첫 대화<',
    '>Getting better results<': '>더 나은 결과 얻기<',
    '>Claude desktop app: Chat, Cowork, Code<': '>Claude 데스크톱 앱: Chat, Cowork, Code<',
    '>Introduction to projects<': '>프로젝트 소개<',
    '>Creating with artifacts<': '>아티팩트로 만들기<',
    '>Working with skills<': '>스킬 활용하기<',
    '>Connecting your tools<': '>도구 연결하기<',
    '>Enterprise search<': '>Enterprise 검색<',
    '>Research mode for deep dives<': '>심층 분석을 위한 Research 모드<',
    '>Claude in action: use-cases by role<': '>Claude 활용 사례: 역할별 사용 사례<',
    '>Other ways to work with Claude<': '>Claude와 함께 일하는 다른 방법<',
    ">What's next?<": '>다음 단계는?<',
    '>Certificate of completion<': '>수료 인증서<',
    'title="What is Claude?"': 'title="Claude란 무엇인가?"',
    'title="Your first conversation with Claude"': 'title="Claude와의 첫 대화"',
    'title="Getting better results"': 'title="더 나은 결과 얻기"',
    'title="Claude desktop app: Chat, Cowork, Code"': 'title="Claude 데스크톱 앱: Chat, Cowork, Code"',
    'title="Introduction to projects"': 'title="프로젝트 소개"',
    'title="Creating with artifacts"': 'title="아티팩트로 만들기"',
    'title="Working with skills"': 'title="스킬 활용하기"',
    'title="Connecting your tools"': 'title="도구 연결하기"',
    'title="Enterprise search"': 'title="Enterprise 검색"',
    'title="Research mode for deep dives"': 'title="심층 분석을 위한 Research 모드"',
    'title="Claude in action: use-cases by role"': 'title="Claude 활용 사례: 역할별 사용 사례"',
    'title="Other ways to work with Claude"': 'title="Claude와 함께 일하는 다른 방법"',
    '''title="What's next?"''': 'title="다음 단계는?"',
    'title="Certificate of completion"': 'title="수료 인증서"',
    '- What is Claude?': '- Claude란 무엇인가?',
    '- Your first conversation with Claude': '- Claude와의 첫 대화',
    '- Getting better results': '- 더 나은 결과 얻기',
    '- Claude desktop app: Chat, Cowork, Code': '- Claude 데스크톱 앱: Chat, Cowork, Code',
    '- Introduction to projects': '- 프로젝트 소개',
    '- Creating with artifacts': '- 아티팩트로 만들기',
    '- Working with skills': '- 스킬 활용하기',
    '- Connecting your tools': '- 도구 연결하기',
    '- Enterprise search': '- Enterprise 검색',
    '- Research mode for deep dives': '- 심층 분석을 위한 Research 모드',
    '- Claude in action: use-cases by role': '- Claude 활용 사례: 역할별 사용 사례',
    '- Other ways to work with Claude': '- Claude와 함께 일하는 다른 방법',
    "- What's next?": '- 다음 단계는?',
    '- Certificate of completion': '- 수료 인증서',
    'By the end of this lesson, you will be able to:': '이 레슨을 마치면 다음을 할 수 있습니다:',
    "By the end of this lesson you'll be able to:": '이 레슨을 마치면 다음을 할 수 있습니다:',
    'Anthropic Help Center': 'Anthropic 도움말 센터',
    'Before moving on, consider:': '다음으로 넘어가기 전에 고려해 보세요:',
}

FILES = {
    'Introduction to projects': {
        'Introduction to projects': '프로젝트 소개',
        'Explain what projects are and when to use them': '프로젝트가 무엇이고 언제 사용해야 하는지 설명할 수 있습니다',
        'Create a new project with a name, description, and visibility settings': '이름, 설명, 공개 설정으로 새 프로젝트를 만들 수 있습니다',
        "Add documents and files to your project's knowledge base": '프로젝트의 지식 기반에 문서와 파일을 추가할 수 있습니다',
        "Write effective project instructions to guide Claude's behavior": 'Claude의 행동을 안내하는 효과적인 프로젝트 지침을 작성할 수 있습니다',
        'Share projects with teammates (for Claude for Work users)': '팀원과 프로젝트를 공유할 수 있습니다 (Claude for Work 사용자용)',
        'Video: Getting started with projects in Claude.ai': '영상: Claude.ai에서 프로젝트 시작하기',
        'Projects are self-contained workspaces': '프로젝트는 자체 완결적 워크스페이스입니다',
        'with their own memory, chat histories, knowledge bases, and customized instructions. Think of them as dedicated environments for specific work streams.': '자체 메모리, 채팅 기록, 지식 기반, 맞춤 지침을 갖추고 있습니다. 특정 작업 흐름을 위한 전용 환경으로 생각하세요.',
        "Project knowledge enhances Claude's understanding": '프로젝트 지식은 Claude의 이해력을 강화합니다',
        'by letting you upload relevant documents that Claude references across all chats within that project. No more re-uploading the same files each time.': '관련 문서를 업로드하면 Claude가 해당 프로젝트 내 모든 채팅에서 참조합니다. 매번 같은 파일을 다시 업로드할 필요가 없습니다.',
        "Project instructions guide Claude's behavior": '프로젝트 지침은 Claude의 행동을 안내합니다',
        '—you can specify tone, expertise level, response style, and more. These instructions apply to every conversation within the project.': '—톤, 전문성 수준, 응답 스타일 등을 지정할 수 있습니다. 이 지침은 프로젝트 내 모든 대화에 적용됩니다.',
        'Projects scale automatically': '프로젝트는 자동으로 확장됩니다',
        '. When your knowledge base approaches context limits, Claude seamlessly enables Retrieval Augmented Generation (RAG) mode to expand capacity by up to 10x while maintaining response quality.': '. 지식 기반이 컨텍스트 제한에 도달하면, Claude는 원활하게 RAG(검색 증강 생성) 모드를 활성화하여 응답 품질을 유지하면서 용량을 최대 10배 확장합니다.',
        'For Claude for Work users, projects enable collaboration': 'Claude for Work 사용자의 경우, 프로젝트는 협업을 가능하게 합니다',
        '. Share projects with teammates so everyone benefits from the same context, instructions, and accumulated knowledge.': '. 팀원과 프로젝트를 공유하여 모든 사람이 동일한 맥락, 지침, 축적된 지식의 혜택을 받을 수 있습니다.',
        'What are Projects?': '프로젝트란 무엇인가요?',
        'Projects are ideal for storing knowledge Claude should reference, organizing related chats around a specific topic or work area, and collaborating with team members who need access to the same shared ': '프로젝트는 Claude가 참조해야 할 지식을 저장하고, 특정 주제나 작업 영역 주변의 관련 채팅을 구성하며, 동일한 공유 리소스에 접근해야 하는 팀원과 협업하는 데 이상적입니다 ',
        'When to use Projects': '프로젝트를 사용해야 할 때',
        "Projects are particularly valuable when you're working on something ongoing—not just a one-off question. Consider creating a project when you have a workflow with:": '프로젝트는 일회성 질문이 아닌 지속적인 작업을 할 때 특히 유용합니다. 다음과 같은 워크플로가 있을 때 프로젝트 생성을 고려하세요:',
        "Reference materials you'll use repeatedly": '반복적으로 사용할 참고 자료',
        '(meeting notes, survey results, reports, historical data, etc.)': '(회의록, 설문 조사 결과, 보고서, 과거 데이터 등)',
        'Consistent requirements': '일관된 요구사항',
        'for how Claude should respond (always use formal language, always cite sources, always follow our template)': 'Claude가 어떻게 응답해야 하는지에 대해 (항상 격식체 사용, 항상 출처 인용, 항상 템플릿 준수)',
        'Team collaboration needs': '팀 협업 필요',
        'where multiple people should work from the same foundation': '여러 사람이 동일한 기반에서 작업해야 하는 경우',
        'Creating your first project': '첫 프로젝트 만들기',
        "Setting up a project takes just a few minutes. Here's how to get started:": '프로젝트 설정은 몇 분이면 됩니다. 시작하는 방법은 다음과 같습니다:',
        'Step 1: Set up your project': '1단계: 프로젝트 설정하기',
        'Hover over the left sidebar and click "Projects," or navigate directly to claude.ai/projects': '왼쪽 사이드바에 마우스를 올리고 "Projects"를 클릭하거나, claude.ai/projects로 직접 이동하세요',
        'Click "+ New Project" in the upper right corner': '오른쪽 상단의 "+ New Project"를 클릭하세요',
        'Give your project a descriptive name (e.g., "Q4 Marketing Campaign" or "Product Documentation")': '프로젝트에 설명적인 이름을 지정하세요 (예: "Q4 마케팅 캠페인" 또는 "제품 문서")',
        "Add a brief description of what you're working on. While Claude doesn't see this description directly, it helps you and your teammates understand the project's purpose.": "작업 내용에 대한 간략한 설명을 추가하세요. Claude는 이 설명을 직접 보지 못하지만, 프로젝트의 목적을 이해하는 데 도움이 됩니다.",
        'Choose your visibility settings: keep it private or share with your organization (for Claude for Work users)': '공개 설정을 선택하세요: 비공개로 유지하거나 조직과 공유 (Claude for Work 사용자용)',
        'Step 2: Add project instructions': '2단계: 프로젝트 지침 추가하기',
        'Project instructions tell Claude how to behave across all conversations in this project. Click on "Instructions" to open the instructions panel.': '프로젝트 지침은 이 프로젝트의 모든 대화에서 Claude의 행동 방식을 알려줍니다. "Instructions"를 클릭하여 지침 패널을 엽니다.',
        'Good project instructions typically include:': '좋은 프로젝트 지침에는 일반적으로 다음이 포함됩니다:',
        "Context about what you're working on:": '작업 내용에 대한 맥락:',
        '"This project is for creating marketing content for our B2B software product."': '"이 프로젝트는 B2B 소프트웨어 제품의 마케팅 콘텐츠를 만들기 위한 것입니다."',
        'Process instructions:': '프로세스 지침:',
        '"First consider a blog structure that will entice this audience, then write the draft."': '"먼저 이 대상 독자를 끌어들일 블로그 구조를 고려한 다음 초안을 작성하세요."',
        'Tone and style preferences:': '톤 및 스타일 선호:',
        '"Use a professional but conversational tone. Avoid jargon when possible."': '"전문적이지만 대화체 톤을 사용하세요. 가능하면 전문 용어를 피하세요."',
        'Specific requirements:': '특정 요구사항:',
        '"Always include a call-to-action at the end of marketing copy."': '"마케팅 카피 끝에 항상 행동 촉구를 포함하세요."',
        '''Once you've written your instructions, click "Save instructions." These will apply to every chat in this project and work alongside any user preferences and styles you've set.''': '''지침을 작성한 후 "Save instructions"를 클릭하세요. 이 지침은 이 프로젝트의 모든 채팅에 적용되며, 설정한 사용자 환경설정 및 스타일과 함께 작동합니다.''',
        'Step 3: Build your knowledge base': '3단계: 지식 기반 구축하기',
        "Your project's knowledge base is where you upload documents that Claude should reference. You'll find the files menu on the right side of your project's main page.": '프로젝트의 지식 기반은 Claude가 참조해야 할 문서를 업로드하는 곳입니다. 프로젝트 메인 페이지 오른쪽에서 파일 메뉴를 찾을 수 있습니다.',
        'Click the "+" button to add content. You can upload various file types including PDF, DOCX, CSV, TXT, HTML, and more. You can also connect to Google Drive to link documents directly.': '"+" 버튼을 클릭하여 콘텐츠를 추가하세요. PDF, DOCX, CSV, TXT, HTML 등 다양한 파일 유형을 업로드할 수 있습니다. Google Drive에 연결하여 문서를 직접 링크할 수도 있습니다.',
        'Reference documents (brand guidelines, style guides, templates)': '참고 문서 (브랜드 가이드라인, 스타일 가이드, 템플릿)',
        'Background materials (research reports, meeting notes, requirements docs)': '배경 자료 (연구 보고서, 회의록, 요구사항 문서)',
        'Examples of work you want Claude to emulate': 'Claude에게 따라 하길 원하는 작업 예시',
        'Technical documentation or specifications': '기술 문서 또는 사양',
        'Name your files descriptively. Claude uses file names to understand and retrieve the right information, so "Q4-2024-Brand-Guidelines.pdf" is more helpful than "document1.pdf."': '파일에 설명적인 이름을 붙이세요. Claude는 파일 이름을 사용하여 올바른 정보를 이해하고 검색하므로, "document1.pdf"보다 "Q4-2024-Brand-Guidelines.pdf"가 더 도움이 됩니다.',
        'How projects handle large knowledge bases': '프로젝트가 대규모 지식 기반을 처리하는 방법',
        'You might wonder what happens when you upload a lot of content. Projects automatically scale to handle large amounts through a feature called Retrieval Augmented Generation (RAG).': '많은 콘텐츠를 업로드하면 어떻게 되는지 궁금할 수 있습니다. 프로젝트는 RAG(검색 증강 생성)라는 기능을 통해 대량의 콘텐츠를 자동으로 확장 처리합니다.',
        'When your project knowledge approaches the context window limit, Claude seamlessly enables RAG mode. Instead of loading all project content into memory at once, Claude intelligently searches and retri': '프로젝트 지식이 컨텍스트 윈도우 제한에 도달하면, Claude는 원활하게 RAG 모드를 활성화합니다. 모든 프로젝트 콘텐츠를 한 번에 메모리에 로드하는 대신, Claude가 지능적으로 검색하고 검색합니다',
        "You'll see a visual indicator when your project is RAG-enabled, but the experience should feel the same—you can still upload documents, chat with Claude, and get context-aware responses.": '프로젝트에 RAG가 활성화되면 시각적 표시가 나타나지만, 경험은 동일합니다—여전히 문서를 업로드하고, Claude와 채팅하며, 맥락을 인식하는 응답을 받을 수 있습니다.',
        'Working within your project': '프로젝트 내에서 작업하기',
        'Once your project is set up, you can start chatting with Claude. Each conversation within the project automatically has access to your knowledge base and follows your project instructions.': '프로젝트가 설정되면 Claude와 채팅을 시작할 수 있습니다. 프로젝트 내 각 대화는 자동으로 지식 기반에 접근하고 프로젝트 지침을 따릅니다.',
        'Collaboration features': '협업 기능',
        'For users on Claude for Work (Team and Enterprise) plans, projects become even more powerful through collaboration features.': 'Claude for Work(Team 및 Enterprise) 플랜 사용자의 경우, 협업 기능을 통해 프로젝트가 더욱 강력해집니다.',
        'Permission levels': '권한 수준',
        'When sharing a project, you can choose from three permission levels:': '프로젝트를 공유할 때 세 가지 권한 수준 중 선택할 수 있습니다:',
        "Members can see project contents, access knowledge, and chat—but can't make changes. Think of this as read-only access with discussion rights.": '멤버는 프로젝트 내용을 보고, 지식에 접근하고, 채팅할 수 있지만 변경은 할 수 없습니다. 토론 권한이 있는 읽기 전용 접근으로 생각하세요.',
        'Members have full collaboration power. They can modify instructions, update knowledge, manage other members, and actively contribute to the project.': '멤버에게 전체 협업 권한이 있습니다. 지침을 수정하고, 지식을 업데이트하고, 다른 멤버를 관리하며, 프로젝트에 적극적으로 기여할 수 있습니다.',
        'Project creators control everything, including who sees the project. They can share with specific people or make projects visible to the entire organization.': '프로젝트 생성자는 프로젝트를 볼 수 있는 사람을 포함하여 모든 것을 제어합니다. 특정 사람과 공유하거나 전체 조직에 프로젝트를 공개할 수 있습니다.',
        'Sharing your project': '프로젝트 공유하기',
        'To share a project:': '프로젝트를 공유하려면:',
        'Open the project you want to share': '공유하려는 프로젝트를 엽니다',
        'Click the "Share project" button to the right of the project name': '프로젝트 이름 오른쪽의 "Share project" 버튼을 클릭합니다',
        'Add individual members using their name or email, or copy and paste a list of email addresses for bulk sharing (in this case, the project will show up in their "Shared with you" section)': '이름이나 이메일로 개별 멤버를 추가하거나, 일괄 공유를 위해 이메일 주소 목록을 복사하여 붙여넣기 합니다 (이 경우, 프로젝트가 "Shared with you" 섹션에 표시됩니다)',
        'Or, share with "Everyone at [your organization]" to make your project discoverable within the Team tab': '또는, "Everyone at [조직명]"과 공유하여 Team 탭 내에서 프로젝트를 검색 가능하게 합니다',
        'Team members will receive email notifications when you share a project with them, and they can find shared projects in their "Shared with me" tab.': '프로젝트를 공유하면 팀원에게 이메일 알림이 전송되며, "Shared with me" 탭에서 공유된 프로젝트를 찾을 수 있습니다.',
        'Example projects to inspire you': '영감을 줄 프로젝트 예시',
        'Not sure where to start? Here are some common project types across different functions:': '어디서 시작해야 할지 모르겠다면? 다양한 기능에 걸친 일반적인 프로젝트 유형을 소개합니다:',
        'Q4 product launch': 'Q4 제품 출시',
        ': Upload your product specs, competitive analysis, and messaging brainstorming notes. Claude will have this context top of mind for any inquiry or document draft.': ': 제품 사양, 경쟁 분석, 메시징 브레인스토밍 노트를 업로드하세요. Claude가 모든 문의나 문서 초안에 이 맥락을 최우선으로 반영합니다.',
        'Research support': '연구 지원',
        ': Centralize your competitive review, user research data, and customer feedback. Claude can help you synthesize sources, draft reports, and maintain consistency across recommendations.': ': 경쟁 리뷰, 사용자 연구 데이터, 고객 피드백을 중앙화하세요. Claude가 소스를 종합하고, 보고서 초안을 작성하며, 권장사항의 일관성을 유지하는 데 도움을 줍니다.',
        'Client account hub': '고객 계정 허브',
        ": Keep your client's brand guidelines, past deliverables, and communication history in one place. Set instructions so Claude matches their tone and references their specific context when creating prop": ': 고객의 브랜드 가이드라인, 과거 산출물, 커뮤니케이션 이력을 한 곳에 보관하세요. Claude가 제안서를 작성할 때 고객의 톤에 맞추고 특정 맥락을 참조하도록 지침을 설정하세요',
        'Event planning workspace': '이벤트 기획 워크스페이스',
        ": Upload venue contracts, speaker bios, and attendee data. Claude can help generate run-of-show documents, attendee communications, and post-event reports that stay consistent with your event's theme.": ': 장소 계약서, 연사 약력, 참석자 데이터를 업로드하세요. Claude가 행사 진행표, 참석자 커뮤니케이션, 이벤트 테마에 일관된 행사 후 보고서를 생성하는 데 도움을 줍니다.',
        'Job description generator': '채용 공고 생성기',
        ": Gather past job descriptions, team charters, and internal headcount request docs. Work with Claude to draft job descriptions that reflect your team's actual work and culture.": ': 과거 채용 공고, 팀 헌장, 내부 인력 요청 문서를 모으세요. Claude와 함께 팀의 실제 업무와 문화를 반영하는 채용 공고를 작성하세요.',
        'Best practices for projects': '프로젝트 모범 사례',
        'To get the most out of projects:': '프로젝트를 최대한 활용하려면:',
        'Start focused, then expand.': '집중해서 시작한 다음 확장하세요.',
        'Begin with a specific use case rather than trying to create one project for everything. You can always add more content as you go.': '모든 것을 위한 하나의 프로젝트를 만들려고 하지 말고 특정 사용 사례로 시작하세요. 진행하면서 항상 더 많은 콘텐츠를 추가할 수 있습니다.',
        'Keep your knowledge base current.': '지식 기반을 최신으로 유지하세요.',
        'Outdated documents can lead to outdated responses. Review and update your project knowledge periodically.': '오래된 문서는 오래된 응답으로 이어질 수 있습니다. 프로젝트 지식을 주기적으로 검토하고 업데이트하세요.',
        'Write clear instructions.': '명확한 지침을 작성하세요.',
        'Be specific about what you want. Vague instructions lead to inconsistent results.': '원하는 것을 구체적으로 명시하세요. 모호한 지침은 일관성 없는 결과를 초래합니다.',
        'Group related documents.': '관련 문서를 그룹화하세요.',
        'This helps Claude draw connections between different sources and provide more comprehensive responses.': '이렇게 하면 Claude가 다양한 소스 간의 연결을 파악하고 더 포괄적인 응답을 제공하는 데 도움이 됩니다.',
        'Reference documents by name.': '이름으로 문서를 참조하세요.',
        'When asking questions, you can mention specific documents to help Claude focus its search: "Based on our Q3 report, what were the top customer concerns?"': '질문할 때 특정 문서를 언급하여 Claude의 검색 범위를 좁힐 수 있습니다: "Q3 보고서를 기준으로, 주요 고객 관심사는 무엇이었나요?"',
        'What ongoing work could benefit from having a dedicated project with persistent context?': '지속적인 맥락이 있는 전용 프로젝트가 있으면 도움이 될 진행 중인 작업은 무엇인가요?',
        "What documents do you expect you'll be re-uploading or re-explaining to Claude on a regular basis?": '정기적으로 Claude에 다시 업로드하거나 재설명할 것으로 예상되는 문서는 무엇인가요?',
        "If you're on a team, are there projects that would benefit from shared knowledge and instructions?": '팀에 속해 있다면, 공유 지식과 지침의 혜택을 받을 프로젝트가 있나요?',
        "In the next lesson, we'll learn how to create mini-apps with Artifacts—actual outputs that Claude builds and you can share right away.": '다음 레슨에서는 아티팩트로 미니 앱을 만드는 방법을 배웁니다—Claude가 만들고 바로 공유할 수 있는 실제 결과물입니다.',
        'For more information on getting started with projects, visit the': '프로젝트 시작에 대한 자세한 정보는',
    },
    'Creating with artifacts': {
        'Creating with artifacts': '아티팩트로 만들기',
        'Explain what artifacts are and when Claude creates them': '아티팩트가 무엇이고 Claude가 언제 만드는지 설명할 수 있습니다',
        'Share artifacts with colleagues and publish them publicly': '동료와 아티팩트를 공유하고 공개적으로 게시할 수 있습니다',
        'Troubleshoot common artifact issues': '일반적인 아티팩트 문제를 해결할 수 있습니다',
        'What are artifacts?': '아티팩트란 무엇인가요?',
        'Artifacts are standalone, interactive outputs that Claude creates in a dedicated window alongside your conversation. Instead of getting a long block of code or text buried in the chat, you see your co': '아티팩트는 대화 옆의 전용 창에서 Claude가 만드는 독립적이고 대화형 출력물입니다. 채팅에 묻힌 긴 코드나 텍스트 블록 대신, 여러분의 콘텐츠를',
        'Claude automatically creates an artifact when content meets certain criteria:': 'Claude는 콘텐츠가 특정 기준을 충족하면 자동으로 아티팩트를 만듭니다:',
        "It's significant and self-contained, typically over 15 lines": '중요하고 자체 완결적이며, 일반적으로 15줄 이상',
        "It's something you're likely to want to edit, iterate on, or reuse": '편집, 반복 작업, 재사용하고 싶을 가능성이 높은 내용',
        'It represents complex content that stands on its own without needing the surrounding conversation': '주변 대화 없이도 독립적으로 존재할 수 있는 복잡한 콘텐츠',
        "It's content you'll want to reference or use later": '나중에 참조하거나 사용하고 싶은 콘텐츠',
        'Common artifact types': '일반적인 아티팩트 유형',
        'Claude can create different types of artifacts, each suited to different needs:': 'Claude는 각각 다른 필요에 맞는 다양한 유형의 아티팩트를 만들 수 있습니다:',
        'Documents (like markdown, plain text):': '문서 (마크다운, 일반 텍스트 등):',
        "Great for anything text-heavy that you'll want to export or continue editing—like meeting notes, reports, project plans, blog posts, and other written content.": '내보내거나 계속 편집하고 싶은 텍스트 중심의 모든 것에 적합합니다—회의록, 보고서, 프로젝트 계획, 블로그 게시물 등 다양한 글 콘텐츠.',
        'Working code in any programming language—Python, JavaScript, C++, and more. You can view the code, copy it, or download it to use in your own projects.': '모든 프로그래밍 언어의 실행 가능한 코드—Python, JavaScript, C++ 등. 코드를 보고, 복사하거나, 다운로드하여 자신의 프로젝트에 사용할 수 있습니다.',
        'Complete web pages with HTML, CSS, and JavaScript in a single file. Perfect for landing pages, forms, interactive demos, or quick prototypes.': 'HTML, CSS, JavaScript가 하나의 파일에 담긴 완전한 웹 페이지. 랜딩 페이지, 양식, 인터랙티브 데모, 빠른 프로토타입에 완벽합니다.',
        "Scalable vector graphics for logos, icons, illustrations, and other visual elements. These render directly in the artifact window so you can see exactly what you're getting.": '로고, 아이콘, 일러스트레이션 등 시각적 요소를 위한 확장 가능한 벡터 그래픽. 아티팩트 창에서 직접 렌더링되어 정확히 어떤 결과물인지 볼 수 있습니다.',
        'Mermaid diagrams:': 'Mermaid 다이어그램:',
        'Flowcharts, sequence diagrams, Gantt charts, org charts, and more. Describe the relationships you want to visualize, and Claude will create a diagram you can refine.': '플로차트, 시퀀스 다이어그램, 간트 차트, 조직도 등. 시각화하려는 관계를 설명하면 Claude가 개선할 수 있는 다이어그램을 만들어 줍니다.',
        'React components:': 'React 컴포넌트:',
        "Interactive UI elements with real functionality—calculators, dashboards, games, data visualizations. These aren't just mockups; they include actual logic and respond to user input.": '실제 기능이 있는 대화형 UI 요소—계산기, 대시보드, 게임, 데이터 시각화. 단순한 목업이 아니라 실제 로직이 포함되어 사용자 입력에 반응합니다.',
        'Creating your first artifact': '첫 아티팩트 만들기',
        'Creating an artifact is as simple as having a conversation. Just describe what you want, and Claude will determine whether to present it as an artifact.': '아티팩트를 만드는 것은 대화하는 것만큼 간단합니다. 원하는 것을 설명하면 Claude가 아티팩트로 표시할지 결정합니다.',
        'For example, you might say:': '예를 들어, 다음과 같이 말할 수 있습니다:',
        '"Create a flowchart showing our customer onboarding process"': '"고객 온보딩 프로세스를 보여주는 플로차트를 만들어 주세요"',
        '"Build an interactive dashboard that lets me input monthly expenses and see a breakdown"': '"월별 지출을 입력하고 분석을 볼 수 있는 인터랙티브 대시보드를 만들어 주세요"',
        '"Design a landing page for a productivity app with a hero section and feature list"': '"히어로 섹션과 기능 목록이 있는 생산성 앱 랜딩 페이지를 디자인해 주세요"',
        '"Write a project brief template I can reuse for new initiatives"': '"새로운 이니셔티브에 재사용할 수 있는 프로젝트 브리프 템플릿을 작성해 주세요"',
        '''If Claude doesn't automatically create an artifact when you expect one, you can explicitly ask: "Create this as an artifact" or "Show me this in an artifact."''': '''Claude가 예상할 때 아티팩트를 자동으로 만들지 않으면, 명시적으로 요청할 수 있습니다: "이것을 아티팩트로 만들어 주세요" 또는 "이것을 아티팩트로 보여주세요."''',
        'When Claude generates an artifact, it appears in a dedicated window to the right of your conversation. From here, you can:': 'Claude가 아티팩트를 생성하면 대화 오른쪽의 전용 창에 나타납니다. 여기서 다음을 할 수 있습니다:',
        'View different formats:': '다양한 형식 보기:',
        'Toggle between a preview (how it looks) and the underlying code': '미리보기(어떻게 보이는지)와 기본 코드 사이를 전환',
        'Click the copy icon to grab the content for use elsewhere': '복사 아이콘을 클릭하여 다른 곳에서 사용할 콘텐츠를 가져옵니다',
        'Save the artifact as a file to your computer': '아티팩트를 파일로 컴퓨터에 저장합니다',
        'See exactly what Claude generated under the hood': 'Claude가 내부적으로 생성한 내용을 정확히 확인합니다',
        'Sharing and publishing artifacts': '아티팩트 공유 및 게시',
        "Once you've created something useful, you have several options for sharing it.": '유용한 것을 만들었다면, 공유할 수 있는 여러 옵션이 있습니다.',
        'Copy or download:': '복사 또는 다운로드:',
        'For personal use or sharing via other channels, use the copy or download buttons in the lower right corner of the artifact window.': '개인 사용이나 다른 채널을 통한 공유의 경우, 아티팩트 창의 오른쪽 하단에 있는 복사 또는 다운로드 버튼을 사용하세요.',
        'Share within your organization (Claude for Work):': '조직 내 공유 (Claude for Work):',
        'Team and Enterprise users can share artifacts internally with colleagues. The shared artifact stays within your organization and requires team authentication to access.': 'Team 및 Enterprise 사용자는 동료와 아티팩트를 내부적으로 공유할 수 있습니다. 공유된 아티팩트는 조직 내에 유지되며 접근하려면 팀 인증이 필요합니다.',
        'Publish publicly:': '공개 게시:',
        'For free, Pro, and Max users, you can publish artifacts to make them accessible to anyone with the link. When you publish:': 'Free, Pro, Max 사용자는 아티팩트를 게시하여 링크가 있는 모든 사람이 접근할 수 있게 할 수 있습니다. 게시하면:',
        'Only the selected version becomes public (your chat remains private)': '선택한 버전만 공개됩니다 (채팅은 비공개로 유지)',
        'Anyone can view and interact with the artifact without a Claude account': 'Claude 계정 없이도 누구나 아티팩트를 보고 상호작용할 수 있습니다',
        'Others can "remix" your artifact—opening it in their own Claude conversation to modify and build upon it': '다른 사람들이 아티팩트를 "리믹스"할 수 있습니다—자신의 Claude 대화에서 열어 수정하고 발전시킬 수 있습니다',
        'To publish, click the "Share" or "Publish" button in the upper right corner of the artifact. You can unpublish at any time by returning to that artifact and removing public access.': '게시하려면 아티팩트 오른쪽 상단의 "Share" 또는 "Publish" 버튼을 클릭하세요. 언제든지 해당 아티팩트로 돌아가 공개 접근을 제거하여 게시를 취소할 수 있습니다.',
        'Tips for getting the most from artifacts': '아티팩트를 최대한 활용하기 위한 팁',
        'Be specific about what you want.': '원하는 것을 구체적으로 말하세요.',
        '''"Build a budget tracker" is good, but "Build a monthly budget tracker where I can input expenses by category, see a pie chart breakdown, and get a warning when I'm over budget" is better.''': '''"예산 추적기를 만들어줘"도 좋지만, "카테고리별로 지출을 입력하고, 원형 차트 분석을 보고, 예산 초과 시 경고를 받을 수 있는 월별 예산 추적기를 만들어줘"가 더 좋습니다.''',
        'Describe the end user.': '최종 사용자를 설명하세요.',
        'Telling Claude who will use the artifact helps it make appropriate design choices. "This flowchart is for new employees" leads to different results than "This flowchart is for the engineering team."': 'Claude에게 아티팩트를 사용할 사람을 알려주면 적절한 디자인 선택을 하는 데 도움이 됩니다. "이 플로차트는 신입 사원용입니다"는 "이 플로차트는 엔지니어링 팀용입니다"와 다른 결과를 만들어 냅니다.',
        'Iterate incrementally.': '점진적으로 반복하세요.',
        "Add one feature or make one change at a time. This makes it easier to identify what's working and catch issues early.": '한 번에 하나의 기능을 추가하거나 하나의 변경을 하세요. 이렇게 하면 무엇이 작동하는지 파악하고 문제를 조기에 발견하기 쉽습니다.',
        'Request artifacts when needed.': '필요할 때 아티팩트를 요청하세요.',
        'If you ask for something substantial and Claude responds in the chat instead of creating an artifact, just say "Please create that as an artifact."': '상당한 것을 요청했는데 Claude가 아티팩트를 만들지 않고 채팅에서 응답하면, "아티팩트로 만들어 주세요"라고 말하세요.',
        'What recurring work could benefit from having an interactive artifact you can reuse?': '재사용 가능한 대화형 아티팩트가 있으면 도움이 될 반복 작업은 무엇인가요?',
        'Are there processes in your work that would be clearer as a flowchart or diagram?': '업무에서 플로차트나 다이어그램으로 표현하면 더 명확해질 프로세스가 있나요?',
        'What prototype or tool would help you test an idea quickly?': '아이디어를 빠르게 테스트하는 데 도움이 될 프로토타입이나 도구는 무엇인가요?',
        "In the next lesson, you'll learn how to connect Claude to your existing tools and data sources, extending Claude's capabilities beyond conversation into your actual workflows.": '다음 레슨에서는 Claude를 기존 도구와 데이터 소스에 연결하여 대화를 넘어 실제 워크플로로 Claude의 기능을 확장하는 방법을 배웁니다.',
    },
}

def translate_file(filepath, translations):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    all_trans = {**COMMON, **translations}
    sorted_items = sorted(all_trans.items(), key=lambda x: len(x[0]), reverse=True)
    for eng, kor in sorted_items:
        if eng in content:
            content = content.replace(eng, kor)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    return content != original

for lesson_name, translations in FILES.items():
    matches = [f for f in os.listdir(FOLDER)
               if f.startswith(lesson_name) and f.endswith('.html') and f != 'index.html']
    if not matches:
        print(f'  [SKIP] No file found for: {lesson_name}')
        continue
    fpath = os.path.join(FOLDER, matches[0])
    changed = translate_file(fpath, translations)
    status = 'TRANSLATED' if changed else 'NO CHANGE'
    print(f'  [{status}] {matches[0]}')

print('\nPart 3 translation complete!')
