#!/usr/bin/env python3
"""Translate files 7-8: Working with skills + Connecting your tools."""
import os

FOLDER = os.path.dirname(os.path.abspath(__file__))

COMMON = {
    'Header Navigation': '헤더 내비게이션',
    'Anthropic Academy': 'Anthropic 아카데미',
    '>Courses<': '>강좌<',
    'Sign Out': '로그아웃',
    '>Previous<': '>이전<',
    '>Next<': '>다음<',
    '>Downloads<': '>다운로드<',
    'Learning objectives': '학습 목표',
    "What you'll learn": '학습 내용',
    'Lesson reflection': '레슨 되돌아보기',
    'Acknowledgments and license': '감사의 말 및 라이선스',
    'Share your feedback': '피드백을 공유해 주세요',
    "As you progress through the course, we'd love to hear from you about how you are using concepts from the course in your work and any feedback you may have. Share your feedback": "강좌를 진행하면서, 강좌의 개념을 업무에 어떻게 활용하고 계신지, 그리고 피드백이 있으시면 알려주세요. 피드백을 공유해 주세요",
    '>What is Claude?<': '>Claude란 무엇인가?<',
    '>Your first conversation with Claude<': '>Claude와의 첫 대화<',
    '>Getting better results<': '>더 나은 결과 얻기<',
    '>Claude desktop app: Chat, Cowork, Code<': '>Claude 데스크톱 앱: Chat, Cowork, Code<',
    '>Introduction to projects<': '>프로젝트 소개<',
    '>Creating with artifacts<': '>아티팩트로 만들기<',
    '>Working with skills<': '>스킬 활용하기<',
    '>Connecting your tools<': '>도구 연결하기<',
    '>Enterprise search<': '>Enterprise 검색<',
    '>Research mode for deep dives<': '>심층 분석을 위한 Research 모드<',
    '>Claude in action: use-cases by role<': '>Claude 활용 사례: 역할별 사용 사례<',
    '>Other ways to work with Claude<': '>Claude와 함께 일하는 다른 방법<',
    ">What's next?<": '>다음 단계는?<',
    '>Certificate of completion<': '>수료 인증서<',
    'title="What is Claude?"': 'title="Claude란 무엇인가?"',
    'title="Your first conversation with Claude"': 'title="Claude와의 첫 대화"',
    'title="Getting better results"': 'title="더 나은 결과 얻기"',
    'title="Claude desktop app: Chat, Cowork, Code"': 'title="Claude 데스크톱 앱: Chat, Cowork, Code"',
    'title="Introduction to projects"': 'title="프로젝트 소개"',
    'title="Creating with artifacts"': 'title="아티팩트로 만들기"',
    'title="Working with skills"': 'title="스킬 활용하기"',
    'title="Connecting your tools"': 'title="도구 연결하기"',
    'title="Enterprise search"': 'title="Enterprise 검색"',
    'title="Research mode for deep dives"': 'title="심층 분석을 위한 Research 모드"',
    'title="Claude in action: use-cases by role"': 'title="Claude 활용 사례: 역할별 사용 사례"',
    'title="Other ways to work with Claude"': 'title="Claude와 함께 일하는 다른 방법"',
    '''title="What's next?"''': 'title="다음 단계는?"',
    'title="Certificate of completion"': 'title="수료 인증서"',
    '- What is Claude?': '- Claude란 무엇인가?',
    '- Your first conversation with Claude': '- Claude와의 첫 대화',
    '- Getting better results': '- 더 나은 결과 얻기',
    '- Claude desktop app: Chat, Cowork, Code': '- Claude 데스크톱 앱: Chat, Cowork, Code',
    '- Introduction to projects': '- 프로젝트 소개',
    '- Creating with artifacts': '- 아티팩트로 만들기',
    '- Working with skills': '- 스킬 활용하기',
    '- Connecting your tools': '- 도구 연결하기',
    '- Enterprise search': '- Enterprise 검색',
    '- Research mode for deep dives': '- 심층 분석을 위한 Research 모드',
    '- Claude in action: use-cases by role': '- Claude 활용 사례: 역할별 사용 사례',
    '- Other ways to work with Claude': '- Claude와 함께 일하는 다른 방법',
    "- What's next?": '- 다음 단계는?',
    '- Certificate of completion': '- 수료 인증서',
    'By the end of this lesson, you will be able to:': '이 레슨을 마치면 다음을 할 수 있습니다:',
    'Anthropic Help Center': 'Anthropic 도움말 센터',
    'Before moving on, consider:': '다음으로 넘어가기 전에 고려해 보세요:',
}

FILES = {
    'Working with skills': {
        'Working with skills': '스킬 활용하기',
        'Explain what Skills are and how Claude uses them': '스킬이 무엇이고 Claude가 어떻게 사용하는지 설명할 수 있습니다',
        "Identify Anthropic's built-in Skills for document creation": '문서 생성을 위한 Anthropic의 내장 스킬을 파악할 수 있습니다',
        'Enable and manage Skills in your settings': '설정에서 스킬을 활성화하고 관리할 수 있습니다',
        'What are Skills?': '스킬이란 무엇인가요?',
        'Skills are folders of instructions, scripts, and resources that Claude loads dynamically to improve performance on specialized tasks. Think of them as expertise packages—they teach Claude how to complete specific tasks in a repeatable way.': '스킬은 Claude가 전문 작업의 성능을 향상시키기 위해 동적으로 로드하는 지침, 스크립트, 리소스의 폴더입니다. 전문성 패키지로 생각하세요—특정 작업을 반복 가능한 방식으로 완료하는 방법을 Claude에게 가르칩니다.',
        "You've already seen Skills at work if you've used Claude to create Excel spreadsheets, PowerPoint presentations, Word documents, or PDFs. Those file creation capabilities are powered by Skills running behind the scenes.": 'Claude를 사용하여 Excel 스프레드시트, PowerPoint 프레젠테이션, Word 문서 또는 PDF를 만들어 본 적이 있다면 이미 스킬이 작동하는 것을 보셨습니다. 이러한 파일 생성 기능은 이면에서 실행되는 스킬에 의해 구동됩니다.',
        "There are two categories of Skills you'll encounter:": '접하게 될 두 가지 범주의 스킬이 있습니다:',
        'Anthropic Skills': 'Anthropic 스킬',
        "are created and maintained by Anthropic. These include enhanced document creation capabilities for Excel, Word, PowerPoint, and PDF files. Anthropic Skills are available to all paid users and Claude invokes them automatically when relevant—you don't need to do anything special to use them.": '은 Anthropic에 의해 생성되고 유지됩니다. Excel, Word, PowerPoint, PDF 파일에 대한 향상된 문서 생성 기능이 포함됩니다. Anthropic 스킬은 모든 유료 사용자가 사용할 수 있으며, 관련될 때 Claude가 자동으로 호출합니다—특별히 할 필요가 없습니다.',
        "are ones you or your organization create for specialized workflows and domain-specific tasks. For example, you might create a skill that applies your company's brand guidelines to presentations, structures meeting notes in a specific format, or executes your organization's data analysis workflows.": "은 전문 워크플로와 도메인별 작업을 위해 여러분이나 조직이 만드는 것입니다. 예를 들어, 회사의 브랜드 가이드라인을 프레젠테이션에 적용하거나, 특정 형식으로 회의록을 구성하거나, 조직의 데이터 분석 워크플로를 실행하는 스킬을 만들 수 있습니다.",
        "Skills are currently available as a feature preview for users on Pro, Max, Team, and Enterprise plans. To use Skills, you'll need to have Code execution and file creation enabled, since Skills require Claude's secure sandboxed computing environment to function.": "스킬은 현재 Pro, Max, Team, Enterprise 플랜 사용자를 위한 기능 프리뷰로 제공됩니다. 스킬을 사용하려면 코드 실행 및 파일 생성이 활성화되어 있어야 하며, 이는 스킬이 Claude의 안전한 샌드박스 컴퓨팅 환경에서 작동하기 때문입니다.",
        "Here's how to enable Skills:": '스킬을 활성화하는 방법은 다음과 같습니다:',
        'Settings > Capabilities': '설정 > 기능',
        'Code execution and file creation': '코드 실행 및 파일 생성',
        'Toggle individual skills on or off as needed': '필요에 따라 개별 스킬을 켜거나 끕니다',
        'Enterprise plans': 'Enterprise 플랜',
        ', organization Owners must first enable both Code execution and Skills in Admin settings before individual members can access them.': '의 경우, 조직 소유자가 먼저 관리자 설정에서 코드 실행과 스킬을 모두 활성화해야 개별 멤버가 접근할 수 있습니다.',
        ', this feature preview is enabled by default at the organization level.': '에서는 이 기능 프리뷰가 조직 수준에서 기본적으로 활성화되어 있습니다.',
        "Once enabled, you'll see available Skills listed in your settings, including Anthropic's built-in Skills and any custom Skills you've uploaded.": '활성화되면, 설정에 Anthropic의 내장 스킬과 업로드한 맞춤 스킬을 포함한 사용 가능한 스킬 목록이 표시됩니다.',
        'Using Skills in practice': '실전에서 스킬 사용하기',
        "The beauty of Skills is that you typically don't need to think about them—Claude handles skill selection automatically based on your request. Here are some examples of prompts that would invoke Skills:": '스킬의 장점은 일반적으로 생각할 필요가 없다는 것입니다—Claude가 요청에 따라 자동으로 스킬을 선택합니다. 스킬을 호출하는 프롬프트 예시를 소개합니다:',
        '"Create an Excel spreadsheet tracking monthly expenses with formulas for totals"': '"총계 수식이 포함된 월별 지출 추적 Excel 스프레드시트를 만들어 주세요"',
        '"Turn this meeting notes document into a PowerPoint presentation"': '"이 회의록 문서를 PowerPoint 프레젠테이션으로 변환해 주세요"',
        '"Generate a PDF report summarizing this data"': '"이 데이터를 요약하는 PDF 보고서를 생성해 주세요"',
        '"Build a financial model in Excel with scenario analysis"': '"시나리오 분석이 포함된 Excel 재무 모델을 만들어 주세요"',
        "When Claude uses a Skill, you'll see it mentioned in Claude's chain of thought as it works. The output will be a downloadable file you can save to your computer or directly to Google Drive.": 'Claude가 스킬을 사용하면 작업 중 Claude의 사고 과정에서 언급되는 것을 볼 수 있습니다. 출력물은 컴퓨터나 Google Drive에 직접 저장할 수 있는 다운로드 가능한 파일입니다.',
        'This same capability means that Claude can work with': '이 동일한 기능은 Claude가',
        'your actual files': '실제 파일',
        '(within a contained environment) to make updates on your behalf . Upload slides, spreadsheets, contracts, (or': '(격리된 환경 내에서)을 대신 업데이트할 수 있음을 의미합니다. 슬라이드, 스프레드시트, 계약서를 업로드하세요 (또는',
        'any .xlsx, .pptx, .docx, or .pdf files) and watch as Claude creates slides, performs analyses, and adds suggested edits. When Claude is done, you can download these files or open them in Drive.': '모든 .xlsx, .pptx, .docx 또는 .pdf 파일을 업로드하면) Claude가 슬라이드를 만들고, 분석을 수행하며, 수정 제안을 추가하는 것을 볼 수 있습니다. Claude가 완료하면 파일을 다운로드하거나 Drive에서 열 수 있습니다.',
        "Note: To use these capabilities you'll need to give Claude access to external data sources. Simply toggle Allow limited network access on when prompted:": '참고: 이 기능을 사용하려면 Claude에게 외부 데이터 소스에 대한 접근 권한을 부여해야 합니다. 메시지가 표시되면 제한된 네트워크 접근 허용을 켜세요:',
        'Security considerations': '보안 고려사항',
        "Because Skills can include executable code, it's important to use them thoughtfully:": '스킬에는 실행 가능한 코드가 포함될 수 있으므로, 신중하게 사용하는 것이 중요합니다:',
        'Only install custom Skills from trusted sources': '신뢰할 수 있는 소스의 맞춤 스킬만 설치하세요',
        "Anthropic's built-in Skills are tested and maintained by Anthropic": 'Anthropic의 내장 스킬은 Anthropic이 테스트하고 유지합니다',
        'Custom Skills you upload are private to your individual account': '업로드한 맞춤 스킬은 개인 계정에만 비공개입니다',
        "If you're installing a custom Skill from an external source, review its contents before use to understand what it does.": '외부 소스의 맞춤 스킬을 설치하는 경우, 사용 전에 내용을 검토하여 무엇을 하는지 이해하세요.',
        'Creating custom skills': '맞춤 스킬 만들기',
        "While Anthropic's built-in Skills cover common document creation tasks, the real power of Skills comes from creating your own. Custom Skills let you teach Claude your specific workflows, brand guidelines, and ways of working—so Claude can apply that knowledge automatically whenever it's relevant.": 'Anthropic의 내장 스킬이 일반적인 문서 생성 작업을 다루지만, 스킬의 진정한 힘은 자신만의 스킬을 만드는 데 있습니다. 맞춤 스킬을 사용하면 Claude에게 특정 워크플로, 브랜드 가이드라인, 작업 방식을 가르칠 수 있어—관련될 때마다 Claude가 자동으로 해당 지식을 적용합니다.',
        "The easiest way to create a custom Skill is through conversation with Claude itself. You don't need to write code or manually create files—Claude handles the technical structure for you.": '맞춤 스킬을 만드는 가장 쉬운 방법은 Claude와의 대화를 통해서입니다. 코드를 작성하거나 수동으로 파일을 만들 필요가 없습니다—Claude가 기술적 구조를 대신 처리합니다.',
        "Here's how to create a Skill through conversation:": '대화를 통해 스킬을 만드는 방법은 다음과 같습니다:',
        'Start a new chat': '새 채팅을 시작하세요',
        'and tell Claude what you want to create. For example: "I want to create a skill for writing quarterly business reviews" or "I need a skill that applies our brand guidelines to presentations."': '그리고 만들고 싶은 것을 Claude에게 말하세요. 예: "분기별 비즈니스 리뷰를 작성하는 스킬을 만들고 싶습니다" 또는 "브랜드 가이드라인을 프레젠테이션에 적용하는 스킬이 필요합니다."',
        "Answer Claude's questions.": 'Claude의 질문에 답하세요.',
        "Claude will interview you about your workflow, asking things like: What should this skill do? What makes good output for this type of work? Can you give examples of when you'd use this skill?": "Claude가 워크플로에 대해 인터뷰합니다: 이 스킬은 무엇을 해야 하나요? 이 유형의 작업에서 좋은 결과물은 무엇인가요? 이 스킬을 사용할 예시를 들어줄 수 있나요?",
        'Upload reference materials': '참고 자료 업로드',
        "if you have them. Templates, style guides, brand assets, or examples of work you're proud of all help Claude understand exactly what you're looking for.": '가 있다면 업로드하세요. 템플릿, 스타일 가이드, 브랜드 자산, 자랑스러운 작업 예시 등이 Claude가 정확히 무엇을 찾는지 이해하는 데 도움이 됩니다.',
        'Download your skill.': '스킬을 다운로드하세요.',
        'When finished, Claude generates a downloadable ZIP file containing your properly structured skill.': '완료되면 Claude가 올바르게 구성된 스킬이 포함된 다운로드 가능한 ZIP 파일을 생성합니다.',
        'Upload to your settings.': '설정에 업로드하세요.',
        ', scroll to the Skills section, click "Upload skill," and select your ZIP file.': '에서 스킬 섹션으로 스크롤하고 "Upload skill"을 클릭한 다음 ZIP 파일을 선택하세요.',
        "Your custom Skill will appear in your Skills list alongside Anthropic's built-in Skills. From that point forward, Claude will automatically invoke it whenever you work on relevant tasks—no manual triggering needed.": '맞춤 스킬이 Anthropic의 내장 스킬과 함께 스킬 목록에 나타납니다. 그 이후부터 관련 작업을 수행할 때마다 Claude가 자동으로 호출합니다—수동 트리거가 필요 없습니다.',
        'Skills vs. Projects': '스킬 vs. 프로젝트',
        'You might be wondering—if both skills and projects can be used to give more context to Claude, when should I use each? Think of it this way:': '스킬과 프로젝트 모두 Claude에 더 많은 맥락을 제공하는 데 사용할 수 있는데, 각각 언제 사용해야 할까요? 이렇게 생각해 보세요:',
        'projects store knowledge, skills perform tasks': '프로젝트는 지식을 저장하고, 스킬은 작업을 수행합니다',
        'Projects are knowledge hubs. They hold the reference materials Claude needs to understand your work—project specs, meeting notes, research documents. When you upload files to a project, Claude draws on that information across every conversation within that project.': '프로젝트는 지식 허브입니다. Claude가 업무를 이해하는 데 필요한 참고 자료—프로젝트 사양, 회의록, 연구 문서를 보관합니다. 프로젝트에 파일을 업로드하면 Claude가 해당 프로젝트 내 모든 대화에서 그 정보를 활용합니다.',
        'Skills are procedural machines. They encode': '스킬은 절차적 기계입니다. 스킬은 Claude가 작업을 실행하는',
        'Claude should execute a task—the specific steps, order of operations, and methodology you want followed every time. Skills shine when you have repeatable workflows you want Claude to run consistently.': '방법—특정 단계, 작업 순서, 매번 따르길 원하는 방법론을 코드화합니다. 스킬은 Claude가 일관되게 실행하길 원하는 반복 가능한 워크플로가 있을 때 빛납니다.',
        'The two features complement each other. A skill can reference knowledge stored in a project—your "customer call prep" skill might pull from customer profiles uploaded to a project\'s knowledge base. The project provides the': '두 기능은 서로 보완합니다. 스킬은 프로젝트에 저장된 지식을 참조할 수 있습니다—"고객 통화 준비" 스킬이 프로젝트 지식 기반에 업로드된 고객 프로필에서 정보를 가져올 수 있습니다. 프로젝트는',
        '(information), the skill provides the': '(정보)를 제공하고, 스킬은',
        'Store knowledge Claude references': 'Claude가 참조하는 지식 저장',
        'Define processes Claude executes': 'Claude가 실행하는 프로세스 정의',
        'Long-term context, reference materials, team collaboration': '장기적 맥락, 참고 자료, 팀 협업',
        'Repeatable workflows, multi-step tasks, consistent methodology': '반복 가능한 워크플로, 다단계 작업, 일관된 방법론',
        'Customer hub, research buddy, feedback generator': '고객 허브, 연구 도우미, 피드백 생성기',
        'Brand guidelines, Blog drafting, PDF creation': '브랜드 가이드라인, 블로그 초안 작성, PDF 생성',
        'Knowledge available across all chats in the project': '프로젝트의 모든 채팅에서 지식 사용 가능',
        'Instructions applied when the skill is invoked': '스킬이 호출될 때 지침 적용',
        "What types of documents do you create regularly that could benefit from Claude's built-in Skills?": 'Claude의 내장 스킬의 혜택을 받을 수 있는 정기적으로 만드는 문서 유형은 무엇인가요?',
        'Are there repetitive workflows in your work that might be good candidates for custom Skills?': '맞춤 스킬의 좋은 후보가 될 수 있는 반복적인 워크플로가 업무에 있나요?',
        'How might Skills change the way you think about document creation and data analysis?': '스킬이 문서 생성과 데이터 분석에 대한 사고 방식을 어떻게 바꿀 수 있을까요?',
        "In the next set of lessons, you'll start to expand Claude's reach with connectors. These powerful tools make information gathering seamless, and can give Claude the ability to perform actions right inside the tools where your work is happening.": '다음 레슨 세트에서는 커넥터로 Claude의 범위를 확장합니다. 이 강력한 도구들은 정보 수집을 원활하게 하며, 업무가 이루어지는 도구 내에서 직접 작업을 수행할 수 있는 능력을 Claude에게 부여합니다.',
        'For more information on Skills, including how to create your own custom Skills, visit the': '맞춤 스킬 만들기를 포함한 스킬에 대한 자세한 정보는',
    },
    'Connecting your tools': {
        'Connecting your tools': '도구 연결하기',
        'Explain what connectors are and why they matter for your work with Claude': '커넥터가 무엇이고 Claude와의 작업에 왜 중요한지 설명할 수 있습니다',
        'Navigate the connectors directory and set up your first connection': '커넥터 디렉토리를 탐색하고 첫 번째 연결을 설정할 수 있습니다',
        'Use connected tools effectively in your conversations with Claude': 'Claude와의 대화에서 연결된 도구를 효과적으로 사용할 수 있습니다',
        'Connectors transform Claude from an assistant into an informed collaborator': '커넥터는 Claude를 어시스턴트에서 정보를 갖춘 협업자로 변환합니다',
        'by giving Claude access to the same tools, data, and context that you use every day. Instead of starting every conversation from scratch, Claude can work directly with your actual information.': '매일 사용하는 도구, 데이터, 맥락에 대한 접근권을 Claude에게 부여함으로써. 매번 처음부터 대화를 시작하는 대신, Claude가 실제 정보로 직접 작업할 수 있습니다.',
        'Connectors allow Claude to read information and perform actions on your behalf.': '커넥터를 사용하면 Claude가 정보를 읽고 대신 작업을 수행할 수 있습니다.',
        'Depending on the connector and permissions you grant, Claude can search your files, retrieve documents, analyze data, create new content, update records, and execute tasks across your connected applic': '커넥터와 부여한 권한에 따라, Claude는 파일을 검색하고, 문서를 검색하며, 데이터를 분석하고, 새 콘텐츠를 만들고, 레코드를 업데이트하며, 연결된 앱에서 작업을 실행할 수 있습니다',
        'The Model Context Protocol (MCP) powers connectors.': 'Model Context Protocol(MCP)이 커넥터를 구동합니다.',
        'Think of MCP like USB-C for AI—a universal standard that allows Claude to connect to many different applications through a single, consistent interface. This open standard means developers can build c': 'MCP를 AI의 USB-C로 생각하세요—Claude가 단일하고 일관된 인터페이스를 통해 다양한 애플리케이션에 연결할 수 있게 하는 범용 표준입니다. 이 오픈 표준은 개발자가',
        'There are two types of connectors: web connectors and desktop extensions.': '두 가지 유형의 커넥터가 있습니다: 웹 커넥터와 데스크톱 확장.',
        'Web connectors link Claude to cloud services like Google Drive, Notion, Slack, and Asana. Desktop extensions run locally on your computer through the Claude Desktop app, giving Claude access to local ': '웹 커넥터는 Claude를 Google Drive, Notion, Slack, Asana와 같은 클라우드 서비스에 연결합니다. 데스크톱 확장은 Claude Desktop 앱을 통해 컴퓨터에서 로컬로 실행되며, Claude에게 로컬',
        'Finding and connecting tools': '도구 찾기 및 연결하기',
        'Anthropic maintains a directory of recommended connectors at claude.ai/directory. The directory is organized into two tabs:': 'Anthropic은 claude.ai/directory에서 추천 커넥터 디렉토리를 유지합니다. 디렉토리는 두 개의 탭으로 구성됩니다:',
        ': Cloud services and applications (Gmail, Notion, Slack, Asana, Linear, Stripe, and many more)': ': 클라우드 서비스 및 애플리케이션 (Gmail, Notion, Slack, Asana, Linear, Stripe 등)',
        'Desktop extensions': '데스크톱 확장',
        ': Local tools that run on your computer through the Claude Desktop app': ': Claude Desktop 앱을 통해 컴퓨터에서 실행되는 로컬 도구',
        'To browse available connectors, you can also click the "Search and tools" button in the lower left of the chat window, then select "Add connectors."': '사용 가능한 커넥터를 탐색하려면, 채팅 창 왼쪽 하단의 "Search and tools" 버튼을 클릭한 다음 "Add connectors"를 선택할 수도 있습니다.',
        'Setting up a web connector': '웹 커넥터 설정하기',
        "Here's how to connect a cloud service:": '클라우드 서비스를 연결하는 방법은 다음과 같습니다:',
        'Find the connector': '커넥터 찾기',
        ': Navigate to claude.ai/directory or click "Search and tools" > "Add connectors" in any chat': ': claude.ai/directory로 이동하거나 채팅에서 "Search and tools" > "Add connectors"를 클릭하세요',
        ': Select the connector you want to add': ': 추가하려는 커넥터를 선택하세요',
        ": You'll be redirected to the service's login page. Sign in with your existing credentials": ': 서비스의 로그인 페이지로 리디렉션됩니다. 기존 자격 증명으로 로그인하세요',
        'Grant permissions': '권한 부여',
        ': Review the specific permissions Claude is requesting, then authorize access': ': Claude가 요청하는 특정 권한을 검토한 다음 접근을 승인하세요',
        'Test the connection': '연결 테스트',
        ': Return to Claude and try a simple request, like "Can you access my [tool name]?"': ': Claude로 돌아가 "내 [도구 이름]에 접근할 수 있나요?"와 같은 간단한 요청을 시도하세요',
        "Once connected, Claude can search, read, and in some cases take actions within that service—depending on the permissions you've granted.": '연결되면 부여한 권한에 따라 Claude가 해당 서비스 내에서 검색, 읽기, 그리고 일부 경우 작업을 수행할 수 있습니다.',
        'Desktop extensions require the Claude Desktop app rather than the web interface. These extensions let Claude interact with local applications, your file system, and native features on macOS or Windows': '데스크톱 확장은 웹 인터페이스가 아닌 Claude Desktop 앱이 필요합니다. 이 확장을 통해 Claude가 로컬 애플리케이션, 파일 시스템, macOS 또는 Windows의 네이티브 기능과 상호작용할 수 있습니다',
        'Some desktop extensions include:': '일부 데스크톱 확장에는 다음이 포함됩니다:',
        'Local file access for reading and organizing documents': '문서 읽기 및 정리를 위한 로컬 파일 접근',
        'Browser control for automated web tasks': '자동화된 웹 작업을 위한 브라우저 제어',
        'Native application integration (like Figma for design work)': '네이티브 애플리케이션 통합 (디자인 작업을 위한 Figma 등)',
        'To install a desktop extension:': '데스크톱 확장을 설치하려면:',
        'Download and install the': '다운로드하고 설치하세요',
        'Claude Desktop app': 'Claude Desktop 앱',
        'Open the app and navigate to Settings > Extensions': '앱을 열고 설정 > 확장으로 이동하세요',
        'Browse available extensions and click Install': '사용 가능한 확장을 탐색하고 설치를 클릭하세요',
        'Follow any additional setup steps specific to that extension': '해당 확장에 특정한 추가 설정 단계를 따르세요',
        'Using connectors in your work': '업무에서 커넥터 사용하기',
        "Once you've connected your tools, Claude considers them when responding to your requests.": '도구를 연결하면, Claude가 요청에 응답할 때 이를 고려합니다.',
        'Video: Using connectors': '영상: 커넥터 사용하기',
        'Here are some practical ways to use connected tools:': '연결된 도구를 활용하는 실용적인 방법을 소개합니다:',
        'Project management (Asana, Linear, Jira)': '프로젝트 관리 (Asana, Linear, Jira)',
        '"What are my highest priority tasks due this week?"': '"이번 주에 마감인 최우선 과제는 무엇인가요?"',
        '"Create a new task for reviewing the Q4 budget proposal"': '"Q4 예산 제안 검토를 위한 새 작업을 만들어 주세요"',
        '"Summarize the status of our product launch project"': '"제품 출시 프로젝트의 현황을 요약해 주세요"',
        'Communication (Slack, Gmail)': '커뮤니케이션 (Slack, Gmail)',
        '"Find the email thread where we discussed the vendor contract"': '"벤더 계약에 대해 논의한 이메일 스레드를 찾아 주세요"',
        '"Draft a reply to the latest message in the #marketing channel"': '"#marketing 채널의 최신 메시지에 대한 답장 초안을 작성해 주세요"',
        '''"What did the team decide about the timeline in yesterday's discussion?"''': '''"어제 논의에서 팀이 일정에 대해 무엇을 결정했나요?"''',
        'Documentation (Notion, Google Drive, Confluence)': '문서화 (Notion, Google Drive, Confluence)',
        '"Search our documentation for our brand voice guidelines"': '"브랜드 보이스 가이드라인에 대한 문서를 검색해 주세요"',
        '''"Summarize the meeting notes from last week's product review"''': '''"지난주 제품 리뷰 회의록을 요약해 주세요"''',
        '"What does our style guide say about using contractions?"': '"스타일 가이드에서 축약어 사용에 대해 뭐라고 하나요?"',
        'Business tools (Stripe, PayPal, Salesforce)': '비즈니스 도구 (Stripe, PayPal, Salesforce)',
        '"Show me revenue trends for the past quarter"': '"지난 분기 수익 트렌드를 보여주세요"',
        '''"What's the status of the Acme Corp opportunity?"''': '''"Acme Corp 기회의 현황은 어떤가요?"''',
        '"List recent transactions over $1,000"': '"1,000달러 이상의 최근 거래를 나열해 주세요"',
        'Security and permissions': '보안 및 권한',
        "When you connect Claude to external services, you're granting it access to read—and sometimes modify—data within those services. Here are some important considerations:": 'Claude를 외부 서비스에 연결하면, 해당 서비스 내의 데이터를 읽고—때로는 수정하는—접근 권한을 부여하는 것입니다. 다음은 중요한 고려사항입니다:',
        ": Permissions are specific to what the connector needs and you can toggle individual permissions on and off within each application's menu.": ": 권한은 커넥터가 필요로 하는 것에 한정되며, 각 애플리케이션의 메뉴에서 개별 권한을 켜고 끌 수 있습니다.",
        'Claude sees what you see': 'Claude는 여러분이 보는 것을 봅니다',
        ': Claude can only access data': ': Claude는 데이터에만 접근할 수 있습니다',
        "have access to. Connecting your work email doesn't give Claude access to your CEO's inbox—only your own.": "여러분이 접근 권한이 있는 데이터에만 접근할 수 있습니다. 업무 이메일을 연결해도 CEO의 받은편지함에 대한 접근 권한은 부여되지 않습니다—본인의 것만 가능합니다.",
        'Revocable at any time': '언제든지 취소 가능',
        ": You can disconnect a service through Claude's settings or through the third-party service's security settings.": ": Claude의 설정이나 타사 서비스의 보안 설정을 통해 서비스 연결을 해제할 수 있습니다.",
        'Which of your daily work tools would be most valuable to connect to Claude?': '일상 업무 도구 중 Claude에 연결하면 가장 유용한 것은 무엇인가요?',
        'What tasks currently require you to copy and paste information that connectors could handle automatically?': '현재 커넥터가 자동으로 처리할 수 있는 정보를 복사하여 붙여넣기해야 하는 작업은 무엇인가요?',
        'Are there workflows where combining data from multiple connected sources would save you significant time?': '여러 연결된 소스의 데이터를 결합하면 상당한 시간을 절약할 수 있는 워크플로가 있나요?',
        "In the next lesson, you'll learn about Enterprise Search—a specialized feature for Claude for Work users that connects Claude to your organization's knowledge sources with custom prompts optimized for": '다음 레슨에서는 Enterprise 검색에 대해 배웁니다—Claude for Work 사용자를 위한 전문 기능으로, 맞춤 프롬프트를 통해 Claude를 조직의 지식 소스에 연결합니다',
        'For more information on connectors and the Model Context Protocol, visit the': '커넥터와 Model Context Protocol에 대한 자세한 정보는',
        'or explore the connector directory at claude.ai/directory.': '를 방문하거나 claude.ai/directory에서 커넥터 디렉토리를 탐색하세요.',
    },
}

def translate_file(filepath, translations):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    all_trans = {**COMMON, **translations}
    sorted_items = sorted(all_trans.items(), key=lambda x: len(x[0]), reverse=True)
    for eng, kor in sorted_items:
        if eng in content:
            content = content.replace(eng, kor)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    return content != original

for lesson_name, translations in FILES.items():
    matches = [f for f in os.listdir(FOLDER)
               if f.startswith(lesson_name) and f.endswith('.html') and f != 'index.html']
    if not matches:
        print(f'  [SKIP] No file found for: {lesson_name}')
        continue
    fpath = os.path.join(FOLDER, matches[0])
    changed = translate_file(fpath, translations)
    status = 'TRANSLATED' if changed else 'NO CHANGE'
    print(f'  [{status}] {matches[0]}')

print('\nPart 4 translation complete!')
