#!/usr/bin/env python3
"""Translate files 1-2: What is Claude + Your first conversation with Claude."""
import os

FOLDER = os.path.dirname(os.path.abspath(__file__))

COMMON = {
    'Header Navigation': '헤더 내비게이션',
    'Anthropic Academy': 'Anthropic 아카데미',
    '>Courses<': '>강좌<',
    'Sign Out': '로그아웃',
    '>Previous<': '>이전<',
    '>Next<': '>다음<',
    '>Downloads<': '>다운로드<',
    'Learning objectives': '학습 목표',
    "What you'll learn": '학습 내용',
    'Lesson reflection': '레슨 되돌아보기',
    'Acknowledgments and license': '감사의 말 및 라이선스',
    'Copyright 2025 Anthropic. All rights reserved.': 'Copyright 2025 Anthropic. All rights reserved.',
    'Share your feedback': '피드백을 공유해 주세요',
    "As you progress through the course, we'd love to hear from you about how you are using concepts from the course in your work and any feedback you may have. Share your feedback": "강좌를 진행하면서, 강좌의 개념을 업무에 어떻게 활용하고 계신지, 그리고 피드백이 있으시면 알려주세요. 피드백을 공유해 주세요",
    "As you progress through the course, we'd love to hear how you're using the Claude desktop app in your work, plus any feedback you may have. Share your feedback": "강좌를 진행하면서, Claude 데스크톱 앱을 업무에 어떻게 활용하고 계신지, 그리고 피드백이 있으시면 알려주세요. 피드백을 공유해 주세요",
    'Estimated time: 6 minutes': '예상 소요 시간: 6분',
    'Estimated time: 5 minutes': '예상 소요 시간: 5분',
    '>What is Claude?<': '>Claude란 무엇인가?<',
    '>Your first conversation with Claude<': '>Claude와의 첫 대화<',
    '>Getting better results<': '>더 나은 결과 얻기<',
    '>Claude desktop app: Chat, Cowork, Code<': '>Claude 데스크톱 앱: Chat, Cowork, Code<',
    '>Introduction to projects<': '>프로젝트 소개<',
    '>Creating with artifacts<': '>아티팩트로 만들기<',
    '>Working with skills<': '>스킬 활용하기<',
    '>Connecting your tools<': '>도구 연결하기<',
    '>Enterprise search<': '>Enterprise 검색<',
    '>Research mode for deep dives<': '>심층 분석을 위한 Research 모드<',
    '>Claude in action: use-cases by role<': '>Claude 활용 사례: 역할별 사용 사례<',
    '>Other ways to work with Claude<': '>Claude와 함께 일하는 다른 방법<',
    ">What's next?<": '>다음 단계는?<',
    '>Certificate of completion<': '>수료 인증서<',
    'title="What is Claude?"': 'title="Claude란 무엇인가?"',
    'title="Your first conversation with Claude"': 'title="Claude와의 첫 대화"',
    'title="Getting better results"': 'title="더 나은 결과 얻기"',
    'title="Claude desktop app: Chat, Cowork, Code"': 'title="Claude 데스크톱 앱: Chat, Cowork, Code"',
    'title="Introduction to projects"': 'title="프로젝트 소개"',
    'title="Creating with artifacts"': 'title="아티팩트로 만들기"',
    'title="Working with skills"': 'title="스킬 활용하기"',
    'title="Connecting your tools"': 'title="도구 연결하기"',
    'title="Enterprise search"': 'title="Enterprise 검색"',
    'title="Research mode for deep dives"': 'title="심층 분석을 위한 Research 모드"',
    'title="Claude in action: use-cases by role"': 'title="Claude 활용 사례: 역할별 사용 사례"',
    'title="Other ways to work with Claude"': 'title="Claude와 함께 일하는 다른 방법"',
    '''title="What's next?"''': 'title="다음 단계는?"',
    'title="Certificate of completion"': 'title="수료 인증서"',
    '- What is Claude?': '- Claude란 무엇인가?',
    '- Your first conversation with Claude': '- Claude와의 첫 대화',
    '- Getting better results': '- 더 나은 결과 얻기',
    '- Claude desktop app: Chat, Cowork, Code': '- Claude 데스크톱 앱: Chat, Cowork, Code',
    '- Introduction to projects': '- 프로젝트 소개',
    '- Creating with artifacts': '- 아티팩트로 만들기',
    '- Working with skills': '- 스킬 활용하기',
    '- Connecting your tools': '- 도구 연결하기',
    '- Enterprise search': '- Enterprise 검색',
    '- Research mode for deep dives': '- 심층 분석을 위한 Research 모드',
    '- Claude in action: use-cases by role': '- Claude 활용 사례: 역할별 사용 사례',
    '- Other ways to work with Claude': '- Claude와 함께 일하는 다른 방법',
    "- What's next?": '- 다음 단계는?',
    '- Certificate of completion': '- 수료 인증서',
    'By the end of this lesson, you will be able to:': '이 레슨을 마치면 다음을 할 수 있습니다:',
    "By the end of this lesson you'll be able to:": '이 레슨을 마치면 다음을 할 수 있습니다:',
    'Anthropic Help Center': 'Anthropic 도움말 센터',
}

FILES = {
    'What is Claude': {
        "By the end of this lesson you'll be able to:": '이 레슨을 마치면 다음을 할 수 있습니다:',
        'Explain what Claude is and the principles that guide its design': 'Claude가 무엇이며 설계를 이끄는 원칙을 설명할 수 있습니다',
        "Describe Claude's core capabilities and how it differs from a simple chatbot": 'Claude의 핵심 기능과 단순한 챗봇과의 차이점을 설명할 수 있습니다',
        'Identify the different ways to access Claude (web, desktop, and mobile)': 'Claude에 접근하는 다양한 방법(웹, 데스크톱, 모바일)을 파악할 수 있습니다',
        'Video: Turning Claude into your thinking partner': '영상: Claude를 사고 파트너로 만들기',
        "This video introduces Claude as more than a chatbot—it's an AI assistant designed to be your thinking partner. You'll learn what makes Claude different from other AI tools and see how it can help with a wide variety of work tasks.": '이 영상에서는 Claude를 단순한 챗봇 이상의 존재, 즉 사고 파트너로 설계된 AI 어시스턴트로 소개합니다. Claude가 다른 AI 도구와 어떻게 다른지, 그리고 다양한 업무에 어떻게 도움을 줄 수 있는지 알아봅니다.',
        'Claude is built to be helpful, harmless, and honest': 'Claude는 유용하고, 무해하며, 정직하도록 설계되었습니다',
        ': At a high level, Claude is guided by principles that help it avoid toxic or discriminatory outputs, avoid helping humans engage in illegal or unethical activities, and broadly behave as a helpful, honest, and harmless AI system. This approach, called Constitutional AI, means Claude is trained to a': ': 상위 수준에서 Claude는 유해하거나 차별적인 출력을 피하고, 불법적이거나 비윤리적인 활동을 돕는 것을 피하며, 전반적으로 유용하고 정직하며 무해한 AI 시스템으로 작동하도록 안내하는 원칙을 따릅니다. Constitutional AI라고 불리는 이 접근 방식은 Claude가 다음과 같이 훈련됨을 의미합니다',
        'Claude is more than a chatbot': 'Claude는 단순한 챗봇 이상입니다',
        ': Claude is capable of a wide variety of conversational and text processing tasks while maintaining a high degree of reliability and predictability, including summarization, search, creative and collaborative writing, Q&A, coding, and more. Think of Claude as a thought partner who can help you tackl': ': Claude는 요약, 검색, 창의적이고 협업적인 글쓰기, Q&A, 코딩 등 다양한 대화 및 텍스트 처리 작업을 높은 수준의 신뢰성과 예측 가능성을 유지하면서 수행할 수 있습니다. Claude를 복잡한 문제를 해결하는 데 도움을 줄 수 있는 사고 파트너로 생각하세요',
        'Claude is designed to be steerable and collaborative': 'Claude는 조종 가능하고 협업적으로 설계되었습니다',
        ': Claude can take direction on personality, tone, and behavior, and early customers report that Claude is much less likely to produce harmful outputs, easier to converse with, and more steerable—so you can get your desired output with less effort.': ': Claude는 성격, 톤, 행동에 대한 지시를 받을 수 있으며, 초기 고객들은 Claude가 유해한 출력을 생성할 가능성이 훨씬 낮고, 대화하기 쉬우며, 더 잘 조종할 수 있다고 보고합니다—따라서 더 적은 노력으로 원하는 결과를 얻을 수 있습니다.',
        'You can access Claude wherever you work': '어디서나 Claude에 접근할 수 있습니다',
        ": Claude apps are available to all plan types—Free, Pro, Max, Team, and Enterprise. Your conversations, projects, memory, and preferences sync across all devices when you're signed in. Whether you're at your desk or on the go, Claude is available through web, desktop, and mobile apps.": ': Claude 앱은 Free, Pro, Max, Team, Enterprise 등 모든 플랜 유형에서 사용할 수 있습니다. 로그인하면 대화, 프로젝트, 메모리, 환경설정이 모든 기기에서 동기화됩니다. 책상에 앉아 있든 이동 중이든, Claude는 웹, 데스크톱, 모바일 앱을 통해 이용할 수 있습니다.',
        "Understanding Claude's capabilities": 'Claude의 기능 이해하기',
        'Claude can help with a wide range of tasks that go far beyond simple question-and-answer interactions to assistant-like partnership that can both automate': 'Claude는 단순한 질의응답을 넘어 업무를 자동화하고',
        "augment your work. Here's a few things Claude excels at:": '증강할 수 있는 어시스턴트형 파트너십까지 다양한 작업을 도울 수 있습니다. Claude가 뛰어난 몇 가지 영역을 소개합니다:',
        'Writing and content creation': '글쓰기 및 콘텐츠 제작',
        ': Claude can collaborate with you on social media posts, professional emails, and complex reports. Because Claude is trained to take direction on personality and tone, you can iterate together on structure and clarity until your voice comes through clearly.': ': Claude는 소셜 미디어 게시물, 전문 이메일, 복잡한 보고서 작업에서 협업할 수 있습니다. Claude는 성격과 톤에 대한 지시를 받도록 훈련되었기 때문에, 여러분의 목소리가 명확하게 전달될 때까지 구조와 명확성을 함께 다듬을 수 있습니다.',
        'Research and analysis': '연구 및 분석',
        ": Claude helps you explore research angles, compile findings, and analyze data to surface meaningful insights. You can upload documents and Claude will help you make sense of complex information—this is enabled by Claude's large context window, which can ingest 200K+ tokens (about 500 pages of text ": ': Claude는 연구 방향을 탐색하고, 발견 사항을 정리하며, 데이터를 분석하여 의미 있는 인사이트를 도출하는 데 도움을 줍니다. 문서를 업로드하면 Claude가 복잡한 정보를 이해하는 데 도움을 줍니다—이는 200K+ 토큰(약 500페이지 분량의 텍스트)을 처리할 수 있는 Claude의 대규모 컨텍스트 윈도우 덕분입니다 ',
        'Coding assistance': '코딩 지원',
        ': Claude Opus 4.5 is our most powerful model yet and the best coding model in the world. This strong performance on real-world coding tasks means Claude can help you write, debug, and explain code across multiple programming languages.': ': Claude Opus 4.5는 현재까지 가장 강력한 모델이자 세계 최고의 코딩 모델입니다. 실제 코딩 작업에서의 뛰어난 성능으로, Claude는 여러 프로그래밍 언어에 걸쳐 코드를 작성, 디버깅, 설명하는 데 도움을 줄 수 있습니다.',
        'Problem-solving and reasoning': '문제 해결 및 추론',
        ': Claude handles complex cognitive tasks, mathematical problems, strategic analysis, and research. Claude Opus 4.5 and Sonnet 4.5 are hybrid models offering two modes: near-instant responses and extended thinking for deeper reasoning. Extended thinking allows Claude to work through problems step-by-': ': Claude는 복잡한 인지 작업, 수학 문제, 전략적 분석, 연구를 처리합니다. Claude Opus 4.5와 Sonnet 4.5는 즉각적인 응답과 더 깊은 추론을 위한 확장된 사고라는 두 가지 모드를 제공하는 하이브리드 모델입니다. 확장된 사고를 통해 Claude는 문제를 단계별로 풀어나갈 수 있습니다',
        'Learning new things': '새로운 것 배우기',
        ": Whether you're learning a new skill, exploring unfamiliar domains, or working through complex challenges, Claude can adapt to your learning style and pace. Learning mode is a new Claude experience that guides your reasoning process rather than providing answers, helping develop critical thinking s": ': 새로운 기술을 배우거나, 익숙하지 않은 분야를 탐구하거나, 복잡한 과제를 해결할 때, Claude는 여러분의 학습 스타일과 속도에 맞출 수 있습니다. 학습 모드는 답을 제공하는 대신 추론 과정을 안내하여 비판적 사고 능력을 개발하는 데 도움을 주는 새로운 Claude 경험입니다',
        'Get inspired on ways to use Claude in your specific function by exploring our': '다음을 탐색하여 특정 업무에서 Claude를 활용하는 방법에 대한 영감을 얻으세요:',
        'use-case gallery': '사용 사례 갤러리',
        'Ways to access Claude': 'Claude에 접근하는 방법',
        "Claude is the intelligence—the AI assistant you're learning to work with throughout this course. That same intelligence is available across multiple interfaces, each suited to different types of tasks.": 'Claude는 지능입니다—이 강좌를 통해 함께 일하는 법을 배우고 있는 AI 어시스턴트입니다. 동일한 지능이 다양한 인터페이스를 통해 제공되며, 각각 다른 유형의 작업에 적합합니다.',
        '(and the associated mobile and desktop apps) are the primary way most people interact with Claude. Here, you can ask questions, brainstorm ideas, create and edit documents, and a lot more. Claude.ai is ideal for conversations, writing assistance, research, analysis, and creating files. This is our f': '(및 관련 모바일, 데스크톱 앱)는 대부분의 사람들이 Claude와 상호작용하는 주요 방법입니다. 여기서 질문하고, 아이디어를 브레인스토밍하고, 문서를 만들고 편집하는 등 다양한 작업을 할 수 있습니다. Claude.ai는 대화, 글쓰기 지원, 연구, 분석, 파일 생성에 이상적입니다. 이것이 저희의 주력',
        'is an agentic coding tool that is designed for developers but can be used for all kinds of file manipulation on your desktop. Claude Code can directly edit files, run commands, and create commits.': '은 개발자를 위해 설계되었지만 데스크톱에서 모든 종류의 파일 조작에 사용할 수 있는 에이전트형 코딩 도구입니다. Claude Code는 파일을 직접 편집하고, 명령을 실행하며, 커밋을 생성할 수 있습니다.',
        'Claude and Slack': 'Claude와 Slack',
        "brings Claude directly into your team's communication tool. You can chat with Claude in the AI assistant header from any channel or conversation, or by mentioning @Claude in threads. When you connect Slack to Claude, Claude searches your workspace's channels, direct messages, and shared files to fin": '은 Claude를 팀의 커뮤니케이션 도구에 직접 통합합니다. 모든 채널이나 대화에서 AI 어시스턴트 헤더를 통해 Claude와 채팅하거나, 스레드에서 @Claude를 멘션할 수 있습니다. Slack을 Claude에 연결하면, Claude가 워크스페이스의 채널, 다이렉트 메시지, 공유 파일을 검색하여',
        'Claude for Excel': 'Claude for Excel',
        'lets you work directly with Claude in a sidebar in Microsoft Excel, where Claude can read, analyze, modify, and create new Excel workbooks. Claude for Excel is best for model analysis, assumption updates, error debugging, template population, formula explanations, and multi-tab navigation.': '을 사용하면 Microsoft Excel의 사이드바에서 Claude와 직접 작업할 수 있으며, Claude가 Excel 통합 문서를 읽고, 분석하고, 수정하고, 새로 만들 수 있습니다. Claude for Excel은 모델 분석, 가정 업데이트, 오류 디버깅, 템플릿 채우기, 수식 설명, 다중 탭 탐색에 가장 적합합니다.',
        'This course will focus primarily on': '이 강좌는 주로',
        ', but you can also check out': '에 초점을 맞추지만,',
        'Claude Code in Action': 'Claude Code 실전 활용',
        'for more information on using Claude in development workflows.': '에서 개발 워크플로에서 Claude를 사용하는 방법에 대한 자세한 정보를 확인할 수도 있습니다.',
        'What tasks in your current work might benefit from having Claude as a thinking partner? Take a look at your calendar (or better yet, ask Claude to) and identify a few tasks you might want to use Claude to support.': '현재 업무에서 Claude를 사고 파트너로 활용하면 도움이 될 작업은 무엇인가요? 캘린더를 살펴보고(더 좋은 방법은 Claude에게 요청하는 것입니다) Claude의 도움을 받고 싶은 몇 가지 작업을 파악해 보세요.',
        "In the next lesson, you'll learn how to navigate the Claude interface, start your first conversation, and understand the basics of how Claude responds to your messages.": '다음 레슨에서는 Claude 인터페이스를 탐색하고, 첫 대화를 시작하며, Claude가 메시지에 응답하는 기본 방식을 이해하는 방법을 배웁니다.',
        'Your first conversation with Claude': 'Claude와의 첫 대화',
    },
    'Your first conversation with Claude': {
        'Your first conversation with Claude': 'Claude와의 첫 대화',
        'Start a new conversation with Claude and navigate the interface': '새로운 대화를 시작하고 인터페이스를 탐색할 수 있습니다',
        'Write effective prompts using clear, specific language': '명확하고 구체적인 언어를 사용하여 효과적인 프롬프트를 작성할 수 있습니다',
        'Upload files and images to provide Claude with additional context': '파일과 이미지를 업로드하여 Claude에 추가 컨텍스트를 제공할 수 있습니다',
        "Use follow-up messages to iterate and refine Claude's responses": '후속 메시지를 사용하여 Claude의 응답을 반복 개선할 수 있습니다',
        'Video: Getting started with Claude.ai': '영상: Claude.ai 시작하기',
        'Claude is a powerful, intelligent collaborator that amplifies your capabilities across all of your work. Claude brings AI intelligence, but you bring the context and expertise that makes the work meaningful.': 'Claude는 모든 업무에서 여러분의 역량을 증폭시키는 강력하고 지능적인 협업자입니다. Claude는 AI 지능을 가져오지만, 업무를 의미있게 만드는 컨텍스트와 전문성은 여러분이 제공합니다.',
        "The best approach when speaking to Claude is like you would a coworker—naturally, concisely, and conversationally.": 'Claude와 대화하는 가장 좋은 접근 방식은 동료에게 말하듯이—자연스럽고, 간결하며, 대화하듯이 하는 것입니다.',
        "Before your next conversation with Claude, consider:": 'Claude와의 다음 대화 전에 다음을 고려하세요:',
        'setting the stage': '무대 설정하기',
        '(your role, objectives, and context),': '(역할, 목표, 맥락),',
        'defining the task': '과제 정의하기',
        '(what action you want Claude to take), and': '(Claude에게 수행하길 원하는 작업), 그리고',
        'specifying rules': '규칙 지정하기',
        '(style, tone, and examples).': '(스타일, 톤, 예시).',
        'When you upload relevant documents or background information into a chat, Claude considers that content in its response—think of it as a shortcut so Claude can understand what your needs are.': '관련 문서나 배경 정보를 채팅에 업로드하면, Claude는 응답 시 해당 내용을 고려합니다—Claude가 여러분의 요구를 이해할 수 있는 지름길로 생각하세요.',
        'The real power of Claude comes with continued and frequent communication, not just one-off prompts.': 'Claude의 진정한 힘은 일회성 프롬프트가 아닌, 지속적이고 빈번한 소통에서 나옵니다.',
        'Starting your first conversation': '첫 대화 시작하기',
        "When you open Claude.ai, you'll see a clean interface with a text input area at the bottom of the screen.": 'Claude.ai를 열면 화면 하단에 텍스트 입력 영역이 있는 깔끔한 인터페이스가 나타납니다.',
        'Your prompts can range from simple questions (like brainstorming code names for a new feature) to complex requests to co-create files.': '프롬프트는 간단한 질문(예: 새 기능의 코드명 브레인스토밍)부터 파일을 함께 만드는 복잡한 요청까지 다양할 수 있습니다.',
        'Writing effective prompts': '효과적인 프롬프트 작성하기',
        "All interactions with Claude begin with a prompt, and these prompts, combined with other context, impact Claude's response. The best approach when speaking to Claude is like you would a coworker—naturally, concisely, and conversationally.": 'Claude와의 모든 상호작용은 프롬프트로 시작되며, 이 프롬프트는 다른 컨텍스트와 결합하여 Claude의 응답에 영향을 미칩니다. Claude와 대화하는 가장 좋은 접근 방식은 동료에게 말하듯이—자연스럽고, 간결하며, 대화하듯이 하는 것입니다.',
        'But you may ask, what is a good prompt? Before your next conversation with Claude, consider a few things:': '하지만 좋은 프롬프트란 무엇인지 궁금할 수 있습니다. Claude와의 다음 대화 전에 몇 가지를 고려해 보세요:',
        'Setting the stage:': '무대 설정하기:',
        'What is your role and what are your objectives? Is there context about your work that Claude should know about?': '여러분의 역할과 목표는 무엇인가요? Claude가 알아야 할 업무 관련 맥락이 있나요?',
        'Defining the task:': '과제 정의하기:',
        'What action do you want Claude to take? Do you want Claude to write, analyze, build, or something else?': 'Claude에게 어떤 작업을 수행하길 원하나요? 글쓰기, 분석, 구축, 아니면 다른 작업을 원하나요?',
        'Specifying rules:': '규칙 지정하기:',
        "What's the style or tone you want Claude to use? Are there examples that you can attach to show Claude what you're looking for?": 'Claude에게 사용하길 원하는 스타일이나 톤은 무엇인가요? Claude에게 원하는 바를 보여줄 수 있는 예시가 있나요?',
        'Putting it together': '종합하기',
        "Here's an example prompt that uses all three elements:": '세 가지 요소를 모두 사용한 프롬프트 예시입니다:',
        '''"I'm the marketing lead at an indie streaming startup, and we're preparing an investor pitch deck. Can you research the current state of the independent film streaming market and identify key trends, competitor positioning, and growth opportunities? Use current web research with citations and struct''': '''"저는 인디 스트리밍 스타트업의 마케팅 리드이며, 투자자 피치 덱을 준비하고 있습니다. 독립 영화 스트리밍 시장의 현황을 조사하고 주요 트렌드, 경쟁사 포지셔닝, 성장 기회를 파악해 주시겠습니까? 인용이 포함된 최신 웹 조사를 사용하고 전문적인 보고서로 구조화해 주세요''',
        'Setting the stage': '무대 설정하기',
        ": We tell Claude this is for an investor pitch deck for a new indie streaming app—that's the context and objective.": ': 투자자 피치 덱을 위한 것이라고 Claude에게 알려줍니다—이것이 맥락과 목표입니다.',
        'Defining the task': '과제 정의하기',
        ': We provide the specific action (research the market) with relevant details (trends, competitors, opportunities).': ': 관련 세부사항(트렌드, 경쟁사, 기회)과 함께 구체적인 작업(시장 조사)을 제공합니다.',
        'Specifying rules': '규칙 지정하기',
        ": We ask for current web research with citations, structured as a professional report—telling Claude exactly what style and format we need.": ': 인용이 포함된 최신 웹 조사를 요청하고 전문적인 보고서로 구조화해달라고 합니다—Claude에게 필요한 스타일과 형식을 정확히 알려줍니다.',
        'Want to go deeper?': '더 깊이 알아보고 싶으신가요?',
        'This prompt framework is adapted from the': '이 프롬프트 프레임워크는',
        '4D Framework for AI Fluency': 'AI 활용 능력을 위한 4D 프레임워크',
        ', developed through research collaboration between Professor Rick Dakan (Ringling College of Art and Design) and Professor Joseph Feller (University College Cork). The framework identifies four core competencies—Delegation, Description, Discernment, and Diligence—that enable effective collaboration ': '에서 적용되었으며, Rick Dakan 교수(Ringling College of Art and Design)와 Joseph Feller 교수(University College Cork) 간의 연구 협력을 통해 개발되었습니다. 이 프레임워크는 효과적인 협업을 가능하게 하는 네 가지 핵심 역량—위임(Delegation), 기술(Description), 판단(Discernment), 성실(Diligence)—을 식별합니다 ',
        'Take our free AI Fluency course': '무료 AI 활용 능력 강좌를 수강하세요',
        'to learn how all four competencies work together to enable efficient, effective, ethical, and safe AI use.': '네 가지 역량이 효율적이고, 효과적이며, 윤리적이고, 안전한 AI 사용을 위해 어떻게 함께 작동하는지 알아보세요.',
        'Uploads, connectors, and custom preferences offer ways to give Claude even more context about your work.': '업로드, 커넥터, 맞춤 환경설정은 Claude에게 업무에 대한 더 많은 컨텍스트를 제공하는 방법입니다.',
        'Claude can analyze both text and visual elements (like images, charts, and graphics) in PDFs and other documents. Supported file types include PDF, DOCX, CSV, TXT, and common image formats like PNG and JPEG.': 'Claude는 PDF 및 기타 문서에서 텍스트와 시각적 요소(이미지, 차트, 그래픽 등)를 모두 분석할 수 있습니다. 지원되는 파일 유형에는 PDF, DOCX, CSV, TXT, 그리고 PNG, JPEG와 같은 일반적인 이미지 형식이 포함됩니다.',
        'Some practical ways to use file uploads:': '파일 업로드를 활용하는 실용적인 방법:',
        'Upload a document and ask Claude to summarize the key points': '문서를 업로드하고 Claude에게 핵심 내용을 요약해 달라고 요청하세요',
        'Share an image and ask Claude to describe or analyze what it sees': '이미지를 공유하고 Claude에게 보이는 내용을 설명하거나 분석해 달라고 요청하세요',
        'Attach a spreadsheet and ask Claude to identify trends in the data': '스프레드시트를 첨부하고 Claude에게 데이터의 트렌드를 파악해 달라고 요청하세요',
        'Upload code and ask Claude to explain how it works or find bugs': '코드를 업로드하고 Claude에게 작동 방식을 설명하거나 버그를 찾아달라고 요청하세요',
        "Once uploaded, Claude will automatically attempt to parse the file's content. In the chat, the file appears as an attachment and you can then prompt Claude about it.": '업로드되면 Claude가 자동으로 파일 내용을 파싱합니다. 채팅에서 파일은 첨부 파일로 나타나며, 이에 대해 Claude에게 프롬프트를 보낼 수 있습니다.',
        "If you'd like Claude to consider specific preferences in every response, you can add those within Settings.": 'Claude가 모든 응답에서 특정 환경설정을 고려하길 원하면, 설정에서 추가할 수 있습니다.',
        "Iterating on Claude's responses": 'Claude의 응답 반복 개선하기',
        "Conversations with Claude are meant to be iterative. Chaining bite-sized prompts together allows for a natural dialogue where you guide the conversation based on Claude's replies.": 'Claude와의 대화는 반복적으로 진행되도록 설계되었습니다. 작은 단위의 프롬프트를 연결하면 Claude의 답변을 바탕으로 대화를 이끌어가는 자연스러운 대화가 가능합니다.',
        "If Claude's first response isn't quite what you wanted, you have several options:": 'Claude의 첫 응답이 원하던 것과 다르다면, 여러 가지 옵션이 있습니다:',
        'Ask follow-up questions': '후속 질문하기',
        ''': Build on Claude's response by asking for more detail, a different angle, or clarification. For example: "Can you expand on the second point?" or "That's helpful, but can you make it more concise?"''': ''': Claude의 응답을 바탕으로 더 자세한 내용, 다른 관점, 또는 명확한 설명을 요청하세요. 예: "두 번째 포인트를 더 자세히 설명해 주시겠어요?" 또는 "도움이 되지만, 좀 더 간결하게 해주시겠어요?"''',
        'Provide feedback': '피드백 제공하기',
        ''': Tell Claude what you liked and didn't like about its response. "This is good, but the tone is too formal. Can you make it more conversational?"''': ''': Claude의 응답에서 좋았던 점과 좋지 않았던 점을 말해주세요. "좋지만 톤이 너무 격식적이에요. 좀 더 대화체로 만들어 주시겠어요?"''',
        'Redirect or restart:': '방향 전환 또는 다시 시작:',
        '''If Claude went in a different direction than you intended, simply steer it back. "Actually, I was asking about X, not Y. Let me clarify...". Worst case, restart your conversation in a new chat to fully refresh the context.''': '''Claude가 의도와 다른 방향으로 갔다면, 단순히 되돌리세요. "사실 Y가 아니라 X에 대해 물어본 거예요. 명확히 할게요...". 최악의 경우, 새 채팅에서 대화를 다시 시작하여 컨텍스트를 완전히 새로고침하세요.''',
        'Put it into practice': '실습해 보기',
        'Before moving on, try prompting Claude with a question or task. If you need an idea to get started, feel free to explore our': '다음으로 넘어가기 전에, Claude에게 질문이나 작업을 프롬프트로 보내보세요. 시작할 아이디어가 필요하다면, 저희의',
        "In the next lesson, we'll explore how to give Claude direction—adjusting its tone, format, and approach to match exactly what you need.": '다음 레슨에서는 Claude에게 지시를 주는 방법—톤, 형식, 접근 방식을 필요에 맞게 조정하는 방법을 살펴봅니다.',
    },
}

def translate_file(filepath, translations):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    all_trans = {**COMMON, **translations}
    sorted_items = sorted(all_trans.items(), key=lambda x: len(x[0]), reverse=True)
    for eng, kor in sorted_items:
        if eng in content:
            content = content.replace(eng, kor)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    return content != original

for lesson_name, translations in FILES.items():
    matches = [f for f in os.listdir(FOLDER)
               if f.startswith(lesson_name) and f.endswith('.html') and f != 'index.html']
    if not matches:
        print(f'  [SKIP] No file found for: {lesson_name}')
        continue
    fpath = os.path.join(FOLDER, matches[0])
    changed = translate_file(fpath, translations)
    status = 'TRANSLATED' if changed else 'NO CHANGE'
    print(f'  [{status}] {matches[0]}')

print('\nPart 1 translation complete!')
