#!/usr/bin/env python3
"""Translate files 3-4: Getting better results + Claude desktop app."""
import os

FOLDER = os.path.dirname(os.path.abspath(__file__))

COMMON = {
    'Header Navigation': '헤더 내비게이션',
    'Anthropic Academy': 'Anthropic 아카데미',
    '>Courses<': '>강좌<',
    'Sign Out': '로그아웃',
    '>Previous<': '>이전<',
    '>Next<': '>다음<',
    '>Downloads<': '>다운로드<',
    'Learning objectives': '학습 목표',
    "What you'll learn": '학습 내용',
    'Lesson reflection': '레슨 되돌아보기',
    'Acknowledgments and license': '감사의 말 및 라이선스',
    'Share your feedback': '피드백을 공유해 주세요',
    "As you progress through the course, we'd love to hear from you about how you are using concepts from the course in your work and any feedback you may have. Share your feedback": "강좌를 진행하면서, 강좌의 개념을 업무에 어떻게 활용하고 계신지, 그리고 피드백이 있으시면 알려주세요. 피드백을 공유해 주세요",
    "As you progress through the course, we'd love to hear how you're using the Claude desktop app in your work, plus any feedback you may have. Share your feedback": "강좌를 진행하면서, Claude 데스크톱 앱을 업무에 어떻게 활용하고 계신지, 그리고 피드백이 있으시면 알려주세요. 피드백을 공유해 주세요",
    'Estimated time: 6 minutes': '예상 소요 시간: 6분',
    'Estimated time: 5 minutes': '예상 소요 시간: 5분',
    '>What is Claude?<': '>Claude란 무엇인가?<',
    '>Your first conversation with Claude<': '>Claude와의 첫 대화<',
    '>Getting better results<': '>더 나은 결과 얻기<',
    '>Claude desktop app: Chat, Cowork, Code<': '>Claude 데스크톱 앱: Chat, Cowork, Code<',
    '>Introduction to projects<': '>프로젝트 소개<',
    '>Creating with artifacts<': '>아티팩트로 만들기<',
    '>Working with skills<': '>스킬 활용하기<',
    '>Connecting your tools<': '>도구 연결하기<',
    '>Enterprise search<': '>Enterprise 검색<',
    '>Research mode for deep dives<': '>심층 분석을 위한 Research 모드<',
    '>Claude in action: use-cases by role<': '>Claude 활용 사례: 역할별 사용 사례<',
    '>Other ways to work with Claude<': '>Claude와 함께 일하는 다른 방법<',
    ">What's next?<": '>다음 단계는?<',
    '>Certificate of completion<': '>수료 인증서<',
    'title="What is Claude?"': 'title="Claude란 무엇인가?"',
    'title="Your first conversation with Claude"': 'title="Claude와의 첫 대화"',
    'title="Getting better results"': 'title="더 나은 결과 얻기"',
    'title="Claude desktop app: Chat, Cowork, Code"': 'title="Claude 데스크톱 앱: Chat, Cowork, Code"',
    'title="Introduction to projects"': 'title="프로젝트 소개"',
    'title="Creating with artifacts"': 'title="아티팩트로 만들기"',
    'title="Working with skills"': 'title="스킬 활용하기"',
    'title="Connecting your tools"': 'title="도구 연결하기"',
    'title="Enterprise search"': 'title="Enterprise 검색"',
    'title="Research mode for deep dives"': 'title="심층 분석을 위한 Research 모드"',
    'title="Claude in action: use-cases by role"': 'title="Claude 활용 사례: 역할별 사용 사례"',
    'title="Other ways to work with Claude"': 'title="Claude와 함께 일하는 다른 방법"',
    '''title="What's next?"''': 'title="다음 단계는?"',
    'title="Certificate of completion"': 'title="수료 인증서"',
    '- What is Claude?': '- Claude란 무엇인가?',
    '- Your first conversation with Claude': '- Claude와의 첫 대화',
    '- Getting better results': '- 더 나은 결과 얻기',
    '- Claude desktop app: Chat, Cowork, Code': '- Claude 데스크톱 앱: Chat, Cowork, Code',
    '- Introduction to projects': '- 프로젝트 소개',
    '- Creating with artifacts': '- 아티팩트로 만들기',
    '- Working with skills': '- 스킬 활용하기',
    '- Connecting your tools': '- 도구 연결하기',
    '- Enterprise search': '- Enterprise 검색',
    '- Research mode for deep dives': '- 심층 분석을 위한 Research 모드',
    '- Claude in action: use-cases by role': '- Claude 활용 사례: 역할별 사용 사례',
    '- Other ways to work with Claude': '- Claude와 함께 일하는 다른 방법',
    "- What's next?": '- 다음 단계는?',
    '- Certificate of completion': '- 수료 인증서',
    'By the end of this lesson, you will be able to:': '이 레슨을 마치면 다음을 할 수 있습니다:',
    "By the end of this lesson you'll be able to:": '이 레슨을 마치면 다음을 할 수 있습니다:',
    'Anthropic Help Center': 'Anthropic 도움말 센터',
}

FILES = {
    'Getting better results': {
        'Getting better results': '더 나은 결과 얻기',
        'Recognize common challenges when starting out with AI and use troubleshooting techniques to overcome them': 'AI를 처음 사용할 때 흔히 겪는 문제를 인식하고 해결 기법을 사용하여 극복할 수 있습니다',
        'Define AI Fluency and know where to go to learn more about working with AI in a fluent way': 'AI 활용 능력을 정의하고 AI와 유창하게 작업하는 방법을 더 배울 수 있는 곳을 알 수 있습니다',
        'Explain how you might set up evals to better understand how Claude might perform with your unique workflows': '고유한 워크플로에서 Claude의 성능을 더 잘 이해하기 위해 평가를 설정하는 방법을 설명할 수 있습니다',
        'Common challenges and how to fix them': '흔한 문제와 해결 방법',
        "As you start working with Claude, you'll likely encounter moments where the response isn't quite what you expected. This is normal—and it's an opportunity to refine your approach. Here are some of the": 'Claude를 사용하기 시작하면 응답이 기대와 다른 순간을 경험할 수 있습니다. 이는 정상적인 것이며, 접근 방식을 개선할 기회입니다. 다음은 흔히 겪는',
        "What's happening": '무엇이 일어나고 있나요',
        "Claude's response is too generic": 'Claude의 응답이 너무 일반적입니다',
        "Your prompt didn't include enough context about your specific situation": '프롬프트에 구체적인 상황에 대한 충분한 맥락이 포함되지 않았습니다',
        'Add details about your audience, role, or constraints. Instead of "Write an email about the project delay," try "Write an email to our enterprise client explaining that the software integration will b': '청중, 역할, 제약 조건에 대한 세부사항을 추가하세요. "프로젝트 지연에 대한 이메일을 작성해줘" 대신 "소프트웨어 통합이 지연될 것임을 기업 고객에게 설명하는 이메일을 작성해줘"라고 시도해 보세요',
        'The response is too long (or too short)': '응답이 너무 길거나 (너무 짧습니다)',
        'Claude is guessing at appropriate length': 'Claude가 적절한 길이를 추측하고 있습니다',
        '''Be explicit: "Give me a two-paragraph summary" or "Keep this under 100 words" or "I need a comprehensive analysis—length isn't a concern."''': '''명시적으로 말하세요: "두 단락 요약을 해줘" 또는 "100단어 이내로 작성해줘" 또는 "포괄적인 분석이 필요해—길이는 상관없어."''',
        "Claude didn't follow my format": 'Claude가 형식을 따르지 않았습니다',
        'Claude understood': 'Claude는 이해했지만',
        'you want but not': '원하는 것은 이해했지만',
        'you want it presented': '표현 방식은 이해하지 못했습니다',
        '''Show, don't just tell. Provide an example of the format, or describe the structure explicitly: "Use bullet points with bold headers for each section."''': '''말로만 하지 말고 보여주세요. 형식의 예시를 제공하거나, 구조를 명시적으로 설명하세요: "각 섹션에 굵은 제목과 글머리 기호를 사용해줘."''',
        'I got confident-sounding information that turned out to be wrong': '확신에 찬 것처럼 들리는 정보가 실제로는 잘못된 것이었습니다',
        'Claude occasionally generates plausible but incorrect information, especially with specific facts or niche topics': 'Claude는 특히 구체적인 사실이나 전문적인 주제에서 그럴듯하지만 부정확한 정보를 생성할 수 있습니다',
        'For high-stakes work, verify key facts independently. Ask Claude to cite sources or indicate confidence level. Enable web search to ground responses in current information.': '중요한 업무의 경우, 핵심 사실을 독립적으로 검증하세요. Claude에게 출처를 인용하거나 확신 수준을 표시하도록 요청하세요. 웹 검색을 활성화하여 최신 정보에 기반한 응답을 받으세요.',
        "The tone isn't right": '톤이 맞지 않습니다',
        'Claude defaults to helpful and professional, which may not match your needs': 'Claude는 기본적으로 도움이 되고 전문적인 톤을 사용하며, 이는 요구와 맞지 않을 수 있습니다',
        '''Describe the tone in plain language: "Make this more conversational" or "This should sound authoritative and formal." Provide an example of writing in the style you want.''': '''톤을 평이한 언어로 설명하세요: "좀 더 대화체로 만들어줘" 또는 "권위 있고 격식 있게 들려야 해." 원하는 스타일의 글쓰기 예시를 제공하세요.''',
        'The iteration mindset': '반복적 사고방식',
        "One of the most important shifts when working with Claude is recognizing that your first prompt rarely produces a perfect result—and that's okay. Think of your initial prompt as the start of a convers": "Claude와 작업할 때 가장 중요한 전환 중 하나는 첫 프롬프트가 완벽한 결과를 거의 내지 않는다는 것을 인식하는 것입니다—그리고 그것은 괜찮습니다. 초기 프롬프트를 대화의 시작으로 생각하세요",
        'Effective Claude users:': '효과적인 Claude 사용자는:',
        'Treat first drafts as starting points.': '첫 번째 초안을 출발점으로 취급합니다.',
        "Review what Claude produces, identify what's working and what isn't, then refine.": 'Claude가 생성한 결과를 검토하고, 잘 되는 것과 그렇지 않은 것을 파악한 다음 개선합니다.',
        'Give specific feedback.': '구체적인 피드백을 제공합니다.',
        '"Make it shorter" is fine, but "Cut the first two paragraphs and make the conclusion more action-oriented" is better.': '"짧게 해줘"도 괜찮지만, "처음 두 단락을 잘라내고 결론을 더 실행 지향적으로 만들어줘"가 더 좋습니다.',
        'Know when to start fresh.': '새로 시작할 때를 알고 있습니다.',
        "If a conversation has gone off track, sometimes it's faster to open a new chat with a clearer prompt than to try to redirect.": '대화가 빗나갔다면, 방향을 바꾸려 하기보다 더 명확한 프롬프트로 새 채팅을 여는 것이 더 빠를 때가 있습니다.',
        'What is AI Fluency?': 'AI 활용 능력이란?',
        'AI Fluency is the ability to collaborate effectively with AI tools—not just knowing which buttons to click, but developing the judgment to use AI well across different situations.': 'AI 활용 능력은 AI 도구와 효과적으로 협업하는 능력입니다—어떤 버튼을 클릭해야 하는지 아는 것뿐만 아니라, 다양한 상황에서 AI를 잘 사용하기 위한 판단력을 기르는 것입니다.',
        '4D Framework for AI Fluency': 'AI 활용 능력을 위한 4D 프레임워크',
        ', developed through research collaboration between Professor Rick Dakan (Ringling College of Art and Design) and Professor Joseph Feller (University College Cork), identifies four core competencies th': '는 Rick Dakan 교수(Ringling College of Art and Design)와 Joseph Feller 교수(University College Cork) 간의 연구 협력을 통해 개발되었으며, 네 가지 핵심 역량을 식별합니다',
        'Deciding on what work should be done by humans, what work should be done by AI, and how to distribute tasks between them. Includes understanding your goals, AI capabilities, and making strategic choic': '인간이 할 작업, AI가 할 작업, 그리고 이들 사이에 작업을 분배하는 방법을 결정합니다. 목표, AI 역량 이해, 전략적 선택을 포함합니다',
        'Effectively communicating with AI systems. Includes clearly defining outputs, guiding AI processes, and specifying desired AI behaviors and interactions.': 'AI 시스템과 효과적으로 소통합니다. 출력을 명확하게 정의하고, AI 프로세스를 안내하며, 원하는 AI 행동과 상호작용을 지정하는 것을 포함합니다.',
        'Thoughtfully and critically evaluating AI outputs, processes, behaviors and interactions. Includes assessing quality, accuracy, appropriateness, and determining areas for improvement.': 'AI 출력, 프로세스, 행동 및 상호작용을 신중하고 비판적으로 평가합니다. 품질, 정확성, 적절성을 평가하고 개선 영역을 결정하는 것을 포함합니다.',
        'Using AI responsibly and ethically. Includes making thoughtful choices about AI systems and interactions, maintaining transparency, and taking accountability for AI-assisted work.': 'AI를 책임감 있고 윤리적으로 사용합니다. AI 시스템과 상호작용에 대한 신중한 선택, 투명성 유지, AI 지원 작업에 대한 책임을 포함합니다.',
        "You've already been practicing these skills throughout this course. The prompt framework from Lesson 2 (setting the stage, defining the task, specifying rules) is rooted in Description. The troublesho": '이 강좌를 통해 이미 이러한 기술을 연습해 왔습니다. 레슨 2의 프롬프트 프레임워크(무대 설정, 과제 정의, 규칙 지정)는 기술(Description)에 뿌리를 두고 있습니다. 문제 해결은',
        'To learn more, check out our free': '더 알아보려면, 무료',
        'AI Fluency course': 'AI 활용 능력 강좌',
        'that explores all four competencies in depth, with practical exercises and real-world applications.': '를 확인하세요. 실습과 실제 응용을 통해 네 가지 역량을 심층적으로 탐구합니다.',
        'Evaluating Claude for your workflows': '워크플로를 위한 Claude 평가하기',
        'As you start integrating Claude into more of your work, you might wonder: how do I know if Claude is actually good at this particular task?': 'Claude를 더 많은 업무에 통합하기 시작하면 궁금해질 수 있습니다: 이 특정 작업에 Claude가 실제로 잘 맞는지 어떻게 알 수 있을까?',
        '(short for evaluations) come in. Evals are systematic ways to test how well Claude performs on specific types of tasks that matter to you.': '(evaluations의 약자)가 등장합니다. 평가(Evals)는 중요한 특정 유형의 작업에서 Claude의 성능을 체계적으로 테스트하는 방법입니다.',
        'Why evals matter': '평가가 중요한 이유',
        'Your work is unique. Claude might excel at drafting marketing copy but need more guidance for technical documentation in your specific domain. Running simple evals helps you:': '여러분의 업무는 고유합니다. Claude는 마케팅 카피 작성에는 뛰어나지만 특정 분야의 기술 문서에는 더 많은 안내가 필요할 수 있습니다. 간단한 평가를 실행하면 다음에 도움이 됩니다:',
        'Understand where Claude adds the most value in your workflow': '워크플로에서 Claude가 가장 큰 가치를 더하는 곳을 이해할 수 있습니다',
        "Identify tasks where you'll need to provide more context or examples": '더 많은 맥락이나 예시를 제공해야 할 작업을 파악할 수 있습니다',
        "Build confidence in Claude's outputs for recurring tasks": '반복 작업에 대한 Claude의 출력에 대한 신뢰를 구축할 수 있습니다',
        'A simple eval approach': '간단한 평가 접근법',
        "You don't need complex infrastructure to evaluate Claude. Here's a practical approach:": 'Claude를 평가하기 위해 복잡한 인프라가 필요하지 않습니다. 실용적인 접근법을 소개합니다:',
        'Gather examples.': '예시를 수집합니다.',
        "Collect 5-10 examples of a task you do regularly—emails you've written, reports you've created, analyses you've done.": '정기적으로 하는 작업의 예시를 5-10개 수집하세요—작성한 이메일, 만든 보고서, 수행한 분석 등.',
        'Create test prompts.': '테스트 프롬프트를 만듭니다.',
        "Write prompts that would generate similar outputs. Include the context you'd naturally have when doing this work.": '유사한 결과를 생성할 프롬프트를 작성하세요. 이 작업을 할 때 자연스럽게 갖는 맥락을 포함하세요.',
        'Compare outputs.': '결과를 비교합니다.',
        "Run your prompts and compare Claude's responses to your examples. Ask yourself:": '프롬프트를 실행하고 Claude의 응답을 예시와 비교하세요. 스스로에게 물어보세요:',
        'Does Claude capture the key information?': 'Claude가 핵심 정보를 포착하나요?',
        'Is the tone and style appropriate?': '톤과 스타일이 적절한가요?',
        "What's missing or could be improved?": '무엇이 빠져있거나 개선될 수 있나요?',
        'Refine your approach.': '접근 방식을 개선합니다.',
        'Based on what you learn, adjust your prompts, add examples to show Claude what good looks like, or identify where human review is essential.': '배운 것을 바탕으로 프롬프트를 조정하고, Claude에게 좋은 결과가 어떤 것인지 보여주는 예시를 추가하거나, 인간 검토가 필수적인 곳을 파악하세요.',
        'Example: Using Claude for data analysis': '예시: 데이터 분석에 Claude 사용하기',
        'The video above is taken from our AI Fluency for nonprofits course, but the example is relevant for anyone working with data in AI. To evaluate how Claude might work with your data:': '위 영상은 비영리 단체를 위한 AI 활용 능력 강좌에서 가져온 것이지만, 이 예시는 AI에서 데이터를 다루는 모든 사람에게 관련이 있습니다. Claude가 데이터와 어떻게 작동하는지 평가하려면:',
        "Find a dataset you've manually analyzed": '수동으로 분석한 데이터셋을 찾으세요',
        'Create prompts that request Claude to do the analysis on your behalf': 'Claude에게 대신 분석을 수행하도록 요청하는 프롬프트를 만드세요',
        "Compare Claude's results to your originals": 'Claude의 결과를 원래 결과와 비교하세요',
        'Note patterns and refine your prompt accordingly: Maybe Claude gets the right numbers but misses the overall patterns': '패턴을 기록하고 프롬프트를 개선하세요: Claude가 올바른 숫자를 얻지만 전체적인 패턴을 놓칠 수 있습니다',
        'This kind of lightweight evaluation helps you develop intuition for how to work with Claude on tasks that matter to you—and where to focus your review and refinement energy.': '이런 종류의 가벼운 평가는 중요한 작업에서 Claude와 작업하는 방법에 대한 직관을 개발하고, 검토와 개선에 에너지를 집중할 곳을 파악하는 데 도움이 됩니다.',
        'Before moving on, consider:': '다음으로 넘어가기 전에 고려해 보세요:',
        'Which of the common challenges have you already encountered? What techniques might you try next time?': '흔한 문제 중 이미 경험한 것은 무엇인가요? 다음에는 어떤 기법을 시도해 볼 수 있을까요?',
        'Where in your work would a simple eval help you understand if Claude is a good fit for a recurring task?': '업무에서 간단한 평가가 반복 작업에 Claude가 적합한지 이해하는 데 도움이 될 곳은 어디인가요?',
        'How might the 4D Framework help you think about your collaboration with Claude?': '4D 프레임워크가 Claude와의 협업에 대해 어떻게 생각하는 데 도움이 될 수 있을까요?',
        "In the next module, you'll learn how to organize your work with Claude using Projects—dedicated workspaces where you can store knowledge, set custom instructions, and collaborate with teammates.": '다음 모듈에서는 프로젝트를 사용하여 Claude와의 작업을 구성하는 방법을 배웁니다—지식을 저장하고, 맞춤 지침을 설정하며, 팀원과 협업할 수 있는 전용 워크스페이스입니다.',
    },
    'Claude desktop app': {
        'Claude desktop app: Chat, Cowork, Code': 'Claude 데스크톱 앱: Chat, Cowork, Code',
        'Identify the three modes in the Claude desktop app — Chat, Cowork, and Code — and what each is designed for': 'Claude 데스크톱 앱의 세 가지 모드 — Chat, Cowork, Code — 와 각각의 용도를 파악할 수 있습니다',
        'Explain key features unique to each mode, including quick entry, scheduled tasks, and local vs. remote development': '빠른 입력, 예약 작업, 로컬 vs. 원격 개발을 포함한 각 모드의 고유 기능을 설명할 수 있습니다',
        'Choose the right mode based on the type of work you need to accomplish': '수행해야 할 작업 유형에 따라 적합한 모드를 선택할 수 있습니다',
        'Navigating the Claude desktop app: Chat, Cowork, Code': 'Claude 데스크톱 앱 탐색하기: Chat, Cowork, Code',
        'The Claude desktop app gives you three ways to work with Claude: Chat, Cowork, and Code — from quick questions to complex research to building software.': 'Claude 데스크톱 앱은 빠른 질문부터 복잡한 연구, 소프트웨어 구축까지 — Chat, Cowork, Code의 세 가지 방식으로 Claude와 작업할 수 있습니다.',
        'Chat is the same Claude you know from claude.ai, plus quick entry, screenshots, dictation, and connectors that come from running natively on your computer. Cowork gives Claude the reach and the room t': 'Chat은 claude.ai에서 알고 있는 Claude와 동일하며, 여기에 컴퓨터에서 네이티브로 실행되어 제공되는 빠른 입력, 스크린샷, 받아쓰기, 커넥터가 추가됩니다. Cowork는 Claude에게 범위와 여유를 제공합니다',
        'Cowork and Code run on the same engine. Both are Claude Code underneath — local to your machine, capable of independent work, able to spin up sub-agents and sustain long tasks. Thi': 'Cowork와 Code는 동일한 엔진에서 실행됩니다. 둘 다 내부적으로 Claude Code입니다 — 로컬 머신에서 실행되며, 독립적인 작업이 가능하고, 서브 에이전트를 생성하여 긴 작업을 지속할 수 있습니다. 이것은',
        'Each mode is designed around the work it serves, showing you what matters and giving you control where you need it.': '각 모드는 해당 작업에 맞게 설계되어, 중요한 것을 보여주고 필요한 곳에서 제어권을 제공합니다.',
        'Chat excels when you need to ask questions, brainstorm, draft, or work through problems back and forth.': 'Chat은 질문하거나, 브레인스토밍하거나, 초안을 작성하거나, 문제를 반복적으로 해결할 때 뛰어납니다.',
        "If you've used claude.ai, this works the same way, with a few things that come from running natively on your computer:": 'claude.ai를 사용해 본 적이 있다면 동일하게 작동하며, 컴퓨터에서 네이티브로 실행되어 제공되는 몇 가지 기능이 있습니다:',
        "Double-tap the Option key on Mac to pull up Claude over whatever you're working on. It responds in a compact window that stays on top as you switch between apps. You never have to ": "Mac에서 Option 키를 두 번 눌러 작업 중인 화면 위에 Claude를 불러올 수 있습니다. 앱 간 전환 시에도 상단에 유지되는 컴팩트한 창에서 응답합니다. 절대로 ",
        'Screenshots and window sharing.': '스크린샷 및 창 공유.',
        "Capture a screenshot or share a window so Claude sees exactly what you're looking at. Faster than describing what's on your screen, and more precise. (Mac)": '스크린샷을 캡처하거나 창을 공유하면 Claude가 여러분이 보고 있는 것을 정확히 볼 수 있습니다. 화면의 내용을 설명하는 것보다 빠르고 정확합니다. (Mac)',
        "Talk through a problem instead of typing. Useful when you're thinking out loud, away from your keyboard, or working through something where speaking is faster than writing. (Mac)": '타이핑 대신 문제를 말로 풀어보세요. 소리내어 생각하거나, 키보드에서 떨어져 있거나, 글보다 말이 빠른 작업을 할 때 유용합니다. (Mac)',
        'Desktop connectors.': '데스크톱 커넥터.',
        'Connect local tools and services through connectors so Claude can work with other tools on your machine.': '커넥터를 통해 로컬 도구와 서비스를 연결하여 Claude가 컴퓨터의 다른 도구와 함께 작업할 수 있습니다.',
        'Try it out when:': '다음과 같은 경우에 사용해 보세요:',
        '''You're staring at an unfamiliar dashboard. Double-tap Option, drag your cursor over the window to screenshot it, and ask "what do these metrics mean?" Claude answers in the overlay while the dashboard''': '''익숙하지 않은 대시보드를 보고 있을 때. Option을 두 번 눌러 창을 스크린샷으로 캡처하고 "이 지표들은 무엇을 의미하나요?"라고 물어보세요. 대시보드가 표시된 상태에서 Claude가 오버레이에서 답변합니다''',
        '''You're in between meetings and want to think through how to structure a presentation. Open quick entry, switch to voice, and talk it through. Claude drafts an outline from what you said.''': '''회의 사이에 프레젠테이션 구조를 생각하고 싶을 때. 빠른 입력을 열고 음성으로 전환하여 말로 정리하세요. Claude가 말한 내용으로 개요 초안을 작성합니다.''',
        '''You've been jotting down ideas for a product launch across Apple Notes for weeks. You add the Notes connector from Settings and ask Claude: "Pull together everything in my notes about the Osprey launc''': '''몇 주 동안 Apple Notes에 제품 출시 아이디어를 메모해 왔을 때. 설정에서 Notes 커넥터를 추가하고 Claude에게 "Osprey 출시에 대한 내 메모의 모든 내용을 정리해줘"라고 요청합니다''',
        'Claude Cowork is built for work that takes real effort: pulling information from many sources, making sense of it, and producing something finished.': 'Claude Cowork는 진정한 노력이 필요한 작업을 위해 만들어졌습니다: 여러 소스에서 정보를 가져오고, 이해하고, 완성된 결과물을 만들어냅니다.',
        'Claude can multitask, tackling different parts of a project at a time, so it has the scope to draw from more sources and the stamina to see things through. Thorough research briefs, cross-source finan': 'Claude는 멀티태스킹이 가능하여 프로젝트의 여러 부분을 동시에 처리할 수 있으므로, 더 많은 소스에서 정보를 가져오고 작업을 끝까지 완수할 수 있습니다. 철저한 연구 브리프, 교차 소스 재무',
        'Before starting, Claude often asks a short set of questions to pin down what you need: scope, format, constraints. It builds a plan you can review in the sidebar. As it works, you see the task come to': '시작하기 전에 Claude는 필요한 것을 파악하기 위해 짧은 질문을 합니다: 범위, 형식, 제약 조건. 사이드바에서 검토할 수 있는 계획을 세웁니다. 작업이 진행되면 과업이 형성되는 것을',
        "Give Claude a folder on your computer and it reads what's there, figures out what's relevant, and saves finished work back to the same place. You can also upload files, paste content into the conversa": "컴퓨터의 폴더를 Claude에게 제공하면 거기에 있는 내용을 읽고, 관련 있는 것을 파악하며, 완성된 작업을 같은 위치에 저장합니다. 파일을 업로드하거나 대화에 내용을 붙여넣을 수도 있습니다",
        'Scheduled tasks.': '예약 작업.',
        'Claude can handle recurring work on a schedule: a daily briefing that pulls from your Slack and calendar, a weekly roundup of what shipped, a morning inbox triage that sorts what needs your attention.': 'Claude는 일정에 따른 반복 작업을 처리할 수 있습니다: Slack과 캘린더에서 가져오는 일일 브리핑, 배포된 내용의 주간 요약, 주의가 필요한 항목을 정리하는 아침 받은편지함 분류.',
        "Connect Claude in Chrome and Claude can navigate websites, interact with pages, and pull what it finds directly into the task it's working on. This is how Cowork does things like check competitor pric": "Chrome에서 Claude를 연결하면 웹사이트를 탐색하고, 페이지와 상호작용하며, 찾은 내용을 진행 중인 작업에 직접 가져올 수 있습니다. 이것이 Cowork가 경쟁사 가격 확인 같은 작업을 수행하는 방식입니다",
        "Plugins give Claude capabilities it doesn't have on its own: pulling live financial data, searching your company's internal knowledge base, or working within a specific compliance framework. Browse an": "플러그인은 Claude에게 자체적으로 갖지 못한 기능을 제공합니다: 실시간 재무 데이터 가져오기, 회사의 내부 지식 기반 검색, 특정 규정 준수 프레임워크 내에서 작업. 플러그인을 찾아보고",
        'Protected environment.': '보호된 환경.',
        "Cowork runs in a contained space on your computer. Claude can read, create, and edit files within the folders you share, but can't access anything outside them.": 'Cowork는 컴퓨터의 격리된 공간에서 실행됩니다. Claude는 공유한 폴더 내에서 파일을 읽고, 만들고, 편집할 수 있지만, 그 외부에는 접근할 수 없습니다.',
        'You want to query all your tools like you would a database. Ask "what did we decide about pricing last quarter?" and Cowork finds the answer across meeting notes, slide decks, email, and Slack threads': '모든 도구를 데이터베이스처럼 조회하고 싶을 때. "지난 분기에 가격에 대해 뭘 결정했지?"라고 물어보면 Cowork가 회의록, 슬라이드, 이메일, Slack 스레드에서 답을 찾습니다',
        "You're researching a new market, scoping competitors, evaluating tools. For any research that might span multiple tabs with hard to extract information, Cowork visits the sites, reads the reports, pul": "새로운 시장을 조사하거나, 경쟁사를 파악하거나, 도구를 평가할 때. 여러 탭에 걸쳐 추출하기 어려운 정보가 있는 조사의 경우, Cowork가 사이트를 방문하고, 보고서를 읽고, 정보를 가져옵니다",
        'You need to parse through large documents where the details matter: contracts, financial reports, meeting transcripts. Cowork reads every page, cross-references across the full set, and pulls out the ': '세부사항이 중요한 대규모 문서를 분석해야 할 때: 계약서, 재무 보고서, 회의 녹취록. Cowork는 모든 페이지를 읽고, 전체 세트에 걸쳐 교차 참조하며, 핵심 내용을 추출합니다 ',
        "You keep doing the same work every morning — checking messages, pulling together a status update, prepping for the day's meetings. Set it up once as a scheduled task and Claude handles it on repeat, s": "매일 아침 같은 작업을 반복할 때 — 메시지 확인, 현황 업데이트 정리, 당일 회의 준비. 예약 작업으로 한 번 설정하면 Claude가 반복적으로 처리합니다",
        'Cowork is currently a research preview, available to Pro, Max, Team, and Enterprise users, with new capabilities being added regularly.': 'Cowork는 현재 연구 프리뷰 단계이며, Pro, Max, Team, Enterprise 사용자에게 제공되고, 새로운 기능이 정기적으로 추가됩니다.',
        'Code puts a full development environment inside the desktop app, powered by Claude Code.': 'Code는 Claude Code로 구동되는 완전한 개발 환경을 데스크톱 앱에 제공합니다.',
        "Claude works directly in your codebase: reading what's there, writing and modifying code, running commands. Visual diffs show what changed, a built-in terminal shows commands as they run, and git trac": "Claude는 코드베이스에서 직접 작업합니다: 기존 코드를 읽고, 코드를 작성하고 수정하며, 명령을 실행합니다. 시각적 diff로 변경 사항을 보여주고, 내장 터미널에서 명령 실행을 보여주며, git 추적을 합니다",
        'Where Cowork runs in a contained workspace limited to the folders you share, Code runs directly in your project with full access to your file system, terminal, and development tools.': 'Cowork가 공유한 폴더로 제한된 격리된 워크스페이스에서 실행되는 반면, Code는 파일 시스템, 터미널, 개발 도구에 대한 전체 접근 권한으로 프로젝트에서 직접 실행됩니다.',
        'You choose where work happens:': '작업이 수행되는 위치를 선택합니다:',
        'You select a folder on your computer and Claude works directly with those files. Because it runs on your machine, Claude can read your project, access local tools, and run a development server you can': '컴퓨터의 폴더를 선택하면 Claude가 해당 파일로 직접 작업합니다. 로컬 머신에서 실행되므로, Claude가 프로젝트를 읽고, 로컬 도구에 접근하며, 개발 서버를 실행할 수 있습니다',
        'You connect a GitHub repository and Claude works in a cloud environment. Sessions continue even if you close the app, so you can start a big refactor and check back later. Good for larger codebases or': 'GitHub 저장소를 연결하면 Claude가 클라우드 환경에서 작업합니다. 앱을 닫아도 세션이 계속되므로, 대규모 리팩토링을 시작하고 나중에 확인할 수 있습니다. 대규모 코드베이스나',
        'Three interaction modes let you control how much Claude does on its own:': '세 가지 상호작용 모드로 Claude의 자율성 수준을 제어할 수 있습니다:',
        'Claude proposes every change and waits for your approval. You review a visual diff and accept or reject before anything is modified.': 'Claude가 모든 변경을 제안하고 승인을 기다립니다. 시각적 diff를 검토하고 수정 전에 수락 또는 거부합니다.',
        'Claude applies file changes automatically but checks before running terminal commands.': 'Claude가 파일 변경을 자동으로 적용하지만 터미널 명령을 실행하기 전에 확인합니다.',
        'Claude outlines its full approach before touching anything. A dedicated plan viewer lets you review and revisit the strategy as work progresses.': 'Claude가 작업에 착수하기 전에 전체 접근 방식을 설명합니다. 전용 계획 뷰어를 통해 작업이 진행됨에 따라 전략을 검토하고 재확인할 수 있습니다.',
        'You can run multiple sessions across projects and filter them by status (Active or Archived) and environment (Local or Cloud) from the sidebar.': '여러 프로젝트에 걸쳐 여러 세션을 실행하고, 사이드바에서 상태(활성 또는 보관됨)와 환경(로컬 또는 클라우드)으로 필터링할 수 있습니다.',
        'The Code tab is rolling out to Pro, Max, Team, and Enterprise users.': 'Code 탭은 Pro, Max, Team, Enterprise 사용자에게 순차적으로 배포되고 있습니다.',
        'Comparing the three modes': '세 가지 모드 비교',
        'Quicker exchanges: exploring ideas, iterative drafting, quick answers, learning through dialogue': '빠른 교류: 아이디어 탐구, 반복적인 초안 작성, 빠른 답변, 대화를 통한 학습',
        'Complex or sustained work: research, analysis, file organization, producing finished documents and deliverables': '복잡하거나 지속적인 작업: 연구, 분석, 파일 정리, 완성된 문서 및 산출물 제작',
        'Building software: writing, testing, running and deploying code': '소프트웨어 구축: 코드 작성, 테스트, 실행 및 배포',
        'Quick entry, dictation': '빠른 입력, 받아쓰기',
        'Work from local folders, plugins, subagents, scheduled tasks': '로컬 폴더, 플러그인, 서브에이전트, 예약 작업에서 작업',
        'Ask/Code/Plan modes, visual diffs, git integration, local and remote environments': 'Ask/Code/Plan 모드, 시각적 diff, git 통합, 로컬 및 원격 환경',
        'Tools and extensions': '도구 및 확장',
        'Connectors, Skills, Claude in Chrome': '커넥터, 스킬, Claude in Chrome',
        'Connectors (local and remote), Skills, Claude in Chrome, Plugins': '커넥터(로컬 및 원격), 스킬, Claude in Chrome, 플러그인',
        'Connectors, Skills, Claude in Chrome, Plugins, Hooks': '커넥터, 스킬, Claude in Chrome, 플러그인, 훅',
        'Think about the tasks you most commonly use Claude for. Which mode — Chat, Cowork, or Code — would best fit each of those tasks?': 'Claude를 가장 자주 사용하는 작업을 생각해 보세요. Chat, Cowork, Code 중 어떤 모드가 각 작업에 가장 적합할까요?',
        'Consider a recent project where you needed to pull information from multiple sources. How might Cowork have changed your workflow?': '여러 소스에서 정보를 가져와야 했던 최근 프로젝트를 떠올려 보세요. Cowork가 워크플로를 어떻게 변화시켰을까요?',
        "In the next lesson, you'll dive deeper into one of these modes and see how to get the most out of it in your daily workflow.": '다음 레슨에서는 이 모드 중 하나를 더 깊이 살펴보고 일상 워크플로에서 최대한 활용하는 방법을 알아봅니다.',
    },
}

def translate_file(filepath, translations):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    all_trans = {**COMMON, **translations}
    sorted_items = sorted(all_trans.items(), key=lambda x: len(x[0]), reverse=True)
    for eng, kor in sorted_items:
        if eng in content:
            content = content.replace(eng, kor)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    return content != original

for lesson_name, translations in FILES.items():
    matches = [f for f in os.listdir(FOLDER)
               if f.startswith(lesson_name) and f.endswith('.html') and f != 'index.html']
    if not matches:
        print(f'  [SKIP] No file found for: {lesson_name}')
        continue
    fpath = os.path.join(FOLDER, matches[0])
    changed = translate_file(fpath, translations)
    status = 'TRANSLATED' if changed else 'NO CHANGE'
    print(f'  [{status}] {matches[0]}')

print('\nPart 2 translation complete!')
