#!/usr/bin/env python3
"""Translate files 9-10: Enterprise search + Research mode for deep dives."""
import os

FOLDER = os.path.dirname(os.path.abspath(__file__))

COMMON = {
    'Header Navigation': '헤더 내비게이션',
    'Anthropic Academy': 'Anthropic 아카데미',
    '>Courses<': '>강좌<',
    'Sign Out': '로그아웃',
    '>Previous<': '>이전<',
    '>Next<': '>다음<',
    '>Downloads<': '>다운로드<',
    'Learning objectives': '학습 목표',
    "What you'll learn": '학습 내용',
    'Lesson reflection': '레슨 되돌아보기',
    'Acknowledgments and license': '감사의 말 및 라이선스',
    'Share your feedback': '피드백을 공유해 주세요',
    "As you progress through the course, we'd love to hear from you about how you are using concepts from the course in your work and any feedback you may have. Share your feedback": "강좌를 진행하면서, 강좌의 개념을 업무에 어떻게 활용하고 계신지, 그리고 피드백이 있으시면 알려주세요. 피드백을 공유해 주세요",
    '>What is Claude?<': '>Claude란 무엇인가?<',
    '>Your first conversation with Claude<': '>Claude와의 첫 대화<',
    '>Getting better results<': '>더 나은 결과 얻기<',
    '>Claude desktop app: Chat, Cowork, Code<': '>Claude 데스크톱 앱: Chat, Cowork, Code<',
    '>Introduction to projects<': '>프로젝트 소개<',
    '>Creating with artifacts<': '>아티팩트로 만들기<',
    '>Working with skills<': '>스킬 활용하기<',
    '>Connecting your tools<': '>도구 연결하기<',
    '>Enterprise search<': '>Enterprise 검색<',
    '>Research mode for deep dives<': '>심층 분석을 위한 Research 모드<',
    '>Claude in action: use-cases by role<': '>Claude 활용 사례: 역할별 사용 사례<',
    '>Other ways to work with Claude<': '>Claude와 함께 일하는 다른 방법<',
    ">What's next?<": '>다음 단계는?<',
    '>Certificate of completion<': '>수료 인증서<',
    'title="What is Claude?"': 'title="Claude란 무엇인가?"',
    'title="Your first conversation with Claude"': 'title="Claude와의 첫 대화"',
    'title="Getting better results"': 'title="더 나은 결과 얻기"',
    'title="Claude desktop app: Chat, Cowork, Code"': 'title="Claude 데스크톱 앱: Chat, Cowork, Code"',
    'title="Introduction to projects"': 'title="프로젝트 소개"',
    'title="Creating with artifacts"': 'title="아티팩트로 만들기"',
    'title="Working with skills"': 'title="스킬 활용하기"',
    'title="Connecting your tools"': 'title="도구 연결하기"',
    'title="Enterprise search"': 'title="Enterprise 검색"',
    'title="Research mode for deep dives"': 'title="심층 분석을 위한 Research 모드"',
    'title="Claude in action: use-cases by role"': 'title="Claude 활용 사례: 역할별 사용 사례"',
    'title="Other ways to work with Claude"': 'title="Claude와 함께 일하는 다른 방법"',
    '''title="What's next?"''': 'title="다음 단계는?"',
    'title="Certificate of completion"': 'title="수료 인증서"',
    '- What is Claude?': '- Claude란 무엇인가?',
    '- Your first conversation with Claude': '- Claude와의 첫 대화',
    '- Getting better results': '- 더 나은 결과 얻기',
    '- Claude desktop app: Chat, Cowork, Code': '- Claude 데스크톱 앱: Chat, Cowork, Code',
    '- Introduction to projects': '- 프로젝트 소개',
    '- Creating with artifacts': '- 아티팩트로 만들기',
    '- Working with skills': '- 스킬 활용하기',
    '- Connecting your tools': '- 도구 연결하기',
    '- Enterprise search': '- Enterprise 검색',
    '- Research mode for deep dives': '- 심층 분석을 위한 Research 모드',
    '- Claude in action: use-cases by role': '- Claude 활용 사례: 역할별 사용 사례',
    '- Other ways to work with Claude': '- Claude와 함께 일하는 다른 방법',
    "- What's next?": '- 다음 단계는?',
    '- Certificate of completion': '- 수료 인증서',
    'By the end of this lesson, you will be able to:': '이 레슨을 마치면 다음을 할 수 있습니다:',
    'Anthropic Help Center': 'Anthropic 도움말 센터',
    'Before moving on, consider:': '다음으로 넘어가기 전에 고려해 보세요:',
}

FILES = {
    'Enterprise search': {
        'Enterprise search': 'Enterprise 검색',
        'Explain what Enterprise Search is and the types of questions Enterprise Search can answer': 'Enterprise 검색이 무엇이고 어떤 유형의 질문에 답할 수 있는지 설명할 수 있습니다',
        'Understand how the setup process works for both admins and users': '관리자와 사용자 모두를 위한 설정 프로세스가 어떻게 작동하는지 이해할 수 있습니다',
        'Recognize how security and permissions protect organizational data': '보안 및 권한이 조직 데이터를 어떻게 보호하는지 인식할 수 있습니다',
        'What is Enterprise Search?': 'Enterprise 검색이란 무엇인가요?',
        '''Enterprise Search adds a dedicated "Ask {Your Org Name}" option to your sidebar. This is designed specifically for finding and synthesizing knowledge buried across your company's tools and data source''': '''Enterprise 검색은 사이드바에 전용 "Ask {조직 이름}" 옵션을 추가합니다. 이것은 회사의 도구와 데이터 소스에 분산된 지식을 찾고 종합하기 위해 특별히 설계되었습니다''',
        'Unlike regular chats with connectors enabled, Enterprise Search is specifically designed for information gathering, using custom instructions configured by the Anthropic team.': '커넥터가 활성화된 일반 채팅과 달리, Enterprise 검색은 Anthropic 팀이 구성한 맞춤 지침을 사용하여 정보 수집을 위해 특별히 설계되었습니다.',
        'What can you ask?': '무엇을 물어볼 수 있나요?',
        'Enterprise Search is particularly valuable for questions that span multiple sources or require synthesizing information from across your organization. Here are some common use cases:': 'Enterprise 검색은 여러 소스에 걸친 질문이나 조직 전체의 정보를 종합해야 하는 질문에 특히 유용합니다. 일반적인 사용 사례를 소개합니다:',
        'Getting up to speed': '최신 상황 파악하기',
        '"What happened yesterday while I was out?"': '"어제 내가 없는 동안 무슨 일이 있었나요?"',
        '"Summarize key updates across the business from the last week"': '"지난 주 비즈니스 전반의 주요 업데이트를 요약해 주세요"',
        '"What are the current blockers on the Platform project?"': '"Platform 프로젝트의 현재 차단 요인은 무엇인가요?"',
        'Policy and process questions': '정책 및 프로세스 질문',
        '"What is our company\'s remote work policy?"': '"회사의 원격 근무 정책은 무엇인가요?"',
        '"How do I submit an expense report?"': '"경비 보고서를 어떻게 제출하나요?"',
        '"What\'s the process for requesting time off?"': '"휴가 요청 절차는 무엇인가요?"',
        'Research and analysis': '조사 및 분석',
        '"What are the main reasons customers cite for choosing competitors?"': '"고객이 경쟁사를 선택하는 주요 이유는 무엇인가요?"',
        '"Summarize discussions about the Q4 product roadmap"': '"Q4 제품 로드맵에 대한 논의를 요약해 주세요"',
        '"Find information about our customer onboarding process"': '"고객 온보딩 프로세스에 대한 정보를 찾아 주세요"',
        'Onboarding new team members': '새 팀원 온보딩',
        '"How does our authentication system work?"': '"인증 시스템은 어떻게 작동하나요?"',
        '"Who should I talk to about learning the billing system?"': '"청구 시스템에 대해 배우려면 누구에게 문의해야 하나요?"',
        '"What tools does the engineering team use for deployment?"': '"엔지니어링 팀은 배포에 어떤 도구를 사용하나요?"',
        'Performance and project tracking': '성과 및 프로젝트 추적',
        '"Find discussions and documents related to the marketing campaign"': '"마케팅 캠페인과 관련된 논의 및 문서를 찾아 주세요"',
        '"What were the key decisions from last week\'s leadership meetings?"': '"지난주 리더십 회의의 주요 결정사항은 무엇이었나요?"',
        '"Summarize team contributions to the Infrastructure initiative"': '"인프라 이니셔티브에 대한 팀 기여를 요약해 주세요"',
        'When you ask a question, Claude searches across all your connected tools—such as SharePoint documents, Slack conversations, Gmail threads, and Google Drive files—and synthesizes information into a uni': '질문을 하면, Claude가 SharePoint 문서, Slack 대화, Gmail 스레드, Google Drive 파일 등 연결된 모든 도구를 검색하고 정보를 통합된',
        'Setting up Enterprise Search': 'Enterprise 검색 설정하기',
        'Enterprise Search requires a': 'Enterprise 검색은',
        'two-step setup process': '2단계 설정 프로세스',
        ': first an admin configures it for the organization, then individual users authenticate with their personal accounts.': '가 필요합니다: 먼저 관리자가 조직을 위해 구성한 다음, 개별 사용자가 개인 계정으로 인증합니다.',
        'For admins (Owners)': '관리자(소유자)용',
        'The Enterprise Search project is enabled by default for all Team and Enterprise organizations, but an Owner needs to complete the initial setup before team members can use it:': 'Enterprise 검색 프로젝트는 모든 Team 및 Enterprise 조직에 기본적으로 활성화되어 있지만, 팀원이 사용하려면 소유자가 초기 설정을 완료해야 합니다:',
        'Click "Ask Your Org" in the left sidebar.': '왼쪽 사이드바에서 "Ask Your Org"를 클릭하세요.',
        'Click "Set up for your org" to continue (or "Disable" to turn the feature off).': '"Set up for your org"를 클릭하여 계속하세요 (또는 "Disable"로 기능을 끄세요).',
        "Connect your organization's tools. You'll be required to choose a connector for": '조직의 도구를 연결하세요. 다음을 위한 커넥터를 선택해야 합니다',
        '(like Google Drive or SharePoint) and': '(Google Drive 또는 SharePoint 등) 및',
        '(like Slack or Microsoft Teams). Email is recommended but optional.': '(Slack 또는 Microsoft Teams 등). 이메일은 권장되지만 선택 사항입니다.',
        'Click "+ Add more" to set up any additional tools your team needs.': '"+ Add more"를 클릭하여 팀에 필요한 추가 도구를 설정하세요.',
        'Customize the project name. Whatever you enter will appear as "Ask [Name]" in everyone\'s sidebar.': '프로젝트 이름을 맞춤 설정하세요. 입력한 내용이 모든 사람의 사이드바에 "Ask [이름]"으로 표시됩니다.',
        'Add a description, then click "Finish set up."': '설명을 추가한 다음 "Finish set up"을 클릭하세요.',
        'Once setup is complete, the project becomes available to all members of your organization.': '설정이 완료되면 조직의 모든 멤버가 프로젝트를 사용할 수 있습니다.',
        'After an admin has set up Enterprise Search, you\'ll see the "Ask {Org Name}" project starred in your sidebar. Here\'s how to get started:': '관리자가 Enterprise 검색을 설정한 후, 사이드바에 "Ask {조직 이름}" 프로젝트가 별표로 표시됩니다. 시작하는 방법은 다음과 같습니다:',
        'Click on the project in your sidebar.': '사이드바에서 프로젝트를 클릭하세요.',
        'Follow the guided onboarding flow to connect to the recommended services.': '안내된 온보딩 흐름을 따라 추천 서비스에 연결하세요.',
        'Authenticate with each service you want to search (Slack, Google, Microsoft 365, etc.).': '검색하려는 각 서비스(Slack, Google, Microsoft 365 등)로 인증하세요.',
        "Start asking Claude questions about your organization's knowledge.": '조직의 지식에 대해 Claude에게 질문을 시작하세요.',
        'The more connectors you enable, the more comprehensive your search results will be. You can always add more connectors later by clicking "Connect" in the project\'s Instructions section.': '더 많은 커넥터를 활성화할수록 검색 결과가 더 포괄적입니다. 프로젝트의 Instructions 섹션에서 "Connect"를 클릭하여 나중에 더 많은 커넥터를 추가할 수 있습니다.',
        "That's a lot of data … is this safe?": '데이터가 많은데… 안전한가요?',
        "In short, yes. Enterprise Search only shows what you already have permission to access in the original connected tool. Plus, your conversations remain private, and your connected data isn't indexed or": '간단히 말해, 네. Enterprise 검색은 원래 연결된 도구에서 이미 접근 권한이 있는 것만 표시합니다. 또한 대화는 비공개로 유지되며, 연결된 데이터는 색인되거나',
        "What questions do you frequently ask colleagues that could be answered by searching your organization's documents and communications?": '조직의 문서와 커뮤니케이션을 검색하면 답할 수 있는, 동료에게 자주 묻는 질문은 무엇인가요?',
        'Are there onboarding or training scenarios where Enterprise Search could help new team members get up to speed faster?': 'Enterprise 검색이 새 팀원의 적응을 더 빠르게 도울 수 있는 온보딩이나 교육 시나리오가 있나요?',
        'Which data sources would be most valuable to connect for your specific role?': '특정 역할에 가장 유용한 연결 데이터 소스는 무엇인가요?',
        "In the next lesson, you'll learn about Research mode—Claude's capability for deep, multi-step investigations that go beyond quick lookups to comprehensive analysis.": '다음 레슨에서는 Research 모드에 대해 배웁니다—빠른 검색을 넘어 포괄적 분석까지 수행하는 Claude의 심층적, 다단계 조사 기능입니다.',
        'For more information on Enterprise Search, visit the': 'Enterprise 검색에 대한 자세한 정보는',
    },
    'Research mode for deep dives': {
        'Research mode for deep dives': '심층 분석을 위한 Research 모드',
        'Explain what Research does: systematic, multi-source investigation': 'Research가 수행하는 체계적이고 다중 소스 조사를 설명할 수 있습니다',
        'Identify when to use Research for comprehensive information gathering': '포괄적인 정보 수집을 위해 Research를 언제 사용해야 하는지 파악할 수 있습니다',
        'Understand how Research works with extended thinking to deliver thorough reports': 'Research가 확장된 사고와 함께 작동하여 철저한 보고서를 제공하는 방법을 이해할 수 있습니다',
        'Write effective Research prompts for complex investigations': '복잡한 조사를 위한 효과적인 Research 프롬프트를 작성할 수 있습니다',
        'Video: Researching with Claude': '영상: Claude로 리서치하기',
        'Research transforms how Claude finds and analyzes information.': 'Research는 Claude가 정보를 찾고 분석하는 방식을 변환합니다.',
        'Instead of a single search, Claude operates agentically—conducting multiple searches that build on each other while determining exactly what to investigate next. It explores different angles of your question automatically and works through open questions systematically.': '단일 검색 대신, Claude는 에이전트적으로 작동합니다—서로를 기반으로 하는 여러 검색을 수행하면서 다음에 무엇을 조사할지 정확히 결정합니다. 질문의 다양한 각도를 자동으로 탐구하고 열린 질문을 체계적으로 해결합니다.',
        'Research delivers comprehensive answers in minutes.': 'Research는 몇 분 안에 포괄적인 답변을 제공합니다.',
        'Most reports complete in 5 to 15 minutes, though more complex investigations may take up to 45 minutes—work that would typically require hours of manual research.': '대부분의 보고서는 5~15분 내에 완료되지만, 더 복잡한 조사는 최대 45분이 소요될 수 있습니다—일반적으로 수시간의 수동 조사가 필요한 작업입니다.',
        'Extended thinking is automatically enabled with Research.': 'Research에서는 확장된 사고가 자동으로 활성화됩니다.',
        'This powerful combination lets Claude both plan its approach thoughtfully and gather comprehensive information, breaking complex requests into manageable pieces.': '이 강력한 조합을 통해 Claude는 접근 방식을 신중하게 계획하고 포괄적인 정보를 수집하며, 복잡한 요청을 관리 가능한 조각으로 나눌 수 있습니다.',
        'Citations make verification easy.': '인용으로 검증이 쉬워집니다.',
        "Research delivers thorough answers complete with easy-to-check citations, so you can trust Claude's findings and quickly verify sources yourself.": 'Research는 확인하기 쉬운 인용이 포함된 철저한 답변을 제공하므로, Claude의 발견을 신뢰하고 직접 소스를 빠르게 검증할 수 있습니다.',
        'What is Research?': 'Research란 무엇인가요?',
        "Research is an advanced feature that transforms Claude from a conversational assistant into a systematic investigator. When you enable Research, Claude doesn't just answer your question—it explores it from multiple angles, synthesizing information from across the web and your connected integrations.": 'Research는 Claude를 대화형 어시스턴트에서 체계적인 조사관으로 변환하는 고급 기능입니다. Research를 활성화하면 Claude는 단순히 질문에 답하는 것이 아니라—여러 각도에서 탐구하며, 웹과 연결된 통합 서비스 전반의 정보를 종합합니다.',
        'Think of it as having a skilled research assistant who can spend hours gathering information, cross-referencing sources, and compiling a comprehensive report—except it happens in minutes instead of hours.': '숙련된 연구 보조원이 정보를 수집하고, 소스를 교차 참조하며, 포괄적인 보고서를 작성하는 데 수시간을 쓰는 것과 같습니다—단지 수시간이 아닌 몇 분 안에 이루어집니다.',
        "Research is particularly valuable when you need more than a quick answer. It's designed for situations where a thorough understanding requires pulling together information from multiple sources, comparing different perspectives, and synthesizing findings into actionable insights.": 'Research는 빠른 답변 이상이 필요할 때 특히 유용합니다. 철저한 이해를 위해 여러 소스의 정보를 모으고, 다양한 관점을 비교하며, 발견을 실행 가능한 인사이트로 종합해야 하는 상황을 위해 설계되었습니다.',
        'When to use Research': 'Research를 사용해야 할 때',
        'Understanding when to use Research versus other Claude capabilities helps you get the best results for your specific needs.': 'Research와 다른 Claude 기능을 언제 사용해야 하는지 이해하면 특정 요구에 최적의 결과를 얻는 데 도움이 됩니다.',
        'Use Research when you need:': '다음이 필요할 때 Research를 사용하세요:',
        'Comprehensive reports that synthesize information from multiple sources': '여러 소스의 정보를 종합하는 포괄적인 보고서',
        'In-depth analysis across the web and your connected integrations (like Google Workspace)': '웹과 연결된 통합 서비스(Google Workspace 등) 전반의 심층 분석',
        'Thorough investigations that would typically require hours of manual work': '일반적으로 수시간의 수동 작업이 필요한 철저한 조사',
        'Comparative analysis, such as evaluating competitors or vendor options': '경쟁사 또는 벤더 옵션 평가와 같은 비교 분석',
        'Reports with citations you can verify': '검증할 수 있는 인용이 포함된 보고서',
        'Consider web search instead when:': '대신 웹 검색을 고려해야 할 때:',
        "You need a quick, specific fact (like today's stock price or a company's address)": '빠르고 구체적인 사실이 필요할 때 (오늘의 주가나 회사 주소 등)',
        'The answer requires only one or two sources': '답변에 하나 또는 두 개의 소스만 필요할 때',
        'Speed matters more than comprehensiveness': '포괄성보다 속도가 더 중요할 때',
        'Consider extended thinking instead when:': '대신 확장된 사고를 고려해야 할 때:',
        "You need deep reasoning on a complex problem that doesn't require external information": '외부 정보가 필요 없는 복잡한 문제에 대한 깊은 추론이 필요할 때',
        "You're working on mathematical problems, code debugging, or logical analysis": '수학 문제, 코드 디버깅 또는 논리적 분석을 할 때',
        'The answer comes from reasoning through a problem rather than gathering information': '정보 수집이 아닌 문제를 통한 추론에서 답이 나올 때',
        'How Research works': 'Research 작동 방식',
        "When you enable Research, you're activating a multi-step process that goes far beyond a simple web search.": 'Research를 활성화하면 단순한 웹 검색을 훨씬 넘어서는 다단계 프로세스가 활성화됩니다.',
        'Step 1: Claude plans its approach.': '1단계: Claude가 접근 방식을 계획합니다.',
        'When Research is enabled, extended thinking automatically activates. This lets Claude break down your request, identify what information it needs, and plan how to investigate different angles of your question.': 'Research가 활성화되면 확장된 사고가 자동으로 활성화됩니다. 이를 통해 Claude가 요청을 분해하고, 필요한 정보를 파악하며, 질문의 다양한 각도를 조사하는 방법을 계획할 수 있습니다.',
        'Step 2: Claude conducts multiple searches.': '2단계: Claude가 여러 검색을 수행합니다.',
        'Rather than running a single search, Claude conducts many searches that build on each other. It determines what to investigate next based on what it finds, pursuing promising leads and filling in gaps.': '단일 검색을 실행하는 대신, Claude는 서로를 기반으로 하는 여러 검색을 수행합니다. 발견한 내용을 바탕으로 다음에 무엇을 조사할지 결정하고, 유망한 단서를 추적하며 빈 부분을 채웁니다.',
        'Step 3: Claude synthesizes findings.': '3단계: Claude가 발견을 종합합니다.',
        'After gathering information from multiple sources—including the web and any connected integrations like Gmail, Google Calendar, or Google Drive—Claude compiles everything into a comprehensive, well-organized report.': '웹과 Gmail, Google Calendar, Google Drive와 같은 연결된 통합 서비스를 포함한 여러 소스에서 정보를 수집한 후, Claude가 모든 것을 포괄적이고 잘 구성된 보고서로 편집합니다.',
        'Step 4: Claude provides citations.': '4단계: Claude가 인용을 제공합니다.',
        'Every claim in Research reports links back to its source, making it easy to verify information and dig deeper when needed.': 'Research 보고서의 모든 주장은 소스로 링크되어, 정보를 검증하고 필요할 때 더 깊이 파고드는 것이 쉽습니다.',
        'Using Research in practice': '실전에서 Research 사용하기',
        "Here's how to enable and use Research:": 'Research를 활성화하고 사용하는 방법은 다음과 같습니다:',
        'button on the bottom left of your chat interface': '채팅 인터페이스 왼쪽 하단의 버튼',
        'Click to enable—the button turns blue when Research is active': '클릭하여 활성화—Research가 활성 상태이면 버튼이 파란색으로 변합니다',
        'Enter your prompt and submit': '프롬프트를 입력하고 제출하세요',
        "Claude will work in the background, and you'll see progress indicators as it searches and analyzes": 'Claude가 백그라운드에서 작업하며, 검색 및 분석 진행 표시가 나타납니다',
        "Web search must be enabled for Research to function. If you haven't already turned on web search, do so in your Search and tools settings.": 'Research가 작동하려면 웹 검색이 활성화되어 있어야 합니다. 아직 웹 검색을 켜지 않았다면 검색 및 도구 설정에서 켜세요.',
        'Tips for effective Research prompts': '효과적인 Research 프롬프트 팁',
        'Since Research can take 5 to 45 minutes depending on complexity, investing time in crafting your prompt pays off. Here are some strategies:': 'Research는 복잡도에 따라 5~45분이 소요될 수 있으므로, 프롬프트를 작성하는 데 시간을 투자하는 것이 좋습니다. 몇 가지 전략을 소개합니다:',
        'Be specific about your goals.': '목표를 구체적으로 설명하세요.',
        'Instead of "Tell me about the EV market," try "Analyze the electric vehicle battery market—identify key players, technology trends, and supply chain challenges that might affect investment decisions."': '"전기차 시장에 대해 알려주세요" 대신 "전기차 배터리 시장을 분석하세요—주요 업체, 기술 트렌드, 투자 결정에 영향을 미칠 수 있는 공급망 과제를 파악하세요."를 시도하세요.',
        'Specify the sections or structure you want.': '원하는 섹션이나 구조를 지정하세요.',
        'Claude will organize its findings around the structure you provide. For example: "Compare venue options for a team offsite including: location and accessibility, meeting space and amenities, catering options, and pricing considerations."': 'Claude는 제공한 구조를 기반으로 발견을 정리합니다. 예: "팀 외부 행사를 위한 장소 옵션을 비교하세요: 위치 및 접근성, 회의 공간 및 편의시설, 케이터링 옵션, 가격 고려사항 포함."',
        'Include relevant constraints.': '관련 제약 조건을 포함하세요.',
        'Budget ranges, timelines, geographic requirements, and other parameters help Claude focus its research on relevant options.': '예산 범위, 일정, 지리적 요구사항 및 기타 매개변수는 Claude가 관련 옵션에 연구를 집중하는 데 도움이 됩니다.',
        'Ask Claude to help refine your prompt.': 'Claude에게 프롬프트를 개선하는 데 도움을 요청하세요.',
        "If you're not sure how to frame your research question, you can even ask Claude to help you write a better Research prompt before enabling the feature.": '연구 질문을 어떻게 구성해야 할지 잘 모르겠다면, 기능을 활성화하기 전에 Claude에게 더 나은 Research 프롬프트를 작성하는 데 도움을 요청할 수도 있습니다.',
        'Working with connected integrations': '연결된 통합 서비스와 작업하기',
        'When you have Google Workspace or other integrations connected, Research becomes even more powerful. Claude can pull context from your emails, calendar, and documents alongside web research.': 'Google Workspace 또는 기타 통합 서비스가 연결되어 있으면 Research가 더욱 강력해집니다. Claude는 웹 조사와 함께 이메일, 캘린더, 문서에서 맥락을 가져올 수 있습니다.',
        'For example, you might ask Claude to:': '예를 들어, Claude에게 다음을 요청할 수 있습니다:',
        '"Summarize what\'s been discussed about Project X across my emails and Slack, then research industry best practices for similar initiatives"': '"내 이메일과 Slack에서 프로젝트 X에 대해 논의된 내용을 요약한 다음, 유사한 이니셔티브에 대한 업계 모범 사례를 조사해 주세요"',
        '"Review my calendar commitments for next week and research each company I\'m meeting with"': '"다음 주 캘린더 약속을 검토하고 만나게 될 각 회사를 조사해 주세요"',
        '"Find all internal documents about our pricing strategy and compare to how competitors are positioning themselves"': '"우리의 가격 전략에 대한 모든 내부 문서를 찾아 경쟁사의 포지셔닝과 비교해 주세요"',
        'When using Research with integrations, you can steer Claude by saying things like "Pull relevant context from my Google Drive" or "Include insights from my recent emails on this topic."': 'Research를 통합 서비스와 함께 사용할 때, "내 Google Drive에서 관련 맥락을 가져와 주세요" 또는 "이 주제에 대한 최근 이메일의 인사이트를 포함해 주세요"와 같이 말하여 Claude를 안내할 수 있습니다.',
        'What research tasks in your work typically require gathering information from multiple sources?': '업무에서 일반적으로 여러 소스의 정보를 수집해야 하는 조사 작업은 무엇인가요?',
        'How might combining Research with your connected integrations (like Google Workspace) change your workflow?': 'Research를 연결된 통합 서비스(Google Workspace 등)와 결합하면 워크플로가 어떻게 바뀔 수 있을까요?',
        "What's a complex question you've been putting off because it would take too much research time?": '너무 많은 조사 시간이 소요되어 미뤄왔던 복잡한 질문은 무엇인가요?',
        "In the next section we're putting it all together. You'll see how everything you've learned comes together through real-world use cases organized by role, and discover additional ways to interact with Claude beyond the web interface.": '다음 섹션에서는 모든 것을 종합합니다. 역할별로 구성된 실제 사용 사례를 통해 배운 모든 것이 어떻게 결합되는지 보고, 웹 인터페이스를 넘어 Claude와 상호작용하는 추가 방법을 발견합니다.',
        'For more information on Research, including video tutorials, visit the': '영상 튜토리얼을 포함한 Research에 대한 자세한 정보는',
    },
}

def translate_file(filepath, translations):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    all_trans = {**COMMON, **translations}
    sorted_items = sorted(all_trans.items(), key=lambda x: len(x[0]), reverse=True)
    for eng, kor in sorted_items:
        if eng in content:
            content = content.replace(eng, kor)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    return content != original

for lesson_name, translations in FILES.items():
    matches = [f for f in os.listdir(FOLDER)
               if f.startswith(lesson_name) and f.endswith('.html') and f != 'index.html']
    if not matches:
        print(f'  [SKIP] No file found for: {lesson_name}')
        continue
    fpath = os.path.join(FOLDER, matches[0])
    changed = translate_file(fpath, translations)
    status = 'TRANSLATED' if changed else 'NO CHANGE'
    print(f'  [{status}] {matches[0]}')

print('\nPart 5 translation complete!')
