#!/usr/bin/env python3
"""Translate all SingleFile HTML files from English to Korean."""
import os

FOLDER = os.path.dirname(os.path.abspath(__file__))

# 공통 UI/내비게이션 번역 (모든 파일에 적용)
COMMON = {
    'Header Navigation': '헤더 내비게이션',
    '>Courses<': '>강좌<',
    '>My Courses<': '>내 강좌<',
    'My Profile': '내 프로필',
    'Sign Out': '로그아웃',
    '>Previous<': '>이전<',
    '>Next<': '>다음<',
    '>Downloads<': '>다운로드<',
    'Course Overview': '강좌 개요',
    'Estimated time: 20 minutes': '예상 시간: 20분',
    'Estimated time: 15 minutes': '예상 시간: 15분',
    'By the end of this lesson you\'ll be able to:': '이 레슨을 마치면 다음을 할 수 있습니다:',
    'Share your feedback': '피드백을 공유하세요',
    'As you progress through the course, we\'d love to hear how you\'re using skills in your work, plus any feedback you may have.': '강좌를 진행하면서 스킬을 업무에 어떻게 활용하고 계신지, 그리고 피드백이 있으시면 알려주세요.',
    'Lesson reflection': '레슨 되돌아보기',
    'What\'s next': '다음 단계',
}

# 파일별 콘텐츠 번역
FILES = {
    'What are skills': {
        'title="What are skills?"': 'title="스킬이란 무엇인가?"',
        '>What are skills?<': '>스킬이란 무엇인가?<',
        'Define what Claude Code skills are and how they work': 'Claude Code 스킬이 무엇이며 어떻게 작동하는지 정의하기',
        'Explain where skills live (personal vs. project directories)': '스킬이 어디에 저장되는지 설명하기 (개인 디렉토리 vs. 프로젝트 디렉토리)',
        'Distinguish between skills, CLAUDE.md, and slash commands': '스킬, CLAUDE.md, 슬래시 명령어의 차이를 구별하기',
        'Identify scenarios where skills are the right customization tool': '스킬이 적합한 커스터마이징 도구인 시나리오를 파악하기',
        'This video introduces skills — reusable markdown files that teach Claude Code how to handle specific tasks automatically. Instead of repeating instruc': '이 영상은 스킬을 소개합니다 — Claude Code에게 특정 작업을 자동으로 처리하는 방법을 가르치는 재사용 가능한 마크다운 파일입니다. 매번 지시를 반복하는 대신',
        'Skills are folders of instructions': '스킬은 지시사항이 담긴 폴더입니다',
        'that Claude Code can discover and use to handle tasks more accurately. Each skill lives in a': 'Claude Code가 발견하고 사용하여 작업을 더 정확하게 처리할 수 있습니다. 각 스킬은',
        'file with a name and description in its frontmatter': '파일에 이름과 설명이 frontmatter에 포함되어 있습니다',
        'Claude uses the description to match skills to requests.': 'Claude는 설명을 사용하여 스킬을 요청에 매칭합니다.',
        'When you ask Claude to do something, it compares your request against available skill descriptions and activates the ones that match': 'Claude에게 무언가를 요청하면, 사용 가능한 스킬 설명과 비교하여 일치하는 것을 활성화합니다',
        'and follow you across all projects.': '모든 프로젝트에서 따라다닙니다.',
        'inside a repository and are shared with anyone who clones it': '저장소 내에 있으며 클론하는 모든 사람과 공유됩니다',
        'Skills load on demand': '스킬은 필요할 때 로드됩니다',
        '— unlike CLAUDE.md (which loads into every conversation) or slash commands (which require explicit invocation), skills activate automatically when Cla': '— CLAUDE.md(모든 대화에 로드됨)나 슬래시 명령어(명시적 호출 필요)와 달리, 스킬은 Claude가 자동으로 활성화합니다',
        'explaining the same thing to Claude repeatedly': 'Claude에게 같은 것을 반복적으로 설명하는 것',
        ", that's a skill waiting to be written": ', 그것은 작성을 기다리는 스킬입니다',
        'Every time you explain your team\'s coding standards to Claude, you\'re repeating yourself. Every PR review, you re-describe how you want feedback struc': '팀의 코딩 표준을 Claude에게 설명할 때마다 반복하게 됩니다. PR 리뷰마다 피드백 구조를 다시 설명하게 됩니다',
        'A skill is a markdown file that teaches Claude how to do something once. Claude then applies that knowledge automatically whenever it\'s relevant.': '스킬은 Claude에게 한 번 무언가를 가르치는 마크다운 파일입니다. 그러면 Claude는 관련될 때마다 자동으로 그 지식을 적용합니다.',
        'Skills are folders of instructions and resources that Claude Code can discover and use to handle tasks more accurately. Each skill lives in a': '스킬은 Claude Code가 발견하고 사용하여 작업을 더 정확하게 처리할 수 있는 지시사항과 리소스가 담긴 폴더입니다. 각 스킬은',
        'file with a name and description in its frontmatter.': '파일에 이름과 설명이 frontmatter에 포함되어 있습니다.',
        'The description is how Claude decides whether to use the skill. When you ask Claude to review a PR, it matches your request against available skill de': '설명은 Claude가 스킬 사용 여부를 결정하는 방법입니다. Claude에게 PR 리뷰를 요청하면, 사용 가능한 스킬 설명과 매칭합니다',
        "Here's what a skill's frontmatter looks like:": '스킬의 frontmatter는 다음과 같습니다:',
        'Below the frontmatter, you write the actual instructions — your review checklist, formatting preferences, or whatever Claude needs to know for that ta': 'frontmatter 아래에 실제 지시사항을 작성합니다 — 리뷰 체크리스트, 서식 기본 설정, 또는 해당 작업에 대해 Claude가 알아야 할 모든 것',
        'You can store skills in different places depending on who needs them:': '필요한 사람에 따라 스킬을 다른 곳에 저장할 수 있습니다:',
        '(your home directory). These follow you across all your projects — your commit message style, your documentation format, how you like code explained.': '(홈 디렉토리). 이것들은 모든 프로젝트에서 따라다닙니다 — 커밋 메시지 스타일, 문서 형식, 코드 설명 방식 등.',
        'inside the root directory of your repository. Anyone who clones the repo gets these skills automatically. This is where team standards live, like your': '저장소 루트 디렉토리 안에 있습니다. 저장소를 클론하면 자동으로 이 스킬을 얻습니다. 팀 표준이 여기에 있습니다, 예를 들어',
        'On Windows, personal skills live in': 'Windows에서 개인 스킬은 다음 위치에 있습니다',
        'Project skills get committed to version control alongside your code, so the whole team shares them.': '프로젝트 스킬은 코드와 함께 버전 관리에 커밋되므로 팀 전체가 공유합니다.',
        'What Are Skills': '스킬이란 무엇인가',
        'Where Skills Live': '스킬이 저장되는 곳',
        'Skills vs. CLAUDE.md vs. Slash Commands': '스킬 vs. CLAUDE.md vs. 슬래시 명령어',
        'When to Use Skills': '스킬을 사용할 때',
        'Claude Code has several ways to customize behavior. Skills are unique because they\'re automatic and task-specific. Here\'s how they compare:': 'Claude Code에는 동작을 커스터마이징하는 여러 방법이 있습니다. 스킬은 자동적이고 작업별로 특화되어 있다는 점에서 고유합니다. 비교하면 다음과 같습니다:',
        'files load into every conversation. If you want Claude to always use TypeScript\'s strict mode, that goes in CLAUDE.md.': '파일은 모든 대화에 로드됩니다. Claude가 항상 TypeScript strict 모드를 사용하게 하려면 CLAUDE.md에 넣으세요.',
        'load on demand when they match your request. Claude only loads the name and description initially, so they don\'t fill up your entire context window. Y': '요청과 일치하면 필요할 때 로드됩니다. Claude는 처음에 이름과 설명만 로드하므로 전체 컨텍스트 윈도우를 채우지 않습니다.',
        "require you to explicitly type them. Skills don't. Claude applies them when it recognizes the situation.": '명시적으로 입력해야 합니다. 스킬은 그렇지 않습니다. Claude는 상황을 인식하면 자동으로 적용합니다.',
        "When Claude matches a skill to your request, you'll see it load in the terminal:": 'Claude가 스킬을 요청에 매칭하면 터미널에서 로드되는 것을 볼 수 있습니다:',
        'Skills work best for specialized knowledge that applies to specific tasks:': '스킬은 특정 작업에 적용되는 전문 지식에 가장 적합합니다:',
        'Code review standards your team follows': '팀이 따르는 코드 리뷰 표준',
        'Commit message formats you prefer': '선호하는 커밋 메시지 형식',
        'Brand guidelines for your organization': '조직의 브랜드 가이드라인',
        'Documentation templates for specific types of docs': '특정 유형의 문서를 위한 문서 템플릿',
        'Debugging checklists for particular frameworks': '특정 프레임워크를 위한 디버깅 체크리스트',
        "The rule of thumb is simple: if you find yourself explaining the same thing to Claude repeatedly, that's a skill waiting to be written.": '경험 법칙은 간단합니다: Claude에게 같은 것을 반복적으로 설명하고 있다면, 그것은 작성을 기다리는 스킬입니다.',
        "Think about your most recent interactions with Claude Code. Which instructions did you find yourself repeating? How might a skill have saved you time?": '최근 Claude Code와의 상호작용을 생각해 보세요. 어떤 지시사항을 반복하고 있었나요? 스킬이 어떻게 시간을 절약해 줄 수 있었을까요?',
        "Consider your team's workflow. Which standards or processes would benefit most from being encoded as skills?": '팀의 워크플로우를 생각해 보세요. 어떤 표준이나 프로세스가 스킬로 인코딩하면 가장 도움이 될까요?',
        "In the next lesson, you'll create your first skill from scratch and learn how Claude Code discovers, matches, and loads skills behind the scenes.": '다음 레슨에서는 처음부터 스킬을 만들고 Claude Code가 뒤에서 어떻게 스킬을 발견, 매칭, 로드하는지 배웁니다.',
    },
    'Creating your first skill': {
        'title="Creating your first skill"': 'title="첫 번째 스킬 만들기"',
        '>Creating your first skill<': '>첫 번째 스킬 만들기<',
        'Create a skill from scratch with proper frontmatter structure': '올바른 frontmatter 구조로 처음부터 스킬 만들기',
        'Test and verify that a skill loads correctly in Claude Code': 'Claude Code에서 스킬이 올바르게 로드되는지 테스트하고 확인하기',
        'Explain how Claude Code matches incoming requests to available skills': 'Claude Code가 들어오는 요청을 사용 가능한 스킬에 매칭하는 방법 설명하기',
        'Describe the skill priority hierarchy (Enterprise, Personal, Project, Plugins)': '스킬 우선순위 계층 구조 설명하기 (Enterprise, Personal, Project, Plugins)',
        "This video walks through building a skill from scratch — a personal PR description skill that works across all your projects. You'll see exactly how t": '이 영상은 처음부터 스킬을 만드는 과정을 안내합니다 — 모든 프로젝트에서 작동하는 개인 PR 설명 스킬입니다. 정확히 어떻게',
        'directory containing a': '디렉토리에',
        'with metadata (name, description) in frontmatter and instructions below': 'frontmatter에 메타데이터(이름, 설명)가 있고 그 아래에 지시사항이 포함된',
        'only skill names and descriptions at startup': '시작 시 스킬 이름과 설명만',
        ', then matches incoming requests against those descriptions using semantic matching': ', 그런 다음 의미론적 매칭을 사용하여 들어오는 요청을 해당 설명과 매칭합니다',
        'before Claude loads the full skill content into context': 'Claude가 전체 스킬 내용을 컨텍스트에 로드하기 전에',
        'Priority for name conflicts:': '이름 충돌 시 우선순위:',
        'Enterprise → Personal → Project → Plugins': 'Enterprise → Personal → Project → Plugins',
        'To update a skill, edit its': '스킬을 업데이트하려면',
        '. To remove one, delete its directory.': '을 편집하세요. 삭제하려면 디렉토리를 삭제하세요.',
        'Always restart Claude Code': '항상 Claude Code를 재시작하세요',
        'for changes to take effect': '변경 사항이 적용되려면',
        "Let's walk through creating a skill from scratch, then look at how Claude Code actually loads and matches skills behind the scenes.": '처음부터 스킬을 만드는 과정을 살펴본 다음, Claude Code가 실제로 뒤에서 어떻게 스킬을 로드하고 매칭하는지 알아보겠습니다.',
        "We'll build a personal skill that teaches Claude how to write PR descriptions in a consistent format. Since it's a personal skill, it lives in your ho": '일관된 형식으로 PR 설명을 작성하는 방법을 Claude에게 가르치는 개인 스킬을 만들겠습니다. 개인 스킬이므로 홈',
        'First, create a directory for your skill inside the skills folder. The directory name should match your skill name:': '먼저 skills 폴더 안에 스킬 디렉토리를 만드세요. 디렉토리 이름은 스킬 이름과 일치해야 합니다:',
        'file inside that directory. The file has two parts separated by frontmatter dashes:': '해당 디렉토리 안에 파일을 만드세요. 파일은 frontmatter 구분선으로 나뉜 두 부분이 있습니다:',
        "identifies your skill. The": '이 스킬을 식별합니다.',
        "tells Claude when to use it — this is the matching criteria. Everything after the second set of dashes is the instructions Claude follows when the ski": 'Claude에게 언제 사용할지 알려줍니다 — 이것이 매칭 기준입니다. 두 번째 구분선 이후의 모든 내용은 스킬이 활성화될 때 Claude가 따르는 지시사항입니다',
        "Claude Code loads skills at startup, so restart your session after creating one. You can verify it's available by checking the available skills list.": 'Claude Code는 시작 시 스킬을 로드하므로, 스킬을 만든 후 세션을 재시작하세요. 사용 가능한 스킬 목록을 확인하여 사용 가능한지 확인할 수 있습니다.',
        'You should see your skill listed. To test it, make some changes on a branch and say something like "write a PR description for my changes." Claude wil': '스킬이 목록에 표시되어야 합니다. 테스트하려면 브랜치에서 변경을 한 후 "내 변경 사항에 대한 PR 설명을 작성해 줘"와 같이 말하세요. Claude가',
        'How Skill Matching Works': '스킬 매칭 작동 방식',
        'When Claude Code starts, it scans four locations for skills but only loads the': 'Claude Code가 시작되면 네 곳에서 스킬을 스캔하지만',
        "— not the full content. This is an important detail.": '만 로드합니다 — 전체 내용이 아닙니다. 이것은 중요한 세부사항입니다.',
        'When you send a request, Claude compares your message against the descriptions of all available skills. For example, "explain what this function does"': '요청을 보내면 Claude는 모든 사용 가능한 스킬의 설명과 메시지를 비교합니다. 예를 들어 "이 함수가 무엇을 하는지 설명해 줘"',
        'Once a match is found, Claude asks you to confirm loading the skill. This confirmation step keeps you aware of what context Claude is pulling in. Afte': '일치하는 것이 발견되면 Claude는 스킬 로드를 확인하도록 요청합니다. 이 확인 단계는 Claude가 어떤 컨텍스트를 가져오는지 인식하게 해줍니다. 그 후',
        'file and follows its instructions.': '파일을 읽고 지시사항을 따릅니다.',
        "If you clone a repository that has a skill with the same name as one of your personal skills, which one wins? There's a clear priority order:": '개인 스킬과 같은 이름의 스킬이 있는 저장소를 클론하면 어떤 것이 우선할까요? 명확한 우선순위가 있습니다:',
        '— managed settings, highest priority': '— 관리 설정, 최고 우선순위',
        '— your home directory (': '— 홈 디렉토리 (',
        'directory inside a repository': '저장소 내부의 디렉토리',
        '— installed plugins, lowest priority': '— 설치된 플러그인, 최저 우선순위',
        'This lets organizations enforce standards through enterprise skills while still allowing individual customization. If your company has an enterprise "': '이를 통해 조직은 enterprise 스킬로 표준을 강제하면서도 개인 커스터마이징을 허용할 수 있습니다. 회사에 enterprise "',
        'To avoid conflicts, use descriptive names. Instead of just "review," use something like "frontend-review" or "backend-review."': '충돌을 피하려면 설명적인 이름을 사용하세요. 단순히 "review" 대신 "frontend-review"나 "backend-review"와 같은 것을 사용하세요.',
        'Updating and Removing Skills': '스킬 업데이트 및 제거',
        'To update a skill, edit its': '스킬을 업데이트하려면',
        'file. To remove one, delete its directory. Restart Claude Code after any changes for them to take effect.': '파일을 편집하세요. 삭제하려면 디렉토리를 삭제하세요. 변경 사항이 적용되려면 Claude Code를 재시작하세요.',
        "What's one task in your daily workflow that you could turn into a skill right now? What would the description look like?": '일상적인 워크플로우에서 지금 바로 스킬로 만들 수 있는 작업이 있나요? 설명은 어떻게 작성할 건가요?',
        "How might the priority hierarchy affect your team's skill management strategy? Would you rely more on personal or project-level skills?": '우선순위 계층이 팀의 스킬 관리 전략에 어떤 영향을 미칠까요? 개인 스킬과 프로젝트 수준 스킬 중 어느 것에 더 의존하시겠습니까?',
        "In the next lesson, you'll learn about advanced configuration options including metadata fields, tool restrictions with": '다음 레슨에서는 메타데이터 필드, 도구 제한 등 고급 설정 옵션에 대해 배웁니다',
        ', and how to structure larger skills using progressive disclosure and multi-file organization.': ', 그리고 점진적 공개와 다중 파일 구성을 사용하여 더 큰 스킬을 구조화하는 방법을 배웁니다.',
    },
    'Configuration and multi-file skills': {
        'title="Configuration and multi-file skills"': 'title="설정 및 다중 파일 스킬"',
        '>Configuration and multi-file skills<': '>설정 및 다중 파일 스킬<',
        'Configure advanced skill metadata fields including allowed-tools and model': 'allowed-tools 및 model을 포함한 고급 스킬 메타데이터 필드 설정하기',
        'Write effective skill descriptions that reliably trigger on the right requests': '적절한 요청에서 안정적으로 트리거되는 효과적인 스킬 설명 작성하기',
        'Use allowed-tools to restrict what Claude can do when a skill is active': 'allowed-tools를 사용하여 스킬 활성화 시 Claude가 할 수 있는 것을 제한하기',
        'Organize complex skills using progressive disclosure and multi-file structures': '점진적 공개와 다중 파일 구조를 사용하여 복잡한 스킬 구성하기',
        'This video covers the advanced techniques that make skills more powerful: the full set of metadata fields, how to write descriptions that trigger reli': '이 영상은 스킬을 더 강력하게 만드는 고급 기술을 다룹니다: 전체 메타데이터 필드 세트, 안정적으로 트리거되는 설명 작성법',
        'are optional but powerful additions': '선택 사항이지만 강력한 추가 기능입니다',
        'answers two questions': '두 가지 질문에 답합니다',
        ': What does the skill do? When should Claude use it?': ': 스킬이 무엇을 하는가? Claude가 언제 사용해야 하는가?',
        "restricts which tools Claude can use when the skill is active — useful for read-only or security-sensitive workflows": '스킬이 활성화되었을 때 Claude가 사용할 수 있는 도구를 제한합니다 — 읽기 전용이나 보안에 민감한 워크플로우에 유용합니다',
        'Progressive disclosure': '점진적 공개',
        ': keep SKILL.md under 500 lines and link to supporting files (references, scripts, assets) that Claude reads only when needed': ': SKILL.md를 500줄 이하로 유지하고 Claude가 필요할 때만 읽는 지원 파일(참조, 스크립트, 에셋)에 링크하세요',
        'Scripts execute without loading their contents into context': '스크립트는 내용을 컨텍스트에 로드하지 않고 실행됩니다',
        '— only the output consumes tokens, keeping context efficient': '— 출력만 토큰을 소비하여 컨텍스트를 효율적으로 유지합니다',
        "A basic skill works with just a name and description, but there are several advanced techniques that can make your skills much more effective in Claud": '기본 스킬은 이름과 설명만으로 작동하지만, Claude에서 스킬을 훨씬 더 효과적으로 만드는 여러 고급 기술이 있습니다',
        'Skill Metadata Fields': '스킬 메타데이터 필드',
        'The agent skills open standard supports several fields in the SKILL.md frontmatter. Two are required, and the rest are optional:': 'agent skills 오픈 표준은 SKILL.md frontmatter에서 여러 필드를 지원합니다. 두 개는 필수이고 나머지는 선택 사항입니다:',
        "(required) — Identifies your skill. Use lowercase letters, numbers, and hyphens only. Maximum 64 characters. Should match your directory name.": '(필수) — 스킬을 식별합니다. 소문자, 숫자, 하이픈만 사용하세요. 최대 64자. 디렉토리 이름과 일치해야 합니다.',
        "(required) — Tells Claude when to use the skill. Maximum 1,024 characters. This is the most important field because Claude uses it for matching.": '(필수) — Claude에게 스킬 사용 시기를 알려줍니다. 최대 1,024자. Claude가 매칭에 사용하므로 가장 중요한 필드입니다.',
        '(optional) — Restricts which tools Claude can use when the skill is active.': '(선택) — 스킬이 활성화되었을 때 Claude가 사용할 수 있는 도구를 제한합니다.',
        '(optional) — Specifies which Claude model to use for the skill.': '(선택) — 스킬에 사용할 Claude 모델을 지정합니다.',
        'Writing Effective Descriptions': '효과적인 설명 작성하기',
        "Be explicit with your instructions. If someone told you \"your job is to help with docs,\" you wouldn't know what to do — and Claude thinks the same way": '지시사항을 명시적으로 작성하세요. 누군가 "문서를 도와주는 게 당신의 일이야"라고 말하면 무엇을 해야 할지 모르겠죠 — Claude도 마찬가지입니다',
        'A good description answers two questions:': '좋은 설명은 두 가지 질문에 답합니다:',
        'What does the skill do?': '스킬이 무엇을 하는가?',
        'When should Claude use it?': 'Claude가 언제 사용해야 하는가?',
        "If your skill isn't triggering when you expect it to, try adding more keywords that match how you actually phrase your requests. The description is wh": '스킬이 예상대로 트리거되지 않으면 실제로 요청을 표현하는 방식과 일치하는 키워드를 더 추가해 보세요. 설명은',
        'Restricting Tools with allowed-tools': 'allowed-tools로 도구 제한하기',
        'Sometimes you want a skill that can only read files, not modify them. This is useful for security-sensitive workflows, read-only tasks, or any situati': '때로는 파일을 읽기만 하고 수정하지 않는 스킬이 필요합니다. 이것은 보안에 민감한 워크플로우, 읽기 전용 작업 또는',
        ". When this skill is active, Claude can only use those tools without asking permission — no editing, no writing.": '. 이 스킬이 활성화되면 Claude는 권한 요청 없이 해당 도구만 사용할 수 있습니다 — 편집이나 쓰기 불가.',
        "entirely, the skill doesn't restrict anything. Claude uses its normal permission model.": '를 완전히 생략하면 스킬은 아무것도 제한하지 않습니다. Claude는 일반적인 권한 모델을 사용합니다.',
        "Skills share Claude's context window with your conversation. When Claude activates a skill, it loads the contents of that SKILL.md into context. But s": '스킬은 대화와 Claude의 컨텍스트 윈도우를 공유합니다. Claude가 스킬을 활성화하면 SKILL.md의 내용을 컨텍스트에 로드합니다. 하지만',
        "Cramming everything into one 2,000-line file has two problems: it takes up a lot of context window space, and it's not fun to maintain.": '모든 것을 2,000줄짜리 파일 하나에 넣으면 두 가지 문제가 있습니다: 컨텍스트 윈도우 공간을 많이 차지하고 유지 보수가 즐겁지 않습니다.',
        'Progressive disclosure solves this. Keep essential instructions in SKILL.md and put detailed reference material in separate files that Claude reads on': '점진적 공개가 이를 해결합니다. SKILL.md에 필수 지시사항을 유지하고 상세한 참조 자료는 Claude가 필요할 때만 읽는 별도 파일에 넣으세요',
        'The open standard suggests organizing your skill directory with:': '오픈 표준은 스킬 디렉토리를 다음과 같이 구성할 것을 제안합니다:',
        '— Additional documentation': '— 추가 문서',
        '— Images, templates, or other data files': '— 이미지, 템플릿 또는 기타 데이터 파일',
        'Then in SKILL.md, link to the supporting files with clear instructions about when to load them:': '그런 다음 SKILL.md에서 언제 로드할지에 대한 명확한 지시사항과 함께 지원 파일에 링크하세요:',
        'In this example, Claude reads': '이 예시에서 Claude는',
        "only when someone asks about system design. If they're asking where to add a component, it never loads that file. It's like having a table of contents": '누군가 시스템 설계에 대해 물을 때만 읽습니다. 컴포넌트를 어디에 추가할지 묻는 경우 해당 파일을 로드하지 않습니다. 목차를 갖는 것과 같습니다',
        'A good rule of thumb:': '좋은 경험 법칙:',
        'keep SKILL.md under 500 lines': 'SKILL.md를 500줄 이하로 유지하세요',
        '. If you\'re exceeding that, consider whether the content should be split into separate reference files.': '. 이를 초과한다면 내용을 별도의 참조 파일로 분할해야 하는지 고려하세요.',
        'Using Scripts Efficiently': '스크립트를 효율적으로 사용하기',
        'Scripts in your skill directory can run without loading their contents into context. The script executes and only the output consumes tokens. The key ': '스킬 디렉토리의 스크립트는 내용을 컨텍스트에 로드하지 않고 실행할 수 있습니다. 스크립트가 실행되고 출력만 토큰을 소비합니다. 핵심은',
        'This is particularly useful for:': '이것은 특히 다음에 유용합니다:',
        'Environment validation': '환경 검증',
        'Data transformations that need to be consistent': '일관성이 필요한 데이터 변환',
        'Operations that are more reliable as tested code than generated code': '생성된 코드보다 테스트된 코드가 더 안정적인 작업',
        "Think about a skill you'd like to build that involves multiple files. How would you structure the SKILL.md versus supporting reference files?": '여러 파일이 관련된 스킬을 만든다면 SKILL.md와 지원 참조 파일을 어떻게 구조화하시겠습니까?',
        'Are there workflows in your team where restricting tool access with': '팀에서 도구 접근을 제한하면',
        'would add an important safety layer?': '중요한 안전 계층을 추가할 수 있는 워크플로우가 있나요?',
        "In the next lesson, we'll compare skills to the other ways you can customize Claude Code — CLAUDE.md, subagents, hooks, and MCP servers — so you can c": '다음 레슨에서는 스킬을 Claude Code를 커스터마이징하는 다른 방법들 — CLAUDE.md, 서브에이전트, 후크, MCP 서버 — 과 비교합니다',
    },
    'Skills vs. other Claude Code features': {
        'title="Skills vs. other Claude Code features"': 'title="스킬 vs. 다른 Claude Code 기능"',
        '>Skills vs. other Claude Code features<': '>스킬 vs. 다른 Claude Code 기능<',
        'Compare skills to CLAUDE.md, subagents, hooks, and MCP servers': '스킬을 CLAUDE.md, 서브에이전트, 후크, MCP 서버와 비교하기',
        'Choose the right Claude Code customization feature for a given use case': '주어진 사용 사례에 적합한 Claude Code 커스터마이징 기능 선택하기',
        'Design a complementary setup that combines multiple features effectively': '여러 기능을 효과적으로 결합하는 보완적 설정 설계하기',
        'Claude Code offers several customization options, and choosing the wrong one can lead to unnecessary complexity. This video breaks down when to use sk': 'Claude Code는 여러 커스터마이징 옵션을 제공하며, 잘못된 것을 선택하면 불필요한 복잡성을 초래할 수 있습니다. 이 영상은 언제 스킬을 사용할지',
        'loads into every conversation and is best for always-on project standards.': '모든 대화에 로드되며 항상 적용되는 프로젝트 표준에 가장 적합합니다.',
        'load on demand and are best for task-specific expertise': '필요할 때 로드되며 작업별 전문 지식에 가장 적합합니다',
        'run in isolated execution contexts — use them for delegated work.': '격리된 실행 컨텍스트에서 실행됩니다 — 위임된 작업에 사용하세요.',
        'add knowledge to your current conversation': '현재 대화에 지식을 추가합니다',
        'are event-driven (fire on file saves, tool calls).': '이벤트 기반입니다 (파일 저장, 도구 호출 시 실행).',
        'are request-driven (activate based on what you\'re asking)': '요청 기반입니다 (요청 내용에 따라 활성화)',
        'provide external tools and integrations — a different category entirely from skills': '외부 도구와 통합을 제공합니다 — 스킬과는 완전히 다른 범주입니다',
        'Each feature handles its own specialty —': '각 기능은 고유한 전문 분야를 처리합니다 —',
        'rather than forcing everything into one approach': '모든 것을 하나의 접근 방식에 강제로 넣기보다는',
        'Claude Code offers several customization options: Skills, CLAUDE.md, subagents, hooks, and MCP servers. They solve different problems, and knowing whe': 'Claude Code는 여러 커스터마이징 옵션을 제공합니다: 스킬, CLAUDE.md, 서브에이전트, 후크, MCP 서버. 서로 다른 문제를 해결하며, 어떤 것을',
        "CLAUDE.md loads into every conversation, always. If you want Claude to use TypeScript strict mode in your project, put it in your CLAUDE.md file.": 'CLAUDE.md는 항상 모든 대화에 로드됩니다. 프로젝트에서 Claude가 TypeScript strict 모드를 사용하게 하려면 CLAUDE.md 파일에 넣으세요.',
        "Skills load on demand. When Claude matches a request to a skill, that skill's instructions join the conversation. Your PR review checklist doesn't nee": '스킬은 필요할 때 로드됩니다. Claude가 요청을 스킬에 매칭하면 해당 스킬의 지시사항이 대화에 참여합니다. PR 리뷰 체크리스트는',
        'Project-wide standards that always apply': '항상 적용되는 프로젝트 전체 표준',
        'Constraints like "never modify the database schema"': '"데이터베이스 스키마를 절대 수정하지 마세요"와 같은 제약 조건',
        'Framework preferences and coding style': '프레임워크 선호도와 코딩 스타일',
        'Task-specific expertise': '작업별 전문 지식',
        "Knowledge that's only relevant sometimes": '때때로만 관련 있는 지식',
        'Detailed procedures that would clutter every conversation': '모든 대화를 어지럽히는 상세한 절차',
        'Skills add knowledge to your current conversation. When a skill activates, its instructions join the existing context.': '스킬은 현재 대화에 지식을 추가합니다. 스킬이 활성화되면 지시사항이 기존 컨텍스트에 참여합니다.',
        'Subagents run in a separate context. They receive a task, work on it independently, and return results. They\'re isolated from the main conversation.': '서브에이전트는 별도의 컨텍스트에서 실행됩니다. 작업을 받아 독립적으로 작업하고 결과를 반환합니다. 메인 대화와 격리되어 있습니다.',
        'You want to delegate a task to a separate execution context': '별도의 실행 컨텍스트에 작업을 위임하고 싶을 때',
        'You need different tool access than the main conversation': '메인 대화와 다른 도구 접근이 필요할 때',
        'You want isolation between delegated work and your main context': '위임된 작업과 메인 컨텍스트 사이의 격리를 원할 때',
        'You want to enhance Claude\'s knowledge for the current task': '현재 작업을 위해 Claude의 지식을 향상시키고 싶을 때',
        'The expertise applies throughout a conversation': '전문 지식이 대화 전체에 적용될 때',
        "Hooks fire on events. A hook might run a linter every time Claude saves a file, or validate input before certain tool calls. They're event-driven.": '후크는 이벤트에 의해 실행됩니다. 후크는 Claude가 파일을 저장할 때마다 린터를 실행하거나 특정 도구 호출 전에 입력을 검증할 수 있습니다. 이벤트 기반입니다.',
        "Skills are request-driven. They activate based on what you're asking.": '스킬은 요청 기반입니다. 요청 내용에 따라 활성화됩니다.',
        'Operations that should run on every file save': '모든 파일 저장 시 실행되어야 하는 작업',
        'Validation before specific tool calls': '특정 도구 호출 전 검증',
        "Automated side effects of Claude's actions": 'Claude 작업의 자동화된 부수 효과',
        "Knowledge that informs how Claude handles requests": 'Claude가 요청을 처리하는 방법을 알려주는 지식',
        "Guidelines that affect Claude's reasoning": 'Claude의 추론에 영향을 미치는 가이드라인',
        'Putting It All Together': '모두 합치기',
        'A typical setup might include:': '일반적인 설정에는 다음이 포함될 수 있습니다:',
        '— always-on project standards': '— 항상 적용되는 프로젝트 표준',
        '— task-specific expertise that loads on demand': '— 필요할 때 로드되는 작업별 전문 지식',
        '— automated operations triggered by events': '— 이벤트에 의해 트리거되는 자동화된 작업',
        '— isolated execution contexts for delegated work': '— 위임된 작업을 위한 격리된 실행 컨텍스트',
        '— external tools and integrations': '— 외부 도구와 통합',
        "Each handles its own specialty. Don't force everything into skills when another option fits better — and you can use multiple at a time. Skills provid": '각각은 고유한 전문 분야를 처리합니다. 다른 옵션이 더 적합할 때 모든 것을 스킬에 강제로 넣지 마세요 — 여러 개를 동시에 사용할 수 있습니다. 스킬은',
        'Use skills when you have knowledge that Claude should apply automatically when the topic is relevant, and combine them with other features for compreh': '주제가 관련될 때 Claude가 자동으로 적용해야 할 지식이 있을 때 스킬을 사용하고, 포괄적인',
        'Look at your current CLAUDE.md file. Is there anything in it that would work better as a skill (loaded only when relevant)?': '현재 CLAUDE.md 파일을 살펴보세요. 스킬로 만들면 더 좋을 것이 있나요 (관련될 때만 로드)?',
        "Think about your team's development workflow. Which combination of Claude Code features (skills, hooks, subagents, MCP) would address your most common": "팀의 개발 워크플로우를 생각해 보세요. 어떤 Claude Code 기능 조합(스킬, 후크, 서브에이전트, MCP)이 가장 일반적인",
        "In the next lesson, you'll learn how to share skills with your team and organization — from committing them to repositories, to distributing via plugi": '다음 레슨에서는 팀과 조직에 스킬을 공유하는 방법을 배웁니다 — 저장소에 커밋하는 것부터 플러그인을 통해 배포하는 것까지',
    },
    'Sharing skills': {
        'title="Sharing skills"': 'title="스킬 공유하기"',
        '>Sharing skills<': '>스킬 공유하기<',
        'Share skills with your team by committing them to a Git repository': 'Git 저장소에 커밋하여 팀과 스킬 공유하기',
        'Distribute skills across projects through plugins and marketplaces': '플러그인과 마켓플레이스를 통해 프로젝트 간 스킬 배포하기',
        'Deploy skills organization-wide using enterprise managed settings': 'enterprise 관리 설정을 사용하여 조직 전체에 스킬 배포하기',
        'Configure custom subagents to use specific skills': '특정 스킬을 사용하도록 커스텀 서브에이전트 설정하기',
        'Skills become much more valuable when they\'re shared across a team or organization. This video covers the three main distribution methods — repository': '스킬은 팀이나 조직 전체에서 공유될 때 훨씬 더 가치가 있습니다. 이 영상은 세 가지 주요 배포 방법을 다룹니다 — 저장소',
        'are shared automatically through Git — anyone who clones the repo gets them': 'Git을 통해 자동으로 공유됩니다 — 저장소를 클론하면 스킬을 얻습니다',
        'let you distribute skills across repositories via marketplaces for broader community use': '마켓플레이스를 통해 더 넓은 커뮤니티 사용을 위해 저장소 간 스킬을 배포할 수 있습니다',
        'Enterprise managed settings': 'Enterprise 관리 설정',
        'deploy skills organization-wide with the highest priority, ideal for mandatory standards and compliance': '최고 우선순위로 조직 전체에 스킬을 배포하며, 필수 표준과 규정 준수에 이상적입니다',
        "Subagents don't automatically see your skills": '서브에이전트는 자동으로 스킬을 볼 수 없습니다',
        "— you must explicitly list skills in a custom agent's frontmatter": '— 커스텀 에이전트의 frontmatter에 명시적으로 스킬을 나열해야 합니다',
        'Built-in agents (Explorer, Plan, Verify)': '내장 에이전트 (Explorer, Plan, Verify)',
        "can't access skills at all": '는 스킬에 전혀 접근할 수 없습니다',
        '— only custom subagents defined in': '— 다음에서 정의된 커스텀 서브에이전트만',
        "Skills become much more valuable when they're shared. A PR review skill that only you use is helpful, but that same skill shared across your entire te": '스킬은 공유될 때 훨씬 더 가치가 있습니다. 본인만 사용하는 PR 리뷰 스킬도 유용하지만, 같은 스킬을 팀 전체에서 공유하면',
        'Committing Skills to Your Repository': '저장소에 스킬 커밋하기',
        'The simplest sharing method is committing skills directly to your repository. Place them in': '가장 간단한 공유 방법은 저장소에 직접 스킬을 커밋하는 것입니다.',
        ', and anyone who clones the repo gets those skills automatically — no extra installation needed.': '에 배치하면 저장소를 클론하는 모든 사람이 자동으로 스킬을 얻습니다 — 추가 설치가 필요 없습니다.',
        'When you push updates, everyone gets them on the next pull. This approach works well for:': '업데이트를 푸시하면 다음 pull에서 모든 사람이 받습니다. 이 접근 방식은 다음에 적합합니다:',
        'Team coding standards': '팀 코딩 표준',
        'Project-specific workflows': '프로젝트별 워크플로우',
        'Skills that reference your codebase structure': '코드베이스 구조를 참조하는 스킬',
        'directory contains your agents, hooks, skills, and settings — all version-controlled and shared with the team through normal Git workflows.': '디렉토리에는 에이전트, 후크, 스킬, 설정이 포함되어 있습니다 — 모두 버전 관리되며 일반적인 Git 워크플로우를 통해 팀과 공유됩니다.',
        'Distributing Skills Through Plugins': '플러그인을 통한 스킬 배포',
        'Plugins are a way to extend Claude Code with custom functionality designed to be shared across teams and projects. In your plugin project, create a': '플러그인은 팀과 프로젝트 간에 공유되도록 설계된 커스텀 기능으로 Claude Code를 확장하는 방법입니다. 플러그인 프로젝트에서',
        'directory that follows a similar file structure to the': '디렉토리를 만드세요. 파일 구조는',
        'directory — each skill gets its own folder with a': '디렉토리와 유사합니다 — 각 스킬은 자체 폴더에',
        'After you distribute your plugin to a marketplace, other users can discover and install it into Claude Code for themselves.': '플러그인을 마켓플레이스에 배포하면 다른 사용자가 직접 발견하고 Claude Code에 설치할 수 있습니다.',
        "This approach is best when your skills aren't too project-specific and can be useful to community members beyond your immediate team.": '이 접근 방식은 스킬이 너무 프로젝트에 특화되지 않고 직접적인 팀 너머의 커뮤니티 구성원에게도 유용할 수 있을 때 가장 적합합니다.',
        'Enterprise Deployment Through Managed Settings': 'Enterprise 관리 설정을 통한 배포',
        'Administrators can deploy skills organization-wide through managed settings. Enterprise skills take the highest priority — they override personal, pro': '관리자는 관리 설정을 통해 조직 전체에 스킬을 배포할 수 있습니다. Enterprise 스킬은 최고 우선순위를 가집니다 — 개인, 프로젝트',
        'The managed settings file supports features like': '관리 설정 파일은 다음과 같은 기능을 지원합니다',
        'to control where plugins can be installed from:': '플러그인 설치 출처를 제어하는:',
        'This is the right choice for mandatory standards, security requirements, compliance workflows, and coding practices that': '필수 표준, 보안 요구 사항, 규정 준수 워크플로우, 그리고',
        'be consistent across the organization. The keyword here is "must."': '조직 전체에서 일관되어야 하는 코딩 관행에 적합합니다. 여기서 핵심 키워드는 "반드시"입니다.',
        "Here's something that surprises people: subagents don't automatically see your skills. When you delegate a task to a subagent, it starts with a fresh,": '놀라운 점은 서브에이전트가 자동으로 스킬을 보지 못한다는 것입니다. 서브에이전트에 작업을 위임하면 새로운',
        'There are important distinctions to understand:': '이해해야 할 중요한 차이점이 있습니다:',
        "(like Explorer, Plan, and Verify) can't access skills at all": '(Explorer, Plan, Verify 같은)은 스킬에 전혀 접근할 수 없습니다',
        'use skills, but only when you explicitly list them': '스킬을 사용하지만, 명시적으로 나열해야만 합니다',
        'Skills are loaded when the subagent starts, not on demand like in the main conversation': '스킬은 메인 대화에서처럼 필요할 때가 아니라 서브에이전트 시작 시 로드됩니다',
        'To create a custom subagent with skills, add an agent markdown file in': '스킬이 있는 커스텀 서브에이전트를 만들려면',
        'command in Claude Code to create one interactively:': 'Claude Code에서 명령어를 사용하여 대화형으로 만드세요:',
        "The generated agent file includes a": '생성된 에이전트 파일에는',
        'field that lists which skills to load. Here\'s what the frontmatter looks like:': '로드할 스킬을 나열하는 필드가 포함됩니다. frontmatter는 다음과 같습니다:',
        'When you delegate to this subagent, it has both skills loaded and applies them to every review. First make sure the skills exist in your': '이 서브에이전트에 위임하면 두 스킬이 모두 로드되어 모든 리뷰에 적용됩니다. 먼저 스킬이',
        'directory, then either create a new subagent or add the': '디렉토리에 있는지 확인한 다음, 새 서브에이전트를 만들거나',
        "field to an existing agent's markdown file.": '필드를 기존 에이전트의 마크다운 파일에 추가하세요.',
        'This pattern works really well when:': '이 패턴은 다음 경우에 매우 잘 작동합니다:',
        'You want isolated task delegation with specific expertise': '특정 전문 지식으로 격리된 작업 위임을 원할 때',
        'Different subagents need different skills (frontend reviewer vs. backend reviewer)': '다른 서브에이전트에 다른 스킬이 필요할 때 (프론트엔드 리뷰어 vs. 백엔드 리뷰어)',
        'You want to enforce standards in delegated work without relying on prompts': '프롬프트에 의존하지 않고 위임된 작업에서 표준을 강제하고 싶을 때',
        "Which sharing method (repository, plugin, enterprise) makes the most sense for the skills you've been thinking about building?": '어떤 공유 방법(저장소, 플러그인, enterprise)이 만들고자 하는 스킬에 가장 적합한가요?',
        'Do you have workflows where custom subagents with specific skills would improve consistency in delegated work?': '특정 스킬을 가진 커스텀 서브에이전트가 위임된 작업의 일관성을 향상시킬 수 있는 워크플로우가 있나요?',
        "In the final lesson, you'll learn how to troubleshoot common skill issues — from skills that don't trigger, to priority conflicts, to runtime errors —": '마지막 레슨에서는 일반적인 스킬 문제를 해결하는 방법을 배웁니다 — 트리거되지 않는 스킬부터 우선순위 충돌, 런타임 오류까지 —',
    },
    'Troubleshooting skills': {
        'title="Troubleshooting skills"': 'title="스킬 문제 해결"',
        '>Troubleshooting skills<': '>스킬 문제 해결<',
        'Use the skills validator to catch structural issues before debugging': '디버깅 전에 스킬 검증기를 사용하여 구조적 문제 포착하기',
        'Diagnose and fix common skill triggering and loading problems': '일반적인 스킬 트리거 및 로딩 문제 진단하고 수정하기',
        'Resolve skill priority conflicts between enterprise, personal, project, and plugin skills': 'enterprise, 개인, 프로젝트, 플러그인 스킬 간의 우선순위 충돌 해결하기',
        'Debug runtime errors including missing dependencies, permissions, and path issues': '누락된 종속성, 권한, 경로 문제를 포함한 런타임 오류 디버깅하기',
        'When skills don\'t work as expected, the problem usually falls into a few predictable categories. This video walks through each one — from skills that ': '스킬이 예상대로 작동하지 않을 때 문제는 보통 몇 가지 예측 가능한 범주에 속합니다. 이 영상은 각각을 안내합니다 — ',
        'to diagnose loading issues.': '로딩 문제를 진단하기 위해.',
        'skills validator tool': '스킬 검증기 도구',
        '— it catches structural problems before you spend time debugging other things': '— 다른 것을 디버깅하는 데 시간을 쓰기 전에 구조적 문제를 포착합니다',
        ', the cause is almost always the description — add trigger phrases that match how you actually phrase requests': ', 원인은 거의 항상 설명입니다 — 실제로 요청을 표현하는 방식과 일치하는 트리거 문구를 추가하세요',
        'is inside a named directory (not at the skills root) and the file name is exactly': '이름이 있는 디렉토리 안에 있어야 하고(skills 루트가 아님) 파일 이름은 정확히',
        'wrong skill gets used': '잘못된 스킬이 사용됨',
        ', your descriptions are too similar — make them more distinct': ', 설명이 너무 유사합니다 — 더 구별되게 만드세요',
        ', check dependencies, file permissions (': ', 종속성, 파일 권한 (',
        '), and path separators (use forward slashes everywhere)': '), 경로 구분자 (어디서나 슬래시 사용)를 확인하세요',
        "When skills don't work, the problem usually falls into one of a few categories: the skill doesn't trigger, doesn't load, has conflicts, or fails at ru": '스킬이 작동하지 않을 때 문제는 보통 몇 가지 범주 중 하나에 속합니다: 스킬이 트리거되지 않거나, 로드되지 않거나, 충돌이 있거나, 런타임에 실패합니다',
        'Use the Skills Validator': '스킬 검증기 사용하기',
        'The first thing to try is the agent skills verifier command. Installation steps vary by operating system, but using': '가장 먼저 시도할 것은 agent skills 검증기 명령어입니다. 설치 단계는 운영체제마다 다르지만',
        'is the easiest way to get it set up quickly.': '을 사용하면 빠르게 설정할 수 있습니다.',
        'Once installed, either navigate to your skill directory or run the command from anywhere. The validator will catch structural problems before you spen': '설치되면 스킬 디렉토리로 이동하거나 어디서나 명령어를 실행하세요. 검증기는 다른 것을 디버깅하는 데 시간을 쓰기 전에',
        "Skill Doesn't Trigger": '스킬이 트리거되지 않을 때',
        "Your skill exists and passes validation, but Claude isn't using it when you expect. The cause is almost always the description.": '스킬이 존재하고 검증을 통과했지만 Claude가 예상대로 사용하지 않습니다. 원인은 거의 항상 설명입니다.',
        "Claude uses semantic matching, so your request needs to overlap with the description's meaning. If there's not enough overlap, no match. Here's what t": "Claude는 의미론적 매칭을 사용하므로 요청이 설명의 의미와 겹쳐야 합니다. 겹침이 충분하지 않으면 매칭되지 않습니다. 다음을 시도하세요",
        "Check your description against how you're actually phrasing requests": '설명을 실제 요청 표현 방식과 비교하세요',
        'Add trigger phrases users would actually say': '사용자가 실제로 말할 트리거 문구를 추가하세요',
        'Test with variations like "help me profile this," "why is this slow?", "make this faster"': '"이거 프로파일링 해줘", "왜 느리지?", "더 빠르게 만들어줘" 같은 변형으로 테스트하세요',
        'If any variation fails to trigger, add those keywords to your description': '어떤 변형이 트리거에 실패하면 해당 키워드를 설명에 추가하세요',
        'If your skill doesn\'t appear when you ask Claude "what skills are available," check these structural requirements:': '"어떤 스킬이 있어?"라고 Claude에게 물었을 때 스킬이 나타나지 않으면 다음 구조적 요구 사항을 확인하세요:',
        'file must be inside a named directory, not at the skills root': '파일은 이름이 있는 디렉토리 안에 있어야 합니다, skills 루트가 아닙니다',
        'The file name must be exactly': '파일 이름은 정확히',
        "— all caps on \"SKILL\", lowercase \"md\"": '여야 합니다 — "SKILL"은 대문자, "md"는 소문자',
        'to see loading errors. Look for messages mentioning your skill name. Sometimes this alone will point you straight to the problem.': '로딩 오류를 확인하세요. 스킬 이름이 언급된 메시지를 찾으세요. 때로는 이것만으로도 문제를 바로 파악할 수 있습니다.',
        'Wrong Skill Gets Used': '잘못된 스킬이 사용될 때',
        'If Claude uses the wrong skill or seems confused between skills, your descriptions are probably too similar. Make them distinct. Being as specific as ': 'Claude가 잘못된 스킬을 사용하거나 스킬 간에 혼동하는 것 같으면 설명이 너무 유사한 것입니다. 구별되게 만드세요. 가능한 한 구체적으로',
        'Skill Priority Conflicts': '스킬 우선순위 충돌',
        'If your personal skill is being ignored, an enterprise or higher-priority skill might have the same name.': '개인 스킬이 무시되고 있다면, enterprise나 더 높은 우선순위의 스킬이 같은 이름을 가지고 있을 수 있습니다.',
        'For example, if there\'s an enterprise "code-review" skill and you also have a personal "code-review" skill, the enterprise one wins every time. Your o': '예를 들어 enterprise "code-review" 스킬이 있고 개인 "code-review" 스킬도 있다면, enterprise 스킬이 항상 우선합니다. 선택지는',
        'Rename your skill to something more distinct (this is usually the easier path)': '스킬 이름을 더 구별되는 것으로 변경하세요 (보통 이것이 더 쉬운 방법)',
        'Talk to your admin about the enterprise skill': '관리자에게 enterprise 스킬에 대해 문의하세요',
        'Plugin Skills Not Appearing': '플러그인 스킬이 나타나지 않을 때',
        "Installed a plugin but can't see its skills? Clear the cache, restart Claude Code, and reinstall.": '플러그인을 설치했지만 스킬이 보이지 않나요? 캐시를 지우고 Claude Code를 재시작한 후 다시 설치하세요.',
        "If skills still don't appear after that, the plugin structure might be wrong. This is when the validator tool really earns its keep.": '그래도 스킬이 나타나지 않으면 플러그인 구조가 잘못되었을 수 있습니다. 이때 검증기 도구가 진가를 발휘합니다.',
        'The skill loads but fails during execution. A few common causes:': '스킬이 로드되지만 실행 중에 실패합니다. 몇 가지 일반적인 원인:',
        'Missing dependencies:': '누락된 종속성:',
        'If your skill uses external packages, they must be installed. Add dependency info to your skill description so Claude knows what\'s needed.': '스킬이 외부 패키지를 사용하면 설치되어 있어야 합니다. 스킬 설명에 종속성 정보를 추가하여 Claude가 필요한 것을 알 수 있게 하세요.',
        'Scripts need execute permission. Run': '스크립트에 실행 권한이 필요합니다.',
        'on any scripts your skill references.': '스킬이 참조하는 모든 스크립트에 실행하세요.',
        'Use forward slashes everywhere, even on Windows.': 'Windows에서도 어디서나 슬래시(/)를 사용하세요.',
        'Quick Troubleshooting Checklist': '빠른 문제 해결 체크리스트',
        'Improve your description and add trigger phrases.': '설명을 개선하고 트리거 문구를 추가하세요.',
        'Check your path, file name, and YAML syntax.': '경로, 파일 이름, YAML 구문을 확인하세요.',
        'Make descriptions more distinct from each other.': '설명을 서로 더 구별되게 만드세요.',
        'Check the priority hierarchy and rename if needed.': '우선순위 계층을 확인하고 필요하면 이름을 변경하세요.',
        'Plugin skills missing?': '플러그인 스킬이 없나요?',
        'Clear cache and reinstall.': '캐시를 지우고 다시 설치하세요.',
        'Check dependencies, permissions, and paths.': '종속성, 권한, 경로를 확인하세요.',
        'Have you encountered any of these troubleshooting scenarios in your own work? Which fix would have saved you the most time?': '작업 중에 이러한 문제 해결 시나리오를 경험한 적이 있나요? 어떤 수정이 가장 많은 시간을 절약해 주었을까요?',
        'How would you set up a process to validate skills before sharing them with your team?': '팀과 공유하기 전에 스킬을 검증하는 프로세스를 어떻게 설정하시겠습니까?',
        "Congratulations on completing Introduction to Agent Skills! You've learned how to create, configure, share, and troubleshoot skills in Claude Code. As": 'Introduction to Agent Skills 완료를 축하합니다! Claude Code에서 스킬을 만들고, 설정하고, 공유하고, 문제를 해결하는 방법을 배웠습니다.',
        "We'd love to hear how you're using skills in your work, plus any feedback about this course.": '스킬을 업무에 어떻게 활용하고 계신지, 그리고 이 강좌에 대한 피드백을 알려주세요.',
    },
}


def translate_file(filepath, translations):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content

    # 공통 + 파일별 번역 합치기
    all_trans = {**COMMON, **translations}

    # 긴 문자열 먼저 치환 (부분 일치 방지)
    sorted_items = sorted(all_trans.items(), key=lambda x: len(x[0]), reverse=True)

    for eng, kor in sorted_items:
        if eng in content:
            content = content.replace(eng, kor)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    return content != original


# 실행
for lesson_name, translations in FILES.items():
    matches = [f for f in os.listdir(FOLDER)
               if f.startswith(lesson_name) and f.endswith('.html') and f != 'index.html']
    if not matches:
        print(f'  [SKIP] No file found for: {lesson_name}')
        continue

    fpath = os.path.join(FOLDER, matches[0])
    changed = translate_file(fpath, translations)
    status = 'TRANSLATED' if changed else 'NO CHANGE'
    print(f'  [{status}] {matches[0]}')

print('\nTranslation complete!')
